"""Regenerate lib/guides/articles-ru.ts and the /ru/ routes from the files in
lib/guides/articles-ru/. Run after adding or removing a Russian article."""
import os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
d = os.path.join(ROOT, 'lib/guides/articles-ru')
i18n = open(os.path.join(ROOT, 'lib/i18n.ts')).read()
ru_paths = dict(re.findall(r"^  (\w+): '(/ru/[^']+)',$", i18n.split('export const RU_ARTICLES')[1].split('};')[0], re.M))
entries = []
for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
    if not f.endswith('.ts'): continue
    src = open(os.path.join(d, f)).read()
    const = re.search(r'export const (\w+)\s*:', src).group(1)
    page = re.search(r"page: '(\w+)'", src).group(1)
    entries.append((f[:-3], const, page))
lines = ["import type { EnglishPage } from '@/lib/i18n';", ""]
lines += [f"import {{ {c} }} from './articles-ru/{f}';" for f, c, p in entries]
lines += ["import type { Guide } from './types';", "",
  "/** Russian versions of the English-only articles, keyed by page. Generated by",
  " * `scripts/gen-articles-ru.py` from the files in `articles-ru/`. */",
  "export const ARTICLES_RU: Partial<Record<EnglishPage, Guide>> = {"]
lines += [f"  {p}: {c}," for f, c, p in entries]
lines += ["};", ""]
open(os.path.join(ROOT, 'lib/guides/articles-ru.ts'), 'w').write('\n'.join(lines))
for f, c, p in entries:
    route = os.path.join(ROOT, 'app', ru_paths[p].strip('/'))
    os.makedirs(route, exist_ok=True)
    name = p[0].upper() + p[1:] + 'RuPage'
    open(os.path.join(route, 'page.tsx'), 'w').write(f"""import {{ Guide }} from '@/components/Guide';
import {{ ARTICLES_RU, guideMetadata }} from '@/lib/guides';

const guide = ARTICLES_RU.{p}!;

export const metadata = guideMetadata(guide);

export default function {name}() {{
  return <Guide guide={{guide}} />;
}}
""")
print(len(entries), 'russian articles wired')
