"""Regenerate lib/guides/articles-new.ts and the /pt/ /fr/ /it/ /de/ article
routes from lib/guides/articles-{pt,fr,it,de}/. Run after adding an article."""
import os, re
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
i18n = open(os.path.join(ROOT, 'lib/i18n.ts')).read()
block = i18n.split('export const NEW_ARTICLE_PATHS')[1].split('\n};')[0]
LANGS = ['pt', 'fr', 'it', 'de']
paths = {}
for l in LANGS:
    sub = block.split(f'  {l}: {{')[1].split('  },')[0]
    paths[l] = dict(re.findall(r"^    (\w+): '([^']+)',$", sub, re.M))
imports, maps = [], {}
for l in LANGS:
    d = os.path.join(ROOT, 'lib/guides', f'articles-{l}')
    maps[l] = []
    for f in sorted(os.listdir(d)) if os.path.isdir(d) else []:
        if not f.endswith('.ts'): continue
        src = open(os.path.join(d, f)).read()
        const = re.search(r'export const (\w+)\s*:', src).group(1)
        page = re.search(r"page: '(\w+)'", src).group(1)
        imports.append(f"import {{ {const} }} from './articles-{l}/{f[:-3]}';")
        maps[l].append((page, const))
        route = os.path.join(ROOT, 'app', paths[l][page].strip('/'))
        os.makedirs(route, exist_ok=True)
        name = page[0].upper() + page[1:] + l.capitalize() + 'Page'
        open(os.path.join(route, 'page.tsx'), 'w').write(f"""import {{ Guide }} from '@/components/Guide';
import {{ ARTICLES_NEW, guideMetadata }} from '@/lib/guides';

const guide = ARTICLES_NEW.{l}.{page}!;

export const metadata = guideMetadata(guide);

export default function {name}() {{
  return <Guide guide={{guide}} />;
}}
""")
out = ["import type { EnglishPage, NewLang } from '@/lib/i18n';", ""] + imports + ["import type { Guide } from './types';", "",
  "/** Articles in Portuguese, French, Italian and German, keyed by language and page.",
  " * Generated by `scripts/gen-articles-new.py`. */",
  "export const ARTICLES_NEW: Record<NewLang, Partial<Record<EnglishPage, Guide>>> = {"]
for l in LANGS:
    out.append(f"  {l}: {{")
    out += [f"    {p}: {c}," for p, c in maps[l]]
    out.append("  },")
out += ["};", ""]
open(os.path.join(ROOT, 'lib/guides/articles-new.ts'), 'w').write('\n'.join(out))
print({l: len(maps[l]) for l in LANGS})
