import { CITE } from '@/lib/citations';
import type { Guide } from '../types';

export const FOOT_STRENGTHENING_FR: Guide = {
  lang: 'fr',
  page: 'footStrengthening',
  mainSource: CITE.taddeiRRI,
  published: '2026-10-09',
  updated: '2026-10-09',
  title: 'Renforcement du pied\u00A0: exercices et progression',
  description:
    'Exercices de renforcement du pied pour ses petits et grands muscles, d’assis à une jambe. Doses de départ et ce que disent les essais sur les blessures.',
  h1: 'Exercices de renforcement du pied\u00A0: quoi faire et comment progresser',
  lede:
    'Les exercices de renforcement du pied entraînent les petits muscles situés dans le pied et les muscles plus grands qui descendent du mollet. Commencez assis avec l’exercice du pied court, l’écartement des orteils et le lever du gros orteil, puis passez debout, puis sur une jambe. Dans les essais, les muscles du pied sont devenus plus gros et plus forts en environ deux mois.',
  intro: [
    'Cette page est le guide général pour tout le pied. Pour les pieds plats, les orteils ou les chaussures minimalistes, les pages plus spécifiques sont indiquées plus bas.',
  ],
  takeaways: [
    'Dans un essai de 2020 sur 118\u00A0coureurs amateurs, le groupe sans entraînement du pied était 2,42\u00A0fois plus susceptible de se blesser en courant sur 12\u00A0mois que le groupe qui suivait un programme de «\u00A0foot core\u00A0» (gainage du pied) (Taddei et coll.). Il s’agit d’un seul essai.',
    'Dans un essai de 2019 sur 57\u00A0coureurs, environ deux mois d’exercices progressifs du pied, faits au moins cinq fois par semaine, ont rendu chaque muscle du pied mesuré plus gros et plus fort, alors que le groupe témoin n’a pas changé (Ridge et coll.).',
    'Une revue de 2025 portant sur 28\u00A0essais et 1\u00A0399\u00A0personnes a soutenu les exercices du pied pour développer la force du pied, mais a jugé la certitude des preuves faible à très faible (Peters-Dickie et coll.).',
    'Chez des adultes de 60 à 90\u00A0ans, un programme supervisé avec des charges de plus en plus lourdes a augmenté la force des orteils jusqu’à 36\u00A0% en trois mois, alors qu’un programme à domicile ne l’a pas fait (Mickle et coll., 2016).',
    'Pour la fasciite plantaire, ajouter le renforcement du pied aux étirements n’a pas fait mieux que les étirements seuls dans un essai sur 83\u00A0personnes (Kamonseki et coll., 2016).',
  ],
  toc: true,
  sections: [
    {
      h2: 'Quels sont les muscles du pied, et pourquoi les renforcer\u00A0?',
      paragraphs: [
        'Le pied a deux groupes de muscles. Les muscles **intrinsèques** (les petits muscles qui commencent et se terminent dans le pied) se trouvent sous la voûte et entre les os. Ils soutiennent la voûte, écartent les orteils et font les minuscules corrections qui vous maintiennent en équilibre. Les muscles **extrinsèques** (les muscles plus grands qui partent du bas de la jambe et rejoignent le pied par de longs tendons) comprennent le mollet, qui soulève le talon, et les muscles qui tournent et relèvent le pied.',
        'Un article de 2015 de McKeon et coll. a appelé les muscles intrinsèques le «\u00A0foot core\u00A0» (le gainage du pied). L’idée est la même que pour les muscles profonds du tronc\u00A0: de petits stabilisateurs qui permettent aux grands muscles moteurs de bien fonctionner. Selon eux, la prise en charge du pied consiste plus souvent à le soutenir de l’extérieur qu’à entraîner ces muscles, si bien que beaucoup de gens ne les entraînent jamais. C’est un modèle, pas une cause établie de douleur, mais il explique pourquoi les programmes pour le pied entraînent d’abord les petits muscles, puis ajoutent le mollet et l’équilibre.',
        'Un bon travail de force du pied couvre les deux groupes. L’exercice du pied court, l’écartement des orteils et le lever du gros orteil entraînent les muscles intrinsèques, les montées sur pointes entraînent le mollet, et l’équilibre sur une jambe fait travailler les deux ensemble.',
      ],
      cites: [CITE.mcKeon],
    },
    {
      h2: 'Par quels exercices de renforcement du pied commencer\u00A0?',
      keyFact: 'Une revue de 2023 portant sur quatre essais a constaté que la plupart des programmes pour le pied utilisaient des maintiens de 5\u00A0secondes et passaient de la position assise à la position debout (de Souza et coll.).',
      paragraphs: [
        'Commencez par les exercices qui isolent les petits muscles du pied, faits assis, puis ajoutez le travail debout et l’équilibre quand ils deviennent faciles. Une revue de 2023 de de Souza et coll. a examiné quatre essais randomisés sur le renforcement des muscles intrinsèques du pied. La plupart utilisaient l’exercice du pied court et le ramassage de serviette avec les orteils, avec des contractions tenues environ 5\u00A0secondes et une progression de la position assise à la position debout.',
        'Les doses ci-dessous sont des doses de départ. Faites les exercices pieds nus. Si un exercice fait monter la douleur à **6/10 ou plus**, arrêtez pour la journée. Chaque exercice a sa propre page plus détaillée, accessible depuis la [bibliothèque d’exercices](/exercises/) (en anglais).',
      ],
      exercises: [
        {
          name: 'Pied court, assis',
          dose: '3\u00A0séries de 8, tenir chaque fois 5\u00A0secondes',
          often: 'La plupart des séances',
          feel: 'Une contraction sous la voûte, les orteils restant détendus',
          stop: 'Une crampe qui ne passe pas, ou une douleur à 6/10',
          how: 'Asseyez-vous, le pied à plat. Sans plier les orteils, rapprochez l’avant-pied du talon pour que la voûte se soulève un peu. Tenez, puis relâchez. Le mouvement est petit. Si vos orteils agrippent le sol, relâchez et recommencez. La technique complète est sur la page [exercice du pied court](/fr/exercices/pied-court/).',
          media: 'short_foot_seated',
          caption: 'Pied court, assis\u00A0: rapprochez l’avant-pied du talon, orteils à plat',
          alt: 'Une personne assise qui soulève la voûte d’un pied pendant que les orteils restent à plat au sol',
          evidence: { level: 'moderate', why: 'Utilisé dans la plupart des essais de la revue de 2023 sur le renforcement du pied (de Souza), avec des preuves de faible qualité pour des changements de la voûte et de l’équilibre. Jamais testé seul sur les blessures ou la douleur.' },
        },
        {
          name: 'Écarter les orteils',
          dose: '3\u00A0séries de 10',
          often: 'La plupart des séances',
          feel: 'Un travail le long des bords du pied',
          stop: 'Une crampe qui ne passe pas',
          how: 'Le pied à plat, écartez les cinq orteils le plus possible, tenez un instant, puis relâchez. Gardez le talon et l’avant-pied au sol.',
          media: 'toe_spread',
          caption: 'Écarter les orteils\u00A0: écartez largement les orteils, talon et avant-pied au sol',
          alt: 'Un pied nu posé au sol, les orteils écartés',
          evidence: { level: 'early', why: 'Une étude en IRM montre qu’il active les petits muscles du pied (Gooding 2016). Pas testé seul dans un essai sur des résultats cliniques.' },
        },
        {
          name: 'Lever le gros orteil',
          dose: '3\u00A0séries de 8, tenir chaque fois 5\u00A0secondes',
          often: 'La plupart des séances',
          feel: 'Un effort sur le dessus du pied et sous la voûte',
          stop: 'Une douleur à l’articulation du gros orteil',
          how: 'Gardez les quatre petits orteils au sol et levez seulement le gros orteil. Puis essayez l’inverse\u00A0: gros orteil au sol, petits orteils levés. C’est difficile au début. Un petit mouvement suffit.',
          media: 'big_toe_lift',
          caption: 'Lever le gros orteil\u00A0: seul le gros orteil se lève',
          alt: 'Un pied nu avec le gros orteil levé et les autres orteils à plat au sol',
          evidence: { level: 'early', why: 'Une étude en IRM montre qu’il active les petits muscles du pied (Gooding 2016). Utilisé dans des programmes pour le pied, mais pas testé seul.' },
        },
        {
          name: 'Ramasser la serviette',
          dose: '3\u00A0séries de 8, tenir chaque fois 5\u00A0secondes',
          often: 'La plupart des séances',
          feel: 'Un travail sous les orteils et la voûte',
          stop: 'Une crampe qui ne passe pas',
          how: 'Asseyez-vous avec une serviette sous le pied. Recroquevillez les orteils pour tirer la serviette vers vous, tenez, puis relâchez et remettez-la à plat. Cela entraîne les longs muscles des orteils en plus des petits.',
          media: 'towel_scrunch',
          caption: 'Ramasser la serviette\u00A0: recroquevillez les orteils pour ramasser la serviette',
          alt: 'Un pied nu qui recroqueville les orteils pour tirer une serviette sur le sol',
          evidence: { level: 'early', why: 'Utilisé dans la plupart des essais de la revue de 2023, en général avec l’exercice du pied court. Pas testé seul sur la douleur ou les blessures.' },
        },
        {
          name: 'Montées sur pointes, deux pieds',
          dose: '3\u00A0séries de 10',
          often: 'La plupart des séances',
          feel: 'Un travail dans les mollets et sous l’avant des pieds',
          stop: 'Une douleur au talon ou au tendon d’Achille à 6/10',
          how: 'Tenez-vous à un mur. Montez sur l’avant des deux pieds en environ 3\u00A0secondes, puis redescendez en 3\u00A0secondes. Essayez de garder le poids du côté du gros orteil, sans basculer vers l’extérieur. Plus de détails sur la page [montées sur pointes](/fr/exercices/montees-sur-pointes/).',
          media: 'heel_raise_double',
          caption: 'Montées sur pointes sur deux pieds\u00A0: montée lente, descente lente',
          alt: 'Une personne qui se tient à un mur et monte sur l’avant des deux pieds',
          evidence: { level: 'moderate', why: 'Les montées sur pointes sont étayées par un essai dans la fasciite plantaire (Rathleff 2015). Ici, elles entraînent le mollet, le principal muscle extrinsèque du pied.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.gooding, CITE.rathleff],
    },
    {
      h2: 'Comment passer d’assis à debout, puis à une jambe\u00A0?',
      paragraphs: [
        'Faites progresser les exercices de renforcement du pied en faisant passer plus de poids du corps par le pied, une étape à la fois. Le travail assis apprend le mouvement. Debout sur deux pieds, vous ajoutez la moitié de votre poids. Debout sur un pied, vous ajoutez tout votre poids, plus l’équilibre. Ne passez à l’étape suivante que quand l’étape actuelle est facile et contrôlée.',
        'Walkito utilise les trois mêmes étapes pour l’exercice du pied court\u00A0: assis, puis debout sur deux pieds, puis sur une jambe. Quand la voûte est la priorité de votre plan, le plan de la semaine suivante vous fait monter d’une étape si vous avez noté faciles vos deux dernières séances avec cet exercice et que votre douleur du matin n’a pas augmenté. Une séance notée difficile, ou une douleur du matin en hausse de 2\u00A0points, vous fait redescendre d’une étape. Les deux étapes suivantes sont présentées ci-dessous.',
      ],
      bullets: [
        '**Étape 1, assis.** Pied court, écarter les orteils, lever le gros orteil et ramasser la serviette, tous en position assise.',
        '**Étape 2, debout sur deux pieds.** Le maintien du pied court debout, et les montées sur pointes sur deux pieds.',
        '**Étape 3, sur une jambe.** Le maintien du pied court sur une jambe, puis l’équilibre sur une jambe en gardant la voûte soulevée.',
        '**Plus tard.** Les montées sur pointes sur une jambe et, pour les coureurs, de petits sauts. Ce sont des charges plus importantes. Ne les ajoutez que quand l’étape 3 est facile.',
      ],
      exercises: [
        {
          name: 'Pied court, debout',
          dose: '3\u00A0séries de 8, tenir chaque fois 5\u00A0secondes',
          often: 'Une fois la version assise facile',
          feel: 'La voûte qui se soulève sous le poids du corps',
          stop: 'Une douleur à 6/10, ou les orteils qui continuent d’agripper',
          how: 'Debout, le poids réparti également sur les deux pieds. Soulevez les voûtes de la même façon qu’assis, orteils détendus, genoux légèrement fléchis. Tenez, puis relâchez.',
          media: 'short_foot_double',
          caption: 'Pied court, debout\u00A0: soulevez les deux voûtes sans plier les orteils',
          alt: 'Une personne debout qui soulève la voûte des deux pieds',
          evidence: { level: 'moderate', why: 'La progression de la position assise à la position debout a été utilisée dans la plupart des essais de la revue de 2023. Pas testée seule sur la douleur ou les blessures.' },
        },
        {
          name: 'Pied court, sur une jambe',
          dose: '3\u00A0séries de 10, tenir chaque fois 5\u00A0secondes',
          often: 'Une fois la version sur deux pieds facile',
          feel: 'Tout le pied et la cheville qui travaillent pour rester stables',
          stop: 'Une douleur à 6/10, ou vous ne pouvez pas garder la voûte soulevée',
          how: 'Tenez-vous sur un pied près d’un mur. Soulevez la voûte et gardez-la pendant que vous tenez l’équilibre. Touchez le mur si besoin.',
          media: 'short_foot_single',
          caption: 'Pied court, sur une jambe\u00A0: gardez la voûte soulevée en tenant l’équilibre',
          alt: 'Une personne debout sur un pied, la voûte soulevée, une main près d’un mur',
          evidence: { level: 'early', why: 'Utilisé comme dernière étape des programmes de gainage du pied. Peu de recherche sur cette variante précise.' },
        },
        {
          name: 'Équilibre sur une jambe',
          dose: '3\u00A0maintiens de 20\u00A0secondes, chaque jambe',
          often: 'Jours d’équilibre',
          feel: 'De petites corrections constantes dans le pied',
          stop: 'Une douleur à 6/10, ou des vertiges',
          how: 'Tenez-vous sur un pied et fixez un point devant vous. Laissez le pied faire de petites oscillations. C’est ça, le travail. Restez près d’un mur ou d’un plan de travail. Plus de détails sur la page [équilibre sur une jambe](/fr/exercices/equilibre-une-jambe/).',
          media: 'single_leg_hold',
          caption: 'Équilibre sur une jambe\u00A0: laissez le pied faire les corrections',
          alt: 'Une personne en équilibre sur une jambe à côté d’un mur',
          evidence: { level: 'moderate', why: 'L’entraînement de l’équilibre a réduit le taux d’entorses de la cheville dans une méta-analyse (Bellows 2018). Pour la force du pied elle-même, il n’a pas été testé seul.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.bellows],
    },
    {
      h2: 'Les exercices de renforcement du pied préviennent-ils les blessures de course\u00A0?',
      keyFact: 'Dans un essai de 2020 sur 118\u00A0coureurs, ceux qui ne faisaient pas d’entraînement de gainage du pied étaient 2,42\u00A0fois plus susceptibles de se blesser sur 12\u00A0mois (Taddei et coll.).',
      paragraphs: [
        'Les exercices de renforcement du pied ont réduit les blessures de course dans un essai de bonne qualité, mais un seul. En 2020, Taddei et coll. ont réparti au hasard 118\u00A0coureurs amateurs de longue distance entre un groupe gainage du pied (57\u00A0coureurs) et un groupe témoin (61\u00A0coureurs). Le groupe gainage du pied a suivi un cycle supervisé d’environ deux mois sur les muscles du pied et de la cheville, puis a continué l’entraînement avec une supervision à distance. Sur 12\u00A0mois, le groupe témoin était 2,42\u00A0fois plus susceptible de se blesser en courant. Les auteurs ont vu l’effet apparaître après environ quatre à huit mois d’entraînement.',
        'Un essai antérieur plus petit de la même équipe, sur 28\u00A0coureurs, a trouvé qu’environ deux mois d’entraînement du pied augmentaient la taille de chaque muscle du pied mesuré, par rapport au groupe témoin. Les coureurs poussaient aussi plus fort sur le sol.',
        'Les deux essais viennent d’un même groupe de recherche au Brésil, chez des coureurs amateurs qui n’étaient pas blessés au départ. On ne sait pas encore si le programme aide les débutants ou les personnes qui ont déjà mal. Pour les coureurs qui ont actuellement mal au talon, commencez par [douleur au talon chez les coureurs](/heel-pain-runners/) (en anglais).',
      ],
      sourceNote: 'Taddei 2020 (Am J Sports Med)\u00A0: groupe témoin 2,42\u00A0fois plus susceptible de se blesser (IC à 95\u00A0% 1,98 à 3,62), p\u00A0=\u00A00,035, essai randomisé en simple aveugle, suivi de 12\u00A0mois. Taddei 2020 (Phys Ther Sport)\u00A0: essai randomisé de preuve de concept en simple aveugle, 28\u00A0coureurs, volume musculaire mesuré par IRM.',
      cites: [CITE.taddeiRRI, CITE.taddeiMuscle],
    },
    {
      h2: 'Combien de temps faut-il pour renforcer ses pieds\u00A0?',
      keyFact: 'Dans un essai de 2019 sur 57\u00A0coureurs, les muscles du pied ont grossi et gagné en force en environ deux mois, certains muscles étant plus gros après un mois (Ridge et coll.).',
      paragraphs: [
        'Dans les essais, les muscles du pied sont devenus mesurablement plus forts en environ deux mois d’entraînement régulier. En 2019, Ridge et coll. ont réparti au hasard 57\u00A0coureurs entre des exercices de renforcement du pied, la marche en chaussures minimalistes ou aucun changement. Le groupe exercices faisait des exercices contre résistance progressive au moins cinq fois par semaine. Après environ deux mois, chaque muscle du pied mesuré était plus gros et plus fort dans les deux groupes actifs, sans changement dans le groupe témoin. Certains muscles étaient déjà plus gros au contrôle à un mois.',
        'La forme de la voûte change plus lentement, et moins. Une revue de 2023 portant sur quatre essais a constaté que le renforcement des muscles intrinsèques du pied ne modifiait pas l’amplitude de mouvement de la voûte après un mois, mais la modifiait après deux mois, avec des preuves de faible qualité. Dans une petite étude de Mulligan et Cook sur 21\u00A0personnes, sans groupe témoin, la chute du naviculaire (de combien la voûte interne s’affaisse quand vous êtes debout) a diminué en moyenne de 1,8\u00A0mm après un mois d’entraînement du pied court. C’est un changement réel, mais petit.',
      ],
      cites: [CITE.ridgeMinimalist, CITE.deSouzaIFM, CITE.mulliganCook],
    },
    {
      h2: 'Les chaussures minimalistes renforcent-elles les pieds\u00A0?',
      paragraphs: [
        'Dans un essai, marcher en chaussures minimalistes a renforcé les muscles du pied à peu près aussi bien que les exercices du pied. Dans la même étude de 2019 de Ridge et coll., les coureurs qui augmentaient progressivement le nombre de pas quotidiens faits en chaussures minimalistes ont gagné en taille et en force musculaires autant que le groupe exercices, en environ deux mois. Les auteurs ont suggéré que changer de chaussures serait peut-être plus facile à tenir dans la durée que faire des exercices.',
        'Changer trop vite comporte ses propres risques, surtout pour la course. Le guide sur les [chaussures minimalistes](/fr/chaussures-minimalistes/) explique comment faire la transition et qui doit être prudent.',
      ],
      cites: [CITE.ridgeMinimalist],
    },
    {
      h2: 'Les personnes âgées peuvent-elles renforcer leurs pieds\u00A0?',
      keyFact: 'Dans un essai de 2016 chez des adultes de 60 à 90\u00A0ans, un entraînement du pied supervisé et progressif a augmenté la force des orteils jusqu’à 36\u00A0%, alors qu’un programme à domicile ne l’a pas modifiée (Mickle et coll.).',
      paragraphs: [
        'Les personnes âgées peuvent renforcer leurs pieds, et dans un essai, c’est la version supervisée avec des charges de plus en plus lourdes qui a fonctionné. Dans un essai de 2016, Mickle et coll. ont réparti 85\u00A0personnes de 60 à 90\u00A0ans entre un cours supervisé avec des exercices du pied de plus en plus lourds et un programme d’exercices à domicile, avec en plus un groupe distinct de 32\u00A0témoins. Après trois mois, le groupe supervisé avait augmenté sa force des orteils jusqu’à 36\u00A0% et tenait plus longtemps sur une jambe. Le groupe à domicile et le groupe témoin n’ont montré aucun changement de la force des orteils.',
        'Une revue de 2022 portant sur neuf études chez des adultes de 65\u00A0ans et plus a constaté que le renforcement des muscles intrinsèques du pied aidait la force, l’équilibre et la mobilité, et réduisait peut-être le risque de chute, avec peu d’effet sur la façon de marcher. Les auteurs ont jugé la qualité des preuves moyenne.',
        'Passez donc à des versions plus difficiles quand elles deviennent faciles, et gardez un mur ou un plan de travail à portée pour le travail d’équilibre. Si les chutes vous inquiètent, un kinésithérapeute peut mettre en place un programme sûr.',
      ],
      cites: [CITE.mickleToe, CITE.futrellOlder],
    },
    {
      h2: 'Le renforcement du pied aide-t-il en cas de fasciite plantaire ou de pieds plats\u00A0?',
      paragraphs: [
        'Pour la fasciite plantaire, le renforcement du pied ajouté aux étirements n’a pas fait mieux que les étirements seuls dans un essai qui les comparait. En 2016, Kamonseki et coll. ont réparti 83\u00A0personnes atteintes de fasciite plantaire en trois groupes pendant deux mois\u00A0: renforcement du pied plus étirements, renforcement du pied et de la hanche plus étirements, ou étirements seuls. Les trois groupes se sont améliorés en douleur et en fonction, et aucun n’a fait mieux que les autres. Pour la douleur au talon, voir les [exercices pour la fasciite plantaire](/fr/exercices-fasciite-plantaire/).',
        'Pour les pieds plats souples, un essai de 2023 sur 52\u00A0personnes a trouvé qu’un programme mixte incluant l’exercice du pied court modifiait davantage la forme de la voûte que dans le groupe témoin. Les détails, et les limites de l’exercice du pied court seul, sont sur la page [exercices pour pieds plats](/fr/exercices-pieds-plats/). Si votre douleur se situe surtout aux orteils, le guide des [exercices de renforcement des orteils](/fr/exercices-renforcement-orteils/) va plus loin, et pour la cheville il y a les [exercices de renforcement de la cheville](/fr/exercices-renforcement-cheville/).',
      ],
      cites: [CITE.kamonseki, CITE.brijwasi],
    },
    {
      h2: 'Quel est le niveau de preuve du renforcement du pied\u00A0?',
      paragraphs: [
        'Les preuves que les exercices du pied rendent les muscles du pied plus forts vont dans le même sens, mais les études sont petites. Une revue de 2025 de Peters-Dickie et coll. a inclus 28\u00A0essais randomisés et 1\u00A0399\u00A0personnes. Elle a soutenu les exercices du pied pour augmenter la force du pied, mais a jugé la certitude faible à très faible, surtout parce qu’il y avait peu d’études par question et que beaucoup présentaient un risque de biais élevé. Les résultats sur la taille des muscles étaient partagés.',
        'Les preuves que des pieds plus forts signifient moins de blessures sont encore plus minces et reposent surtout sur l’unique essai chez des coureurs présenté plus haut. Le renforcement du pied présente peu de risque, coûte peu et développe bien la force. Savoir s’il préviendra votre prochaine blessure reste une question ouverte. La façon dont ces guides évaluent la recherche est expliquée sur la page [science](/science/) (en anglais).',
      ],
      sourceNote: 'Peters-Dickie 2025\u00A0: les méta-analyses ont montré que les chaussures minimalistes augmentaient la force des orteils 2 à 5, et que les exercices du pied réduisaient le mouvement de la voûte pendant la course\u00A0; certitude faible à très faible.',
      cites: [CITE.petersDickie],
    },
  ],
  faq: [
    {
      q: 'À quelle fréquence faire les exercices de renforcement du pied\u00A0?',
      cites: [CITE.ridgeMinimalist],
      a: 'La plupart des programmes étudiés se faisaient plusieurs fois par semaine. Dans un essai de 2019, des coureurs faisaient des exercices progressifs du pied au moins cinq fois par semaine et ont gagné en taille et en force musculaires en environ deux mois. Une courte séance la plupart des jours est un bon début. Les muscles ont besoin de récupérer\u00A0: si vos pieds sont douloureux le lendemain matin, faites une journée plus légère.',
    },
    {
      q: 'Vaut-il mieux ramasser une serviette ou faire l’exercice du pied court\u00A0?',
      cites: [CITE.jung, CITE.lynn],
      a: 'L’exercice du pied court cible plus directement les muscles de la voûte. Dans une étude en laboratoire sur 20\u00A0personnes, le principal muscle de la voûte interne était nettement plus actif pendant l’exercice du pied court que pendant le ramassage de serviette (Jung 2011). Dans un petit essai sur 24\u00A0personnes, un mois d’entraînement du pied court a davantage amélioré un test d’équilibre que le ramassage de serviette (Lynn 2012). Ramasser la serviette reste une première étape utile et facile.',
    },
    {
      q: 'Les exercices de renforcement du pied doivent-ils faire mal\u00A0?',
      a: 'Non. Vous devez sentir un effort, et peut-être une légère crampe sous la voûte au début, qui passe quand vous relâchez. Une douleur vive ou une douleur à 6/10 ou plus veut dire qu’il faut arrêter pour la journée. Si le même endroit fait mal à chaque fois, ou si la douleur vous empêche de dormir, consultez un professionnel de santé avant de continuer.',
    },
    {
      q: 'Marcher pieds nus suffit-il à renforcer les pieds\u00A0?',
      cites: [CITE.ridgeMinimalist],
      a: 'Cela peut aider. Dans un essai de 2019, des coureurs qui augmentaient lentement leurs pas quotidiens en chaussures minimalistes ont gagné autant de force du pied qu’un groupe exercices, en environ deux mois. C’était un changement progressif, pas un passage brutal. Passer aux pieds nus trop vite peut surcharger le pied\u00A0: progressez lentement et gardez les exercices si vous les aimez.',
    },
    {
      q: 'Le renforcement du pied peut-il remonter une voûte plate\u00A0?',
      cites: [CITE.mulliganCook, CITE.cheng],
      a: 'Seulement un peu, et seulement dans les pieds plats souples. Dans une petite étude sur 21\u00A0personnes sans douleur au pied et sans groupe témoin, la voûte s’affaissait de 1,8\u00A0mm de moins après un mois d’entraînement du pied court. Une revue de 2024 a constaté que les programmes de pied court ne modifiaient les mesures de la voûte que lorsqu’ils duraient plus longtemps. Attendez-vous à un pied plus fort et plus stable, pas à une nouvelle forme de voûte.',
    },
    {
      q: 'Faut-il du matériel pour renforcer ses pieds\u00A0?',
      a: 'Non. Les exercices de cette page demandent un sol, une chaise, une serviette et un mur pour se tenir pendant l’équilibre. Faites-les pieds nus pour voir et sentir le pied bouger. Plus tard, vous pourrez ajouter de la charge avec des montées sur pointes sur une jambe ou un sac à dos, mais le poids du corps suffit pendant longtemps.',
    },
  ],
  redFlags: {
    h2: 'Consultez d’abord un professionnel de santé si',
    bullets: [
      'vous avez des engourdissements, des fourmillements ou des brûlures dans les pieds, ou vous êtes diabétique avec une plaie ou une lésion de la peau',
      'un pied s’affaiblit, ou l’avant du pied traîne ou claque au sol quand vous marchez',
      'une voûte s’affaisse rapidement ou l’intérieur de la cheville est gonflé et douloureux',
      'la douleur se situe à un point précis d’un os et s’aggrave à chaque marche ou course, ce qui peut être une fracture de fatigue',
      'le pied est rouge, chaud ou gonflé, ou vous avez de la fièvre',
      'vous ne pouvez pas mettre de poids sur le pied',
      'la douleur continue de s’aggraver malgré le repos et des exercices plus faciles',
    ],
  },
  program: {
    h2: 'En faire un plan',
    text: 'Walkito construit un plan hebdomadaire autour d’un objectif et comprend les exercices du pied de cette page\u00A0: l’exercice du pied court d’assis à une jambe, écarter les orteils, lever le gros orteil, ramasser la serviette, les montées sur pointes et le travail d’équilibre. Il démarre les exercices de la voûte à 3\u00A0séries de 8 avec des maintiens de 5\u00A0secondes et l’équilibre à 3\u00A0maintiens de 20\u00A0secondes, et à chaque nouveau plan hebdomadaire, il fait monter d’une étape votre exercice prioritaire quand vous avez noté faciles vos deux dernières séances avec lui et que votre douleur du matin n’a pas augmenté.',
    more: [
      'Vous choisissez des séances de 3, 5 ou 10\u00A0minutes. Au début, un court test tous les 14\u00A0jours vérifie l’endurance du mollet, le maintien de la voûte et l’équilibre, pour que vous puissiez voir ce qui change. Walkito est un programme d’exercices pour adultes. Il ne pose pas de diagnostic et ne remplace pas un professionnel de santé.',
    ],
    cta: 'Commencez avec 3\u00A0minutes par jour.',
  },
  crumb: 'Renforcement du pied',
  campaign: 'guide-foot-strength-fr',
};
