/**
 * The copy that is not the app's, in the app's seven languages: the red flags,
 * the call to action, the footer, the footwear tips, the checks, the widget's
 * few words and the /p/ page. Exercises, doses and routines are the app's own
 * catalogues (content.ts) and are never written here.
 *
 * English is the spec's (`walkito-ai-assistant-spec` v1.1, §4-§5) and the
 * source; `Copy` is typed from it, so a language missing a line fails `tsc`.
 * The register follows the app's catalogue in each language: "вы" in Russian,
 * "tú" in Spanish, "você" in Portuguese, "tu" in French and Italian, "du" in
 * German. Never a long dash, never a diagnosis word.
 */
import { pluralCategory } from '@/shared/lib/i18n/plural';

import type { Lang } from './content';

type Forms = { one: string; few?: string; many?: string; other?: string };

/** A counted phrase in the language's own plural form. */
function count(lang: Lang, n: number, forms: Forms): string {
  const cat = pluralCategory(lang, n) as keyof Forms;
  return (forms[cat] ?? forms.other ?? forms.many ?? forms.one).replace('{n}', String(n));
}

const en = {
  disclaimer: 'Walkito is not a medical device and does not diagnose, treat, cure or prevent any medical condition.',
  evidence: 'Exercises chosen from published research and guidelines; Walkito itself hasn’t been tested in a trial.',
  redFlagTitle: 'See a doctor if',
  seeDoctorFirst: 'Please see a doctor before doing exercises.',
  redFlags: {
    injury: 'An injury or fall, and you can’t put weight on it',
    numbness: 'Numbness, tingling or burning',
    swelling: 'Swelling or warmth',
    night_pain: 'Pain at night or at rest',
    arch_flattened: 'One arch suddenly flattened',
    fever: 'Fever',
    diabetes_hot_foot: 'A hot, red or swollen foot with diabetes',
    achilles_pop: 'A sudden pop at the back of the ankle',
    calf_swollen: 'A swollen, warm calf',
  },
  ctaLine: 'In the app, the plan adapts to your foot every day.',
  ctaBullets: ['Reminder before your first step', 'Plan changes with your pain check-in', 'Progress test every 14 days'],
  ctaButton: 'Continue this plan in Walkito',
  appChanges:
    'In the app the plan changes every day with your pain check-in, gets harder when it feels easy, reminds you before your first step, and tests your progress every 14 days.',
  area: { heel_arch: 'Heel and arch', achilles: 'Achilles', flat_feet: 'Flat feet', shin: 'Shin', general_plus: 'Stronger feet' },
  planTitle: {
    heel_arch: 'Heel and arch plan',
    achilles: 'Achilles plan',
    flat_feet: 'Flat feet plan',
    shin: 'Shin plan',
    general_plus: 'Stronger feet plan',
  },
  planIntro: (minutes: number, days: number) => `${minutes} min a day · ${days} days a week`,
  rest: 'Rest',
  restDay: 'Rest day.',
  reliefHigh: 'With pain this high today, keep to this seated routine and nothing else on your feet.',
  planHigh: 'With pain this high today, start with this seated routine. Ask for the week again on a calmer morning.',
  planCode: 'Plan code',
  routineLine: (minutes: number, position: string) => `a ${minutes}-minute routine, ${position}`,
  stretchDose: '10 × 10s per foot',
  stretchHow: 'Pull your toes back, 10 seconds, 10 times.',
  stretchWhen: 'before standing up',
  side: { both: 'Do both feet.', left: 'Do your left foot.', right: 'Do your right foot.' },
  stretchEvidence: 'A stretch studied in published research (DiGiovanni 2003).',
  videoSoon: 'Video coming soon.',
  flatTitle: 'Flat foot check',
  flatOutcome: {
    yes: 'An arch appears, so the flat foot is flexible. That is common, and arch exercises are an option.',
    no: 'Your arch didn’t change - worth showing a physio or podiatrist. Exercises may still help strength, but may not change the shape.',
    not_sure: 'Hard to tell. Watch the video and try again, standing with your weight on both feet.',
  },
  notDiagnose: 'This check does not diagnose.',
  afterWorkTitle: 'After a long day on your feet',
  afterWorkLine: (minutes: number, routine: string) => `A ${minutes}-minute routine for after a shift, from the app's "${routine}" routine:`,
  shoeTipsLabel: 'Shoe tips',
  footwearTitle: 'Footwear tips',
  footwearNoBrands: 'Footwear tips (no brands)',
  shoeTips: [
    { title: 'Supportive shoes', text: 'A firm heel counter and some cushioning under the heel. Swap out shoes whose soles have worn flat.' },
    { title: 'Heel cups', text: 'A soft heel cup can make long days on hard floors easier while the foot gets stronger.' },
    { title: 'Hard floors', text: 'While it hurts, avoid going barefoot on hard floors; wear shoes or supportive slippers at home.' },
    { title: 'Wide feet', text: 'Shop late in the day when feet are largest, check the widest part of the foot has room, and look for shoes sold in wide fittings.' },
  ],
  readyTitle: 'Ready to run?',
  readyPain: (n: number) => `First-step pain over the last two weeks: ${n}/10 (3 or under to start).`,
  readyCalf: (n: number) => `Single-leg calf raises on the painful side: ${n} (20 or more to start).`,
  readyCalfAsk: 'Single-leg calf raises on the painful side: count how many you can do in a row (20 or more to start).',
  readyYes: 'You meet the check. Start with short, easy run-walks: at most 3 runs a week, never on consecutive days.',
  readyMornings: 'Your mornings look ready. Count your single-leg calf raises before the first run.',
  readyNotYet: 'Not yet. Build strength first; the starter plan below works on the calf and the arch.',
  error: 'That did not work. Please try again.',
  ui: {
    start: 'Start {seconds}s',
    seconds: '{seconds}s',
    done: 'Done',
    code: 'Code {code}',
    copied: 'Copied',
    copyCode: 'Copy plan code {code}',
    video: 'Video: {name}',
  },
  page: {
    lang: 'en',
    notFoundTitle: 'Code not recognised',
    notFoundBody: 'Check the code and try again, or get the app and set up your plan there.',
    store: 'Get Walkito on the App Store',
    title: 'Your Walkito plan',
    ready: 'Your plan is ready to continue',
    areaRow: 'Area',
    eachDay: 'Each day',
    daysRow: 'Days a week',
    kitRow: 'Equipment',
    sideRow: 'Side',
    minutes: (n: number) => count('en', n, { one: '{n} minute', other: '{n} minutes' }),
    none: 'None',
    kit: { step: 'Step', towel: 'Towel', band: 'Band', ball: 'Ball', backpack: 'Backpack' },
    side: { both: 'Both feet', left: 'Left foot', right: 'Right foot' },
    open: 'Open in Walkito',
    copy: 'Copy code',
    copied: 'Copied',
    howTo: 'In the app, tap “Got a code from ChatGPT or Claude?” on the first screen and enter this code. Your plan starts with these settings.',
    android: 'Android is coming to Google Play soon.',
  },
};

export type Copy = typeof en;

const ru: Copy = {
  disclaimer: 'Walkito - не медицинское изделие. Приложение не ставит диагнозы, не лечит и не предотвращает заболевания.',
  evidence: 'Упражнения подобраны по опубликованным исследованиям и рекомендациям; сам Walkito в клинических испытаниях не проверялся.',
  redFlagTitle: 'Обратитесь к врачу, если',
  seeDoctorFirst: 'Пожалуйста, покажитесь врачу, прежде чем делать упражнения.',
  redFlags: {
    injury: 'Была травма или падение, и на ногу не встать',
    numbness: 'Онемение, покалывание или жжение',
    swelling: 'Отёк или стопа горячая на ощупь',
    night_pain: 'Боль ночью или в покое',
    arch_flattened: 'Свод одной стопы внезапно опустился',
    fever: 'Температура',
    diabetes_hot_foot: 'Горячая, красная или отёкшая стопа при диабете',
    achilles_pop: 'Внезапный щелчок сзади над пяткой',
    calf_swollen: 'Отёкшая, горячая икра',
  },
  ctaLine: 'В приложении план подстраивается под вашу стопу каждый день.',
  ctaBullets: ['Напоминание до первого шага', 'План меняется по вашей отметке боли', 'Проверка прогресса каждые 14 дней'],
  ctaButton: 'Продолжить план в Walkito',
  appChanges:
    'В приложении план меняется каждый день по вашей отметке боли, усложняется, когда становится легко, напоминает о себе до первого шага и проверяет прогресс каждые 14 дней.',
  area: { heel_arch: 'Пятка и свод', achilles: 'Ахиллово сухожилие', flat_feet: 'Плоскостопие', shin: 'Голень', general_plus: 'Сильные стопы' },
  planTitle: {
    heel_arch: 'План для пятки и свода',
    achilles: 'План для ахиллова сухожилия',
    flat_feet: 'План при плоскостопии',
    shin: 'План для голени',
    general_plus: 'План для сильных стоп',
  },
  planIntro: (minutes, days) =>
    `${count('ru', minutes, { one: '{n} минута', few: '{n} минуты', many: '{n} минут' })} в день · ${count('ru', days, { one: '{n} день', few: '{n} дня', many: '{n} дней' })} в неделю`,
  rest: 'Отдых',
  restDay: 'День отдыха.',
  reliefHigh: 'Сегодня боль сильная: ограничьтесь этой разминкой сидя и больше не нагружайте стопы.',
  planHigh: 'Сегодня боль сильная, начните с этой разминки сидя. Попросите план на неделю в более спокойное утро.',
  planCode: 'Код плана',
  routineLine: (minutes, position) => `${count('ru', minutes, { one: '{n} минута', few: '{n} минуты', many: '{n} минут' })}, ${position}`,
  stretchDose: '10 × 10 с на каждую стопу',
  stretchHow: 'Потяните пальцы на себя, 10 секунд, 10 раз.',
  stretchWhen: 'до того как встать',
  side: { both: 'Делайте на обеих стопах.', left: 'Делайте на левой стопе.', right: 'Делайте на правой стопе.' },
  stretchEvidence: 'Растяжка, изученная в опубликованном исследовании (DiGiovanni, 2003).',
  videoSoon: 'Видео скоро появится.',
  flatTitle: 'Проверка плоскостопия',
  flatOutcome: {
    yes: 'Свод появляется, значит, плоскостопие гибкое. Это часто встречается, и упражнения на свод - хороший вариант.',
    no: 'Свод не изменился - стоит показаться физиотерапевту или подологу. Упражнения всё равно могут укрепить стопу, но форму могут и не изменить.',
    not_sure: 'Трудно сказать. Посмотрите видео и попробуйте ещё раз, стоя с весом на обеих стопах.',
  },
  notDiagnose: 'Эта проверка не ставит диагноз.',
  afterWorkTitle: 'После долгого дня на ногах',
  afterWorkLine: (minutes, routine) =>
    `Разминка после смены на ${count('ru', minutes, { one: '{n} минуту', few: '{n} минуты', many: '{n} минут' })}, из разминки «${routine}» в приложении:`,
  shoeTipsLabel: 'Советы по обуви',
  footwearTitle: 'Советы по обуви',
  footwearNoBrands: 'Советы по обуви (без брендов)',
  shoeTips: [
    { title: 'Обувь с поддержкой', text: 'Жёсткий задник и немного амортизации под пяткой. Меняйте обувь, у которой подошва стёрлась.' },
    { title: 'Подпяточники', text: 'Мягкий подпяточник облегчает долгие дни на твёрдом полу, пока стопа становится сильнее.' },
    { title: 'Твёрдый пол', text: 'Пока болит, не ходите босиком по твёрдому полу; дома носите обувь или тапочки с поддержкой.' },
    { title: 'Широкая стопа', text: 'Покупайте обувь ближе к вечеру, когда стопа больше всего, проверяйте место в самой широкой части и ищите модели широкой полноты.' },
  ],
  readyTitle: 'Можно ли бегать?',
  readyPain: (n) => `Боль при первых шагах за последние две недели: ${n}/10 (чтобы начать, 3 или меньше).`,
  readyCalf: (n) => `Подъёмы на носок на одной ноге, больная сторона: ${n} (чтобы начать, 20 или больше).`,
  readyCalfAsk: 'Подъёмы на носок на одной ноге, больная сторона: посчитайте, сколько получится подряд (чтобы начать, 20 или больше).',
  readyYes: 'Проверка пройдена. Начните с коротких лёгких пробежек с ходьбой: не больше 3 в неделю и никогда два дня подряд.',
  readyMornings: 'По утрам всё готово. Перед первой пробежкой посчитайте подъёмы на носок на одной ноге.',
  readyNotYet: 'Пока рано. Сначала наберите силу; стартовый план ниже работает с икрой и сводом.',
  error: 'Не получилось. Попробуйте ещё раз.',
  ui: {
    start: 'Старт {seconds} с',
    seconds: '{seconds} с',
    done: 'Готово',
    code: 'Код {code}',
    copied: 'Скопировано',
    copyCode: 'Скопировать код плана {code}',
    video: 'Видео: {name}',
  },
  page: {
    lang: 'ru',
    notFoundTitle: 'Код не распознан',
    notFoundBody: 'Проверьте код и попробуйте ещё раз или скачайте приложение и настройте план там.',
    store: 'Скачать Walkito в App Store',
    title: 'Ваш план Walkito',
    ready: 'Ваш план готов, можно продолжать',
    areaRow: 'Зона',
    eachDay: 'Каждый день',
    daysRow: 'Дней в неделю',
    kitRow: 'Инвентарь',
    sideRow: 'Сторона',
    minutes: (n) => count('ru', n, { one: '{n} минута', few: '{n} минуты', many: '{n} минут' }),
    none: 'Нет',
    kit: { step: 'Ступенька', towel: 'Полотенце', band: 'Резинка', ball: 'Мячик', backpack: 'Рюкзак' },
    side: { both: 'Обе стопы', left: 'Левая стопа', right: 'Правая стопа' },
    open: 'Открыть в Walkito',
    copy: 'Скопировать код',
    copied: 'Скопировано',
    howTo: 'В приложении нажмите «Есть код от ChatGPT или Claude?» на первом экране и введите этот код. План начнётся с этими настройками.',
    android: 'Скоро и в Google Play для Android.',
  },
};

const es: Copy = {
  disclaimer: 'Walkito no es un dispositivo médico y no diagnostica, trata, cura ni previene ninguna condición médica.',
  evidence: 'Ejercicios elegidos a partir de investigación publicada y guías; Walkito en sí no se ha probado en un ensayo.',
  redFlagTitle: 'Ve al médico si',
  seeDoctorFirst: 'Por favor, consulta a un médico antes de hacer ejercicios.',
  redFlags: {
    injury: 'Una lesión o caída, y no puedes apoyar el pie',
    numbness: 'Entumecimiento, hormigueo o ardor',
    swelling: 'Hinchazón o calor',
    night_pain: 'Dolor por la noche o en reposo',
    arch_flattened: 'Un arco que se aplanó de repente',
    fever: 'Fiebre',
    diabetes_hot_foot: 'Un pie caliente, rojo o hinchado con diabetes',
    achilles_pop: 'Un chasquido repentino en la parte de atrás del tobillo',
    calf_swollen: 'Una pantorrilla hinchada y caliente',
  },
  ctaLine: 'En la app, el plan se adapta a tu pie cada día.',
  ctaBullets: ['Recordatorio antes de tu primer paso', 'El plan cambia con tu registro de dolor', 'Prueba de progreso cada 14 días'],
  ctaButton: 'Continúa este plan en Walkito',
  appChanges:
    'En la app el plan cambia cada día con tu registro de dolor, sube de nivel cuando te resulta fácil, te avisa antes de tu primer paso y mide tu progreso cada 14 días.',
  area: { heel_arch: 'Talón y arco', achilles: 'Aquiles', flat_feet: 'Pie plano', shin: 'Espinilla', general_plus: 'Pies más fuertes' },
  planTitle: {
    heel_arch: 'Plan para talón y arco',
    achilles: 'Plan para el Aquiles',
    flat_feet: 'Plan para pie plano',
    shin: 'Plan para la espinilla',
    general_plus: 'Plan para pies más fuertes',
  },
  planIntro: (minutes, days) => `${minutes} min al día · ${days} días a la semana`,
  rest: 'Descanso',
  restDay: 'Día de descanso.',
  reliefHigh: 'Con tanto dolor hoy, quédate con esta rutina sentado y no cargues más los pies.',
  planHigh: 'Con tanto dolor hoy, empieza con esta rutina sentado. Vuelve a pedir la semana en una mañana más tranquila.',
  planCode: 'Código del plan',
  routineLine: (minutes, position) => `una rutina de ${minutes} min, ${position}`,
  stretchDose: '10 × 10 s por pie',
  stretchHow: 'Tira de los dedos hacia ti, 10 segundos, 10 veces.',
  stretchWhen: 'antes de levantarte',
  side: { both: 'Hazlo con los dos pies.', left: 'Hazlo con el pie izquierdo.', right: 'Hazlo con el pie derecho.' },
  stretchEvidence: 'Un estiramiento estudiado en investigación publicada (DiGiovanni 2003).',
  videoSoon: 'Video disponible pronto.',
  flatTitle: 'Prueba de pie plano',
  flatOutcome: {
    yes: 'Aparece un arco, así que el pie plano es flexible. Es frecuente, y los ejercicios de arco son una opción.',
    no: 'Tu arco no cambió - vale la pena que lo vea un fisioterapeuta o podólogo. Los ejercicios pueden darte fuerza, aunque quizá no cambien la forma.',
    not_sure: 'Difícil de saber. Mira el video y vuelve a intentarlo, de pie y con el peso en los dos pies.',
  },
  notDiagnose: 'Esta prueba no es un diagnóstico.',
  afterWorkTitle: 'Después de un día largo de pie',
  afterWorkLine: (minutes, routine) => `Una rutina de ${minutes} min para después del turno, de la rutina «${routine}» de la app:`,
  shoeTipsLabel: 'Consejos de calzado',
  footwearTitle: 'Consejos de calzado',
  footwearNoBrands: 'Consejos de calzado (sin marcas)',
  shoeTips: [
    { title: 'Calzado con soporte', text: 'Un contrafuerte firme en el talón y algo de amortiguación debajo. Cambia los zapatos con la suela gastada.' },
    { title: 'Taloneras', text: 'Una talonera blanda puede hacer más llevaderos los días largos sobre suelo duro mientras el pie se fortalece.' },
    { title: 'Suelos duros', text: 'Mientras duela, evita andar descalzo sobre suelo duro; usa zapatos o zapatillas con soporte en casa.' },
    { title: 'Pies anchos', text: 'Compra por la tarde, cuando el pie está más grande, comprueba que la parte más ancha tenga espacio y busca modelos de horma ancha.' },
  ],
  readyTitle: '¿Listo para correr?',
  readyPain: (n) => `Dolor en los primeros pasos en las últimas dos semanas: ${n}/10 (3 o menos para empezar).`,
  readyCalf: (n) => `Elevaciones de talón a una pierna en el lado que duele: ${n} (20 o más para empezar).`,
  readyCalfAsk: 'Elevaciones de talón a una pierna en el lado que duele: cuenta cuántas haces seguidas (20 o más para empezar).',
  readyYes: 'Pasas la prueba. Empieza con trote y caminata cortos y suaves: como mucho 3 salidas a la semana, nunca en días seguidos.',
  readyMornings: 'Tus mañanas están listas. Cuenta tus elevaciones de talón a una pierna antes de la primera salida.',
  readyNotYet: 'Todavía no. Primero gana fuerza; el plan de abajo trabaja la pantorrilla y el arco.',
  error: 'No funcionó. Inténtalo de nuevo.',
  ui: {
    start: 'Empezar {seconds} s',
    seconds: '{seconds} s',
    done: 'Listo',
    code: 'Código {code}',
    copied: 'Copiado',
    copyCode: 'Copiar el código del plan {code}',
    video: 'Video: {name}',
  },
  page: {
    lang: 'es',
    notFoundTitle: 'Código no reconocido',
    notFoundBody: 'Revisa el código e inténtalo de nuevo, o descarga la app y configura tu plan allí.',
    store: 'Descarga Walkito en el App Store',
    title: 'Tu plan de Walkito',
    ready: 'Tu plan está listo para continuar',
    areaRow: 'Zona',
    eachDay: 'Cada día',
    daysRow: 'Días a la semana',
    kitRow: 'Material',
    sideRow: 'Lado',
    minutes: (n) => count('es', n, { one: '{n} minuto', other: '{n} minutos' }),
    none: 'Ninguno',
    kit: { step: 'Escalón', towel: 'Toalla', band: 'Banda', ball: 'Pelota', backpack: 'Mochila' },
    side: { both: 'Los dos pies', left: 'Pie izquierdo', right: 'Pie derecho' },
    open: 'Abrir en Walkito',
    copy: 'Copiar código',
    copied: 'Copiado',
    howTo: 'En la app, toca «¿Tienes un código de ChatGPT o Claude?» en la primera pantalla e introduce este código. Tu plan empieza con estos ajustes.',
    android: 'Pronto en Google Play para Android.',
  },
};

const pt: Copy = {
  disclaimer: 'O Walkito não é um dispositivo médico e não diagnostica, trata, cura nem previne nenhuma condição médica.',
  evidence: 'Exercícios escolhidos a partir de pesquisas publicadas e diretrizes; o próprio Walkito não foi testado em um estudo clínico.',
  redFlagTitle: 'Procure um médico se houver',
  seeDoctorFirst: 'Procure um médico antes de fazer os exercícios.',
  redFlags: {
    injury: 'Uma lesão ou queda, e você não consegue apoiar o pé',
    numbness: 'Dormência, formigamento ou ardência',
    swelling: 'Inchaço ou calor',
    night_pain: 'Dor à noite ou em repouso',
    arch_flattened: 'Um arco que abaixou de repente',
    fever: 'Febre',
    diabetes_hot_foot: 'Um pé quente, vermelho ou inchado com diabetes',
    achilles_pop: 'Um estalo repentino atrás do tornozelo',
    calf_swollen: 'Uma panturrilha inchada e quente',
  },
  ctaLine: 'No app, o plano se adapta ao seu pé todos os dias.',
  ctaBullets: ['Lembrete antes do primeiro passo', 'O plano muda com o seu registro de dor', 'Teste de progresso a cada 14 dias'],
  ctaButton: 'Continue este plano no Walkito',
  appChanges:
    'No app o plano muda todo dia com o seu registro de dor, fica mais difícil quando está fácil, lembra você antes do primeiro passo e testa o seu progresso a cada 14 dias.',
  area: { heel_arch: 'Calcanhar e arco', achilles: 'Tendão de Aquiles', flat_feet: 'Pé chato', shin: 'Canela', general_plus: 'Pés mais fortes' },
  planTitle: {
    heel_arch: 'Plano para calcanhar e arco',
    achilles: 'Plano para o tendão de Aquiles',
    flat_feet: 'Plano para pé chato',
    shin: 'Plano para a canela',
    general_plus: 'Plano para pés mais fortes',
  },
  planIntro: (minutes, days) => `${minutes} min por dia · ${days} dias por semana`,
  rest: 'Descanso',
  restDay: 'Dia de descanso.',
  reliefHigh: 'Com tanta dor hoje, fique só nesta rotina sentado e não force mais os pés.',
  planHigh: 'Com tanta dor hoje, comece por esta rotina sentado. Peça a semana de novo numa manhã mais tranquila.',
  planCode: 'Código do plano',
  routineLine: (minutes, position) => `uma rotina de ${minutes} min, ${position}`,
  stretchDose: '10 × 10 s em cada pé',
  stretchHow: 'Puxe os dedos para trás, 10 segundos, 10 vezes.',
  stretchWhen: 'antes de levantar',
  side: { both: 'Faça nos dois pés.', left: 'Faça no pé esquerdo.', right: 'Faça no pé direito.' },
  stretchEvidence: 'Um alongamento estudado em pesquisa publicada (DiGiovanni 2003).',
  videoSoon: 'Vídeo em breve.',
  flatTitle: 'Teste de pé chato',
  flatOutcome: {
    yes: 'Aparece um arco, então o pé chato é flexível. Isso é comum, e exercícios para o arco são uma opção.',
    no: 'O seu arco não mudou - vale mostrar a um fisioterapeuta ou podólogo. Os exercícios ainda podem dar força, mas talvez não mudem o formato.',
    not_sure: 'Difícil dizer. Veja o vídeo e tente de novo, em pé, com o peso nos dois pés.',
  },
  notDiagnose: 'Este teste não é um diagnóstico.',
  afterWorkTitle: 'Depois de um dia longo em pé',
  afterWorkLine: (minutes, routine) => `Uma rotina de ${minutes} min para depois do turno, da rotina "${routine}" do app:`,
  shoeTipsLabel: 'Dicas de calçado',
  footwearTitle: 'Dicas de calçado',
  footwearNoBrands: 'Dicas de calçado (sem marcas)',
  shoeTips: [
    { title: 'Calçado com apoio', text: 'Contraforte firme no calcanhar e um pouco de amortecimento embaixo dele. Troque os calçados com a sola gasta.' },
    { title: 'Calcanheiras', text: 'Uma calcanheira macia pode deixar os dias longos em piso duro mais fáceis enquanto o pé fica mais forte.' },
    { title: 'Piso duro', text: 'Enquanto doer, evite andar descalço em piso duro; em casa, use calçado ou chinelo com apoio.' },
    { title: 'Pés largos', text: 'Compre no fim do dia, quando o pé está maior, confira se a parte mais larga tem espaço e procure modelos de forma larga.' },
  ],
  readyTitle: 'Pronto para correr?',
  readyPain: (n) => `Dor nos primeiros passos nas últimas duas semanas: ${n}/10 (3 ou menos para começar).`,
  readyCalf: (n) => `Elevações de panturrilha numa perna só, no lado que dói: ${n} (20 ou mais para começar).`,
  readyCalfAsk: 'Elevações de panturrilha numa perna só, no lado que dói: conte quantas consegue seguidas (20 ou mais para começar).',
  readyYes: 'Você passou no teste. Comece com corrida e caminhada curtas e leves: no máximo 3 por semana, nunca em dias seguidos.',
  readyMornings: 'As suas manhãs estão prontas. Conte as elevações de panturrilha numa perna só antes da primeira corrida.',
  readyNotYet: 'Ainda não. Ganhe força primeiro; o plano abaixo trabalha a panturrilha e o arco.',
  error: 'Não deu certo. Tente de novo.',
  ui: {
    start: 'Começar {seconds} s',
    seconds: '{seconds} s',
    done: 'Pronto',
    code: 'Código {code}',
    copied: 'Copiado',
    copyCode: 'Copiar o código do plano {code}',
    video: 'Vídeo: {name}',
  },
  page: {
    lang: 'pt-BR',
    notFoundTitle: 'Código não reconhecido',
    notFoundBody: 'Confira o código e tente de novo, ou baixe o app e monte o seu plano lá.',
    store: 'Baixe o Walkito na App Store',
    title: 'Seu plano Walkito',
    ready: 'Seu plano está pronto para continuar',
    areaRow: 'Área',
    eachDay: 'Por dia',
    daysRow: 'Dias por semana',
    kitRow: 'Material',
    sideRow: 'Lado',
    minutes: (n) => count('pt', n, { one: '{n} minuto', other: '{n} minutos' }),
    none: 'Nenhum',
    kit: { step: 'Degrau', towel: 'Toalha', band: 'Elástico', ball: 'Bolinha', backpack: 'Mochila' },
    side: { both: 'Os dois pés', left: 'Pé esquerdo', right: 'Pé direito' },
    open: 'Abrir no Walkito',
    copy: 'Copiar código',
    copied: 'Copiado',
    howTo: 'No app, toque em "Recebeu um código do ChatGPT ou do Claude?" na primeira tela e digite este código. O seu plano começa com estas configurações.',
    android: 'Em breve no Google Play para Android.',
  },
};

const fr: Copy = {
  disclaimer: 'Walkito n’est pas un dispositif médical et ne diagnostique, ne traite, ne guérit ni ne prévient aucune affection.',
  evidence: 'Exercices choisis d’après la recherche publiée et les recommandations ; Walkito lui-même n’a pas été testé dans un essai.',
  redFlagTitle: 'Consulte un médecin si',
  seeDoctorFirst: 'Consulte un médecin avant de faire les exercices.',
  redFlags: {
    injury: 'Une blessure ou une chute, et tu ne peux pas poser le pied',
    numbness: 'Engourdissement, fourmillements ou brûlure',
    swelling: 'Gonflement ou chaleur',
    night_pain: 'Douleur la nuit ou au repos',
    arch_flattened: 'Une voûte qui s’est affaissée d’un coup',
    fever: 'De la fièvre',
    diabetes_hot_foot: 'Un pied chaud, rouge ou gonflé avec un diabète',
    achilles_pop: 'Un claquement soudain à l’arrière de la cheville',
    calf_swollen: 'Un mollet gonflé et chaud',
  },
  ctaLine: 'Dans l’app, le plan s’adapte à ton pied chaque jour.',
  ctaBullets: ['Un rappel avant ton premier pas', 'Le plan change selon ton relevé de douleur', 'Un test de progrès tous les 14 jours'],
  ctaButton: 'Continuer ce plan dans Walkito',
  appChanges:
    'Dans l’app, le plan change chaque jour selon ton relevé de douleur, devient plus dur quand c’est facile, te rappelle avant ton premier pas et teste tes progrès tous les 14 jours.',
  area: { heel_arch: 'Talon et voûte', achilles: 'Achille', flat_feet: 'Pieds plats', shin: 'Tibia', general_plus: 'Pieds plus forts' },
  planTitle: {
    heel_arch: 'Plan talon et voûte',
    achilles: 'Plan tendon d’Achille',
    flat_feet: 'Plan pieds plats',
    shin: 'Plan tibia',
    general_plus: 'Plan pieds plus forts',
  },
  planIntro: (minutes, days) => `${minutes} min par jour · ${days} jours par semaine`,
  rest: 'Repos',
  restDay: 'Jour de repos.',
  reliefHigh: 'Avec une douleur aussi forte aujourd’hui, tiens-t’en à cette routine assise et ne charge pas plus tes pieds.',
  planHigh: 'Avec une douleur aussi forte aujourd’hui, commence par cette routine assise. Redemande la semaine un matin plus calme.',
  planCode: 'Code du plan',
  routineLine: (minutes, position) => `une routine de ${minutes} min, ${position}`,
  stretchDose: '10 × 10 s par pied',
  stretchHow: 'Tire les orteils vers toi, 10 secondes, 10 fois.',
  stretchWhen: 'avant de te lever',
  side: { both: 'Fais les deux pieds.', left: 'Fais le pied gauche.', right: 'Fais le pied droit.' },
  stretchEvidence: 'Un étirement étudié dans une recherche publiée (DiGiovanni 2003).',
  videoSoon: 'Vidéo bientôt disponible.',
  flatTitle: 'Test des pieds plats',
  flatOutcome: {
    yes: 'Une voûte apparaît, donc le pied plat est souple. C’est fréquent, et les exercices de voûte sont une option.',
    no: 'Ta voûte n’a pas changé - ça vaut le coup de la montrer à un kiné ou un podologue. Les exercices peuvent quand même renforcer, sans forcément changer la forme.',
    not_sure: 'Difficile à dire. Regarde la vidéo et réessaie, debout, le poids sur les deux pieds.',
  },
  notDiagnose: 'Ce test n’est pas un diagnostic.',
  afterWorkTitle: 'Après une longue journée debout',
  afterWorkLine: (minutes, routine) => `Une routine de ${minutes} min pour après le travail, tirée de la routine « ${routine} » de l’app :`,
  shoeTipsLabel: 'Conseils chaussures',
  footwearTitle: 'Conseils chaussures',
  footwearNoBrands: 'Conseils chaussures (sans marques)',
  shoeTips: [
    { title: 'Chaussures qui tiennent', text: 'Un contrefort ferme au talon et un peu d’amorti dessous. Change les chaussures dont la semelle est usée à plat.' },
    { title: 'Talonnettes', text: 'Une talonnette souple peut rendre les longues journées sur sol dur plus faciles pendant que le pied se renforce.' },
    { title: 'Sols durs', text: 'Tant que ça fait mal, évite d’être pieds nus sur un sol dur ; à la maison, porte des chaussures ou des chaussons qui tiennent le pied.' },
    { title: 'Pieds larges', text: 'Achète en fin de journée, quand le pied est le plus grand, vérifie qu’il y a de la place au plus large et cherche des modèles en largeur large.' },
  ],
  readyTitle: 'Prêt à courir ?',
  readyPain: (n) => `Douleur aux premiers pas sur les deux dernières semaines : ${n}/10 (3 ou moins pour commencer).`,
  readyCalf: (n) => `Montées sur pointe sur une jambe, côté douloureux : ${n} (20 ou plus pour commencer).`,
  readyCalfAsk: 'Montées sur pointe sur une jambe, côté douloureux : compte combien tu en fais d’affilée (20 ou plus pour commencer).',
  readyYes: 'Tu passes le test. Commence par des sorties courtes et faciles en alternant course et marche : 3 par semaine au plus, jamais deux jours de suite.',
  readyMornings: 'Tes matins sont prêts. Compte tes montées sur pointe sur une jambe avant la première sortie.',
  readyNotYet: 'Pas encore. Gagne d’abord en force ; le plan ci-dessous travaille le mollet et la voûte.',
  error: 'Ça n’a pas marché. Réessaie.',
  ui: {
    start: 'Démarrer {seconds} s',
    seconds: '{seconds} s',
    done: 'Terminé',
    code: 'Code {code}',
    copied: 'Copié',
    copyCode: 'Copier le code du plan {code}',
    video: 'Vidéo : {name}',
  },
  page: {
    lang: 'fr',
    notFoundTitle: 'Code non reconnu',
    notFoundBody: 'Vérifie le code et réessaie, ou télécharge l’app et crée ton plan directement.',
    store: 'Télécharger Walkito sur l’App Store',
    title: 'Ton plan Walkito',
    ready: 'Ton plan est prêt à continuer',
    areaRow: 'Zone',
    eachDay: 'Par jour',
    daysRow: 'Jours par semaine',
    kitRow: 'Matériel',
    sideRow: 'Côté',
    minutes: (n) => count('fr', n, { one: '{n} minute', other: '{n} minutes' }),
    none: 'Aucun',
    kit: { step: 'Marche', towel: 'Serviette', band: 'Élastique', ball: 'Balle', backpack: 'Sac à dos' },
    side: { both: 'Les deux pieds', left: 'Pied gauche', right: 'Pied droit' },
    open: 'Ouvrir dans Walkito',
    copy: 'Copier le code',
    copied: 'Copié',
    howTo: 'Dans l’app, touche « Tu as un code de ChatGPT ou Claude ? » sur le premier écran et saisis ce code. Ton plan démarre avec ces réglages.',
    android: 'Bientôt sur Google Play pour Android.',
  },
};

const it: Copy = {
  disclaimer: 'Walkito non è un dispositivo medico e non diagnostica, tratta, cura né previene alcuna condizione medica.',
  evidence: 'Esercizi scelti dalla ricerca pubblicata e dalle linee guida; Walkito in sé non è stato testato in uno studio clinico.',
  redFlagTitle: 'Vai dal medico se hai',
  seeDoctorFirst: 'Fatti vedere da un medico prima di fare gli esercizi.',
  redFlags: {
    injury: 'Un infortunio o una caduta, e non riesci ad appoggiare il piede',
    numbness: 'Intorpidimento, formicolio o bruciore',
    swelling: 'Gonfiore o calore',
    night_pain: 'Dolore di notte o a riposo',
    arch_flattened: 'Un arco che si è abbassato all’improvviso',
    fever: 'Febbre',
    diabetes_hot_foot: 'Un piede caldo, rosso o gonfio con il diabete',
    achilles_pop: 'Uno schiocco improvviso dietro la caviglia',
    calf_swollen: 'Un polpaccio gonfio e caldo',
  },
  ctaLine: 'Nell’app il piano si adatta al tuo piede ogni giorno.',
  ctaBullets: ['Promemoria prima del primo passo', 'Il piano cambia con il tuo check del dolore', 'Test dei progressi ogni 14 giorni'],
  ctaButton: 'Continua questo piano in Walkito',
  appChanges:
    'Nell’app il piano cambia ogni giorno con il tuo check del dolore, diventa più impegnativo quando è facile, ti avvisa prima del primo passo e testa i tuoi progressi ogni 14 giorni.',
  area: { heel_arch: 'Tallone e arco', achilles: 'Achille', flat_feet: 'Piede piatto', shin: 'Tibia', general_plus: 'Piedi più forti' },
  planTitle: {
    heel_arch: 'Piano per tallone e arco',
    achilles: 'Piano per il tendine d’Achille',
    flat_feet: 'Piano per il piede piatto',
    shin: 'Piano per la tibia',
    general_plus: 'Piano per piedi più forti',
  },
  planIntro: (minutes, days) => `${minutes} min al giorno · ${days} giorni a settimana`,
  rest: 'Riposo',
  restDay: 'Giorno di riposo.',
  reliefHigh: 'Con un dolore così forte oggi, resta su questa routine da seduto e non caricare altro sui piedi.',
  planHigh: 'Con un dolore così forte oggi, inizia da questa routine da seduto. Richiedi la settimana in una mattina più tranquilla.',
  planCode: 'Codice del piano',
  routineLine: (minutes, position) => `una routine di ${minutes} min, ${position}`,
  stretchDose: '10 × 10 s per piede',
  stretchHow: 'Tira le dita verso di te, 10 secondi, 10 volte.',
  stretchWhen: 'prima di alzarti',
  side: { both: 'Fallo su entrambi i piedi.', left: 'Fallo sul piede sinistro.', right: 'Fallo sul piede destro.' },
  stretchEvidence: 'Un allungamento studiato in una ricerca pubblicata (DiGiovanni 2003).',
  videoSoon: 'Video in arrivo.',
  flatTitle: 'Test del piede piatto',
  flatOutcome: {
    yes: 'Compare un arco, quindi il piede piatto è flessibile. È frequente, e gli esercizi per l’arco sono un’opzione.',
    no: 'Il tuo arco non è cambiato - vale la pena farlo vedere a un fisioterapista o a un podologo. Gli esercizi possono comunque dare forza, ma forse non cambiano la forma.',
    not_sure: 'Difficile dirlo. Guarda il video e riprova, in piedi, con il peso su entrambi i piedi.',
  },
  notDiagnose: 'Questo test non è una diagnosi.',
  afterWorkTitle: 'Dopo una lunga giornata in piedi',
  afterWorkLine: (minutes, routine) => `Una routine di ${minutes} min per dopo il turno, dalla routine «${routine}» dell’app:`,
  shoeTipsLabel: 'Consigli sulle scarpe',
  footwearTitle: 'Consigli sulle scarpe',
  footwearNoBrands: 'Consigli sulle scarpe (senza marchi)',
  shoeTips: [
    { title: 'Scarpe che sostengono', text: 'Un contrafforte rigido sul tallone e un po’ di ammortizzazione sotto. Cambia le scarpe con la suola consumata.' },
    { title: 'Talloniere', text: 'Una talloniera morbida può rendere più leggere le lunghe giornate su pavimenti duri mentre il piede si rinforza.' },
    { title: 'Pavimenti duri', text: 'Finché fa male, evita di camminare scalzo su pavimenti duri; in casa porta scarpe o pantofole che sostengono.' },
    { title: 'Piedi larghi', text: 'Compra nel tardo pomeriggio, quando il piede è più grande, controlla che ci sia spazio nel punto più largo e cerca modelli a pianta larga.' },
  ],
  readyTitle: 'Pronto a correre?',
  readyPain: (n) => `Dolore ai primi passi nelle ultime due settimane: ${n}/10 (3 o meno per iniziare).`,
  readyCalf: (n) => `Sollevamenti sulle punte su una gamba, lato che fa male: ${n} (20 o più per iniziare).`,
  readyCalfAsk: 'Sollevamenti sulle punte su una gamba, lato che fa male: conta quanti ne fai di fila (20 o più per iniziare).',
  readyYes: 'Superi il test. Inizia con uscite brevi e facili di corsa e camminata: al massimo 3 a settimana, mai in giorni consecutivi.',
  readyMornings: 'Le tue mattine sono pronte. Conta i sollevamenti sulle punte su una gamba prima della prima uscita.',
  readyNotYet: 'Non ancora. Prima costruisci forza; il piano qui sotto lavora su polpaccio e arco.',
  error: 'Non ha funzionato. Riprova.',
  ui: {
    start: 'Inizia {seconds} s',
    seconds: '{seconds} s',
    done: 'Fatto',
    code: 'Codice {code}',
    copied: 'Copiato',
    copyCode: 'Copia il codice del piano {code}',
    video: 'Video: {name}',
  },
  page: {
    lang: 'it',
    notFoundTitle: 'Codice non riconosciuto',
    notFoundBody: 'Controlla il codice e riprova, oppure scarica l’app e imposta lì il tuo piano.',
    store: 'Scarica Walkito dall’App Store',
    title: 'Il tuo piano Walkito',
    ready: 'Il tuo piano è pronto per continuare',
    areaRow: 'Zona',
    eachDay: 'Ogni giorno',
    daysRow: 'Giorni a settimana',
    kitRow: 'Attrezzatura',
    sideRow: 'Lato',
    minutes: (n) => count('it', n, { one: '{n} minuto', other: '{n} minuti' }),
    none: 'Nessuna',
    kit: { step: 'Gradino', towel: 'Asciugamano', band: 'Elastico', ball: 'Pallina', backpack: 'Zaino' },
    side: { both: 'Entrambi i piedi', left: 'Piede sinistro', right: 'Piede destro' },
    open: 'Apri in Walkito',
    copy: 'Copia il codice',
    copied: 'Copiato',
    howTo: 'Nell’app, tocca «Hai un codice da ChatGPT o Claude?» nella prima schermata e inserisci questo codice. Il tuo piano parte con queste impostazioni.',
    android: 'Presto su Google Play per Android.',
  },
};

const de: Copy = {
  disclaimer: 'Walkito ist kein Medizinprodukt und dient nicht der Diagnose, Behandlung, Heilung oder Vorbeugung von Erkrankungen.',
  evidence: 'Übungen ausgewählt nach veröffentlichter Forschung und Leitlinien; Walkito selbst wurde nicht in einer Studie getestet.',
  redFlagTitle: 'Geh zum Arzt bei diesen Zeichen',
  seeDoctorFirst: 'Bitte lass dich ärztlich untersuchen, bevor du die Übungen machst.',
  redFlags: {
    injury: 'Verletzung oder Sturz, und du kannst den Fuß nicht belasten',
    numbness: 'Taubheit, Kribbeln oder Brennen',
    swelling: 'Schwellung oder Wärme',
    night_pain: 'Schmerzen nachts oder in Ruhe',
    arch_flattened: 'Ein Gewölbe ist plötzlich abgesunken',
    fever: 'Fieber',
    diabetes_hot_foot: 'Ein heißer, roter oder geschwollener Fuß bei Diabetes',
    achilles_pop: 'Ein plötzlicher Knall hinten am Knöchel',
    calf_swollen: 'Eine geschwollene, warme Wade',
  },
  ctaLine: 'In der App passt sich der Plan jeden Tag an deinen Fuß an.',
  ctaBullets: ['Erinnerung vor deinem ersten Schritt', 'Der Plan ändert sich mit deinem Schmerz-Check-in', 'Fortschrittstest alle 14 Tage'],
  ctaButton: 'Diesen Plan in Walkito fortsetzen',
  appChanges:
    'In der App ändert sich der Plan jeden Tag mit deinem Schmerz-Check-in, wird schwerer, wenn es leicht fällt, erinnert dich vor deinem ersten Schritt und testet alle 14 Tage deinen Fortschritt.',
  area: { heel_arch: 'Ferse und Gewölbe', achilles: 'Achillessehne', flat_feet: 'Plattfüße', shin: 'Schienbein', general_plus: 'Stärkere Füße' },
  planTitle: {
    heel_arch: 'Plan für Ferse und Gewölbe',
    achilles: 'Plan für die Achillessehne',
    flat_feet: 'Plan bei Plattfüßen',
    shin: 'Plan fürs Schienbein',
    general_plus: 'Plan für stärkere Füße',
  },
  planIntro: (minutes, days) => `${minutes} Min. am Tag · ${days} Tage pro Woche`,
  rest: 'Pause',
  restDay: 'Ruhetag.',
  reliefHigh: 'Bei so starken Schmerzen heute bleib bei dieser Routine im Sitzen und belaste die Füße sonst nicht.',
  planHigh: 'Bei so starken Schmerzen heute fang mit dieser Routine im Sitzen an. Frag an einem ruhigeren Morgen noch mal nach der Woche.',
  planCode: 'Plan-Code',
  routineLine: (minutes, position) => `eine Routine von ${minutes} Min., ${position}`,
  stretchDose: '10 × 10 s pro Fuß',
  stretchHow: 'Zieh die Zehen zu dir, 10 Sekunden, 10 Mal.',
  stretchWhen: 'vor dem Aufstehen',
  side: { both: 'Mach beide Füße.', left: 'Mach den linken Fuß.', right: 'Mach den rechten Fuß.' },
  stretchEvidence: 'Eine Dehnung, die in veröffentlichter Forschung untersucht wurde (DiGiovanni 2003).',
  videoSoon: 'Video folgt bald.',
  flatTitle: 'Plattfuß-Check',
  flatOutcome: {
    yes: 'Ein Gewölbe erscheint, der Plattfuß ist also flexibel. Das ist häufig, und Übungen fürs Gewölbe sind eine Option.',
    no: 'Dein Gewölbe hat sich nicht verändert - zeig es am besten einer Physiotherapeutin oder einem Podologen. Übungen können trotzdem kräftigen, die Form aber vielleicht nicht ändern.',
    not_sure: 'Schwer zu sagen. Schau dir das Video an und versuch es noch mal, im Stehen, mit Gewicht auf beiden Füßen.',
  },
  notDiagnose: 'Dieser Check ist keine Diagnose.',
  afterWorkTitle: 'Nach einem langen Tag auf den Beinen',
  afterWorkLine: (minutes, routine) => `Eine Routine von ${minutes} Min. für nach der Schicht, aus der Routine „${routine}“ der App:`,
  shoeTipsLabel: 'Schuhtipps',
  footwearTitle: 'Schuhtipps',
  footwearNoBrands: 'Schuhtipps (ohne Marken)',
  shoeTips: [
    { title: 'Schuhe mit Halt', text: 'Eine feste Fersenkappe und etwas Dämpfung unter der Ferse. Tausch Schuhe aus, deren Sohle abgelaufen ist.' },
    { title: 'Fersenkissen', text: 'Ein weiches Fersenkissen kann lange Tage auf hartem Boden leichter machen, während der Fuß stärker wird.' },
    { title: 'Harte Böden', text: 'Solange es weh tut, lauf nicht barfuß auf hartem Boden; trag zu Hause Schuhe oder Hausschuhe mit Halt.' },
    { title: 'Breite Füße', text: 'Kauf am späten Nachmittag, wenn der Fuß am größten ist, prüf, ob an der breitesten Stelle Platz ist, und such nach Modellen in weiter Passform.' },
  ],
  readyTitle: 'Bereit zum Laufen?',
  readyPain: (n) => `Anlaufschmerz in den letzten zwei Wochen: ${n}/10 (3 oder weniger zum Start).`,
  readyCalf: (n) => `Einbeinige Fersenheber auf der schmerzenden Seite: ${n} (20 oder mehr zum Start).`,
  readyCalfAsk: 'Einbeinige Fersenheber auf der schmerzenden Seite: zähl, wie viele du am Stück schaffst (20 oder mehr zum Start).',
  readyYes: 'Du bestehst den Check. Fang mit kurzen, lockeren Lauf-Geh-Einheiten an: höchstens 3 pro Woche, nie an aufeinanderfolgenden Tagen.',
  readyMornings: 'Deine Morgen sehen gut aus. Zähl vor dem ersten Lauf deine einbeinigen Fersenheber.',
  readyNotYet: 'Noch nicht. Bau zuerst Kraft auf; der Plan unten arbeitet an Wade und Gewölbe.',
  error: 'Das hat nicht geklappt. Versuch es noch mal.',
  ui: {
    start: 'Start {seconds} s',
    seconds: '{seconds} s',
    done: 'Fertig',
    code: 'Code {code}',
    copied: 'Kopiert',
    copyCode: 'Plan-Code {code} kopieren',
    video: 'Video: {name}',
  },
  page: {
    lang: 'de',
    notFoundTitle: 'Code nicht erkannt',
    notFoundBody: 'Prüf den Code und versuch es noch mal, oder lad die App und richte deinen Plan dort ein.',
    store: 'Walkito im App Store laden',
    title: 'Dein Walkito-Plan',
    ready: 'Dein Plan ist bereit zum Weitermachen',
    areaRow: 'Bereich',
    eachDay: 'Pro Tag',
    daysRow: 'Tage pro Woche',
    kitRow: 'Ausrüstung',
    sideRow: 'Seite',
    minutes: (n) => count('de', n, { one: '{n} Minute', other: '{n} Minuten' }),
    none: 'Keine',
    kit: { step: 'Stufe', towel: 'Handtuch', band: 'Band', ball: 'Ball', backpack: 'Rucksack' },
    side: { both: 'Beide Füße', left: 'Linker Fuß', right: 'Rechter Fuß' },
    open: 'In Walkito öffnen',
    copy: 'Code kopieren',
    copied: 'Kopiert',
    howTo: 'Tipp in der App auf dem ersten Bildschirm auf „Hast du einen Code von ChatGPT oder Claude?“ und gib diesen Code ein. Dein Plan startet mit diesen Einstellungen.',
    android: 'Bald auch bei Google Play für Android.',
  },
};

export const COPY: Record<Lang, Copy> = { en, ru, es, pt, fr, it, de };

/** Short and one-letter weekday names, Monday first, in a language. */
export function weekdays(lang: Lang): { short: string; initial: string }[] {
  // 2024-01-01 was a Monday.
  return Array.from({ length: 7 }, (_, i) => {
    const date = new Date(Date.UTC(2024, 0, 1 + i, 12));
    const cap = (s: string) => s.charAt(0).toLocaleUpperCase(lang) + s.slice(1);
    return {
      short: cap(new Intl.DateTimeFormat(lang, { weekday: 'short', timeZone: 'UTC' }).format(date).replace(/\.$/, '')),
      initial: cap(new Intl.DateTimeFormat(lang, { weekday: 'narrow', timeZone: 'UTC' }).format(date)),
    };
  });
}

/** The language for a call: what the model passed, else the host's locale
 * (`openai/locale` on ChatGPT), else English. "pt-BR", "ru_RU" and the like
 * resolve to their language. */
export function langOf(...candidates: unknown[]): Lang {
  for (const c of candidates) {
    if (typeof c !== 'string') continue;
    const base = c.trim().toLowerCase().split(/[-_]/)[0];
    if ((['en', 'ru', 'es', 'pt', 'fr', 'it', 'de'] as string[]).includes(base)) return base as Lang;
  }
  return 'en';
}
