import { CITE } from '@/lib/citations';
import type { Guide } from '../types';

export const FOOT_STRENGTHENING_IT: Guide = {
  lang: 'it',
  page: 'footStrengthening',
  mainSource: CITE.taddeiRRI,
  published: '2026-10-09',
  updated: '2026-10-09',
  title: 'Esercizi per rinforzare i piedi: come progredire',
  description:
    'Esercizi per rinforzare i piedi, per i muscoli piccoli e grandi, da seduto a una gamba, con dosi di partenza e cosa dicono gli studi sugli infortuni.',
  h1: 'Esercizi per rinforzare i piedi: cosa fare e come progredire',
  lede:
    'Gli esercizi per rinforzare i piedi allenano i piccoli muscoli dentro il piede e quelli più grandi che scendono dal polpaccio. Comincia da seduto con l’esercizio del piede corto, l’apertura delle dita e il sollevamento dell’alluce, poi passa in piedi, poi su una gamba. Negli studi, i muscoli del piede sono diventati più grandi e più forti in circa due mesi.',
  intro: [
    'Questa pagina è la guida generale per tutto il piede. Per piede piatto, dita o scarpe barefoot, le pagine più specifiche sono linkate più sotto.',
  ],
  takeaways: [
    'In uno studio del 2020 su 118\u00A0runner amatoriali, il gruppo senza allenamento del piede aveva una probabilità 2,42\u00A0volte più alta di un infortunio da corsa nei 12\u00A0mesi rispetto al gruppo che faceva un programma per il «core del piede» (Taddei e colleghi). È un solo studio.',
    'In uno studio del 2019 su 57\u00A0runner, circa due mesi di esercizi progressivi per il piede, fatti almeno cinque volte a settimana, hanno reso più grande e più forte ogni muscolo del piede misurato, mentre il gruppo di controllo non è cambiato (Ridge e colleghi).',
    'Una revisione del 2025 di 28\u00A0studi con 1.399\u00A0persone ha sostenuto gli esercizi per il piede per aumentarne la forza, ma ha valutato la certezza delle prove da bassa a molto bassa (Peters-Dickie e colleghi).',
    'Negli anziani tra 60 e 90\u00A0anni, un programma supervisionato con carichi via via più pesanti ha aumentato la forza delle dita fino al 36% in tre mesi, mentre un programma a casa no (Mickle e colleghi, 2016).',
    'Per la fascite plantare, aggiungere il rinforzo del piede allo stretching non ha fatto meglio del solo stretching in uno studio su 83\u00A0persone (Kamonseki e colleghi, 2016).',
  ],
  toc: true,
  sections: [
    {
      h2: 'Quali sono i muscoli del piede e perché rinforzarli?',
      paragraphs: [
        'Il piede ha due gruppi di muscoli:',
        {
          list: [
            'I muscoli **intrinseci** (i piccoli muscoli che iniziano e finiscono dentro il piede) stanno sotto l’arco e tra le ossa. Sostengono l’arco, allargano le dita e fanno le minime correzioni che ti tengono in equilibrio.',
            'I muscoli **estrinseci** (i muscoli più grandi che partono dalla gamba e arrivano al piede con lunghi tendini) comprendono il polpaccio, che solleva il tallone, e i muscoli che ruotano e sollevano il piede.',
          ],
        },
        'Un articolo del 2015 di McKeon e colleghi ha chiamato i muscoli intrinseci il «core del piede». L’idea è la stessa dei muscoli profondi del tronco: piccoli stabilizzatori che fanno lavorare bene i muscoli più grandi.',
        'Secondo loro, nella gestione dei problemi al piede si sostiene il piede dall’esterno più spesso di quanto si alleni questi muscoli, quindi molte persone non li allenano mai. È un modello, non una causa di dolore dimostrata, ma spiega perché i programmi per il piede allenano prima i piccoli muscoli e poi aggiungono polpaccio ed equilibrio.',
        'Un buon lavoro di forza per il piede copre entrambi i gruppi:',
        {
          list: [
            'L’esercizio del piede corto, l’apertura delle dita e il sollevamento dell’alluce allenano i muscoli intrinseci.',
            'I sollevamenti sulle punte allenano il polpaccio.',
            'Stare su una gamba li fa lavorare insieme.',
          ],
        },
      ],
      cites: [CITE.mcKeon],
    },
    {
      h2: 'Da quali esercizi per rinforzare i piedi cominciare?',
      keyFact: 'Una revisione del 2023 di quattro studi ha trovato che la maggior parte dei programmi per il piede usava tenute di 5\u00A0secondi e passava da seduti a in piedi (de Souza e colleghi).',
      paragraphs: [
        'Comincia con gli esercizi che isolano i piccoli muscoli del piede, da seduto, poi aggiungi il lavoro in piedi e di equilibrio quando diventano facili. Una revisione del 2023 di de Souza e colleghi ha esaminato quattro studi randomizzati sul rinforzo dei muscoli intrinseci del piede. La maggior parte usava l’esercizio del piede corto e la raccolta dell’asciugamano, con contrazioni tenute per circa 5\u00A0secondi e una progressione da seduti a in piedi.',
        'Le dosi qui sotto sono dosi di partenza. Falli a piedi nudi. Se un esercizio porta il dolore a **6/10 o più**, fermati per quel giorno. Ogni esercizio ha la sua pagina con più dettagli, collegata dalla [libreria degli esercizi](/exercises/) (in inglese).',
      ],
      exercises: [
        {
          name: 'Piede corto, da seduto',
          dose: '3\u00A0serie da 8, tenuta di 5\u00A0secondi ciascuna',
          often: 'Quasi tutte le sessioni',
          feel: 'Una contrazione sotto l’arco, con le dita ancora rilassate',
          stop: 'Un crampo che non passa, o dolore a 6/10',
          how: 'Siediti con il piede appoggiato. Senza piegare le dita, avvicina l’avampiede al tallone in modo che l’arco si alzi un po’. Tieni, poi rilassa. Il movimento è piccolo. Se le dita fanno presa sul pavimento, molla un po’ e riprova. La tecnica completa è nella pagina sull’[esercizio del piede corto](/it/esercizi/piede-corto/).',
          media: 'short_foot_seated',
          caption: 'Piede corto, da seduto: avvicina l’avampiede al tallone, dita appoggiate',
          alt: 'Una figura seduta che alza l’arco di un piede mentre le dita restano appoggiate a terra',
          evidence: { level: 'moderate', why: 'Usato nella maggior parte degli studi della revisione del 2023 sul rinforzo del piede (de Souza), con prove di bassa qualità per i cambiamenti di arco ed equilibrio. Mai testato da solo per infortuni o dolore.' },
        },
        {
          name: 'Apertura delle dita',
          dose: '3\u00A0serie da 10',
          often: 'Quasi tutte le sessioni',
          feel: 'Lavoro lungo i lati del piede',
          stop: 'Un crampo che non passa',
          how: 'Con il piede appoggiato, allarga tutte e cinque le dita più che puoi, tieni un attimo, poi rilassa. Tieni il tallone e l’avampiede a terra.',
          media: 'toe_spread',
          caption: 'Apertura delle dita: allarga bene le dita, tallone e avampiede giù',
          alt: 'Un piede nudo appoggiato a terra con le dita allargate',
          evidence: { level: 'early', why: 'Uno studio con risonanza magnetica mostra che attiva i piccoli muscoli del piede (Gooding 2016). Non testato da solo in uno studio sui risultati.' },
        },
        {
          name: 'Sollevamento dell’alluce',
          dose: '3\u00A0serie da 8, tenuta di 5\u00A0secondi ciascuna',
          often: 'Quasi tutte le sessioni',
          feel: 'Lavoro sul dorso del piede e sotto l’arco',
          stop: 'Dolore all’articolazione dell’alluce',
          how: 'Tieni le quattro dita piccole a terra e solleva solo l’alluce. Poi prova il contrario: alluce giù, dita piccole su. All’inizio è difficile. Basta un movimento piccolo.',
          media: 'big_toe_lift',
          caption: 'Sollevamento dell’alluce: si alza solo l’alluce',
          alt: 'Un piede nudo con l’alluce sollevato e le altre dita appoggiate a terra',
          evidence: { level: 'early', why: 'Uno studio con risonanza magnetica mostra che attiva i piccoli muscoli del piede (Gooding 2016). Usato nei programmi per il piede ma non testato da solo.' },
        },
        {
          name: 'Raccolta dell’asciugamano',
          dose: '3\u00A0serie da 8, tenuta di 5\u00A0secondi ciascuna',
          often: 'Quasi tutte le sessioni',
          feel: 'Lavoro sotto le dita e l’arco',
          stop: 'Un crampo che non passa',
          how: 'Siediti con un asciugamano sotto il piede. Piega le dita per tirare l’asciugamano verso di te, tieni, poi lascia andare e stendilo. Allena i muscoli lunghi delle dita oltre a quelli piccoli.',
          media: 'towel_scrunch',
          caption: 'Raccolta dell’asciugamano: piega le dita per raccogliere l’asciugamano',
          alt: 'Un piede nudo che piega le dita per tirare un asciugamano sul pavimento',
          evidence: { level: 'early', why: 'Usata nella maggior parte degli studi della revisione del 2023, di solito insieme all’esercizio del piede corto. Non testata da sola per dolore o infortuni.' },
        },
        {
          name: 'Sollevamenti sulle punte su due piedi',
          dose: '3\u00A0serie da 10',
          often: 'Quasi tutte le sessioni',
          feel: 'Lavoro nei polpacci e sotto l’avampiede',
          stop: 'Dolore al tallone o all’Achille a 6/10',
          how: 'Tieniti a un muro. Sali sull’avampiede di entrambi i piedi in circa 3\u00A0secondi, poi scendi in 3\u00A0secondi. Cerca di tenere il peso sul lato dell’alluce, senza ruotare verso l’esterno. Altro nella pagina sui [sollevamenti sulle punte](/it/esercizi/sollevamenti-sulle-punte/).',
          media: 'heel_raise_double',
          caption: 'Sollevamenti sulle punte su due piedi: su piano, giù piano',
          alt: 'Una figura che si tiene a un muro e sale sull’avampiede di entrambi i piedi',
          evidence: { level: 'moderate', why: 'I sollevamenti sulle punte hanno il supporto di uno studio per la fascite plantare (Rathleff 2015). Qui allenano il polpaccio, il principale muscolo estrinseco del piede.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.gooding, CITE.rathleff],
    },
    {
      h2: 'Come passare da seduto a in piedi a una gamba?',
      paragraphs: [
        'Fai progredire gli esercizi per rinforzare i piedi mettendo più peso del corpo sul piede, un gradino alla volta. Il lavoro da seduto insegna il movimento. In piedi su due piedi aggiungi metà del peso del corpo. Su un piede lo aggiungi tutto, più l’equilibrio. Sali solo quando il gradino attuale ti sembra facile e controllato.',
        'Walkito usa gli stessi tre gradini per l’esercizio del piede corto: da seduto, poi in piedi su due piedi, poi su una gamba. Quando il focus del tuo piano è l’arco, il piano della settimana successiva ti fa salire di un gradino se hai valutato facili le ultime due sessioni con quell’esercizio e il dolore del mattino non è aumentato. Una sessione valutata difficile, o il dolore del mattino salito di 2\u00A0punti, ti fa tornare indietro di un gradino. I due gradini successivi sono qui sotto.',
      ],
      bullets: [
        '**Gradino 1, da seduto.** Piede corto, apertura delle dita, sollevamento dell’alluce e raccolta dell’asciugamano, tutti da seduto.',
        '**Gradino 2, in piedi su due piedi.** La tenuta del piede corto in piedi e i sollevamenti sulle punte su due piedi.',
        '**Gradino 3, su una gamba.** La tenuta del piede corto su una gamba, poi l’equilibrio su una gamba tenendo l’arco alzato.',
        '**Più avanti.** I sollevamenti sulle punte su una gamba e, per chi corre, piccoli saltelli. Sono carichi più grandi. Aggiungili solo quando il gradino 3 è facile.',
      ],
      exercises: [
        {
          name: 'Piede corto, in piedi',
          dose: '3\u00A0serie da 8, tenuta di 5\u00A0secondi ciascuna',
          often: 'Quando la versione da seduto è facile',
          feel: 'L’arco che si alza sotto il peso del corpo',
          stop: 'Dolore a 6/10, o le dita continuano a fare presa',
          how: 'Stai in piedi con il peso distribuito su entrambi i piedi. Alza gli archi come da seduto, dita rilassate, ginocchia morbide. Tieni, poi rilassa.',
          media: 'short_foot_double',
          caption: 'Piede corto, in piedi: alza entrambi gli archi senza piegare le dita',
          alt: 'Una figura in piedi che alza l’arco di entrambi i piedi',
          evidence: { level: 'moderate', why: 'La progressione da seduti a in piedi era usata nella maggior parte degli studi della revisione del 2023. Non testata da sola per dolore o infortuni.' },
        },
        {
          name: 'Piede corto, su una gamba',
          dose: '3\u00A0serie da 10, tenuta di 5\u00A0secondi ciascuna',
          often: 'Quando la versione su due piedi è facile',
          feel: 'Tutto il piede e la caviglia che lavorano per restare stabili',
          stop: 'Dolore a 6/10, o non riesci a tenere l’arco alzato',
          how: 'Stai su un piede vicino a un muro. Alza l’arco e tienilo mentre stai in equilibrio. Tocca il muro se ti serve.',
          media: 'short_foot_single',
          caption: 'Piede corto, su una gamba: tieni l’arco mentre stai in equilibrio',
          alt: 'Una figura in piedi su un piede con l’arco alzato, una mano vicino al muro',
          evidence: { level: 'early', why: 'Usato come ultimo gradino nei programmi per il core del piede. Pochi studi su questa variante precisa.' },
        },
        {
          name: 'Equilibrio su una gamba',
          dose: '3\u00A0tenute da 20\u00A0secondi, ogni gamba',
          often: 'Giorni di equilibrio',
          feel: 'Piccole correzioni continue nel piede',
          stop: 'Dolore a 6/10, o capogiri',
          how: 'Stai su un piede e guarda un punto fisso davanti a te. Lascia che il piede faccia piccole oscillazioni. Il lavoro è quello. Stai vicino a un muro o a un piano di lavoro. Altro nella pagina sull’[equilibrio su una gamba](/it/esercizi/equilibrio-su-una-gamba/).',
          media: 'single_leg_hold',
          caption: 'Equilibrio su una gamba: lascia che sia il piede a fare le correzioni',
          alt: 'Una figura in equilibrio su una gamba accanto a un muro',
          evidence: { level: 'moderate', why: 'L’allenamento dell’equilibrio ha ridotto le distorsioni della caviglia in una meta-analisi (Bellows 2018). Per la forza del piede in sé non è stato testato da solo.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.bellows],
    },
    {
      h2: 'Gli esercizi per rinforzare i piedi prevengono gli infortuni da corsa?',
      keyFact: 'In uno studio del 2020 su 118\u00A0runner, chi non faceva l’allenamento del core del piede aveva una probabilità 2,42\u00A0volte più alta di infortunarsi nei 12\u00A0mesi (Taddei e colleghi).',
      paragraphs: [
        'Gli esercizi per rinforzare i piedi **hanno ridotto gli infortuni da corsa in un buono studio, ma uno solo.** Nel 2020, Taddei e colleghi hanno diviso a caso 118\u00A0runner amatoriali di lunga distanza tra un gruppo core del piede (57\u00A0runner) e un gruppo di controllo (61\u00A0runner). Il gruppo core del piede ha seguito un corso supervisionato di circa due mesi sui muscoli di piede e caviglia, poi ha continuato ad allenarsi con una supervisione a distanza.',
        'Nei 12\u00A0mesi, il gruppo di controllo aveva una probabilità 2,42\u00A0volte più alta di un infortunio da corsa. Gli autori hanno visto comparire l’effetto dopo circa quattro-otto mesi di allenamento.',
        'Uno studio precedente e più piccolo dello stesso gruppo, con 28\u00A0runner, ha trovato che circa due mesi di allenamento del piede aumentavano le dimensioni di ogni muscolo del piede misurato, rispetto al gruppo di controllo. I runner spingevano anche da terra con più forza.',
        'Entrambi gli studi vengono da un solo gruppo di ricerca in Brasile, su runner amatoriali che all’inizio non erano infortunati. Non sappiamo ancora se il programma aiuti chi comincia o chi ha già dolore. Se corri e hai già dolore al tallone, parti da [dolore al tallone nei runner](/heel-pain-runners/) (in inglese).',
      ],
      sourceNote: 'Taddei 2020 (Am J Sports Med): il gruppo di controllo aveva una probabilità 2,42\u00A0volte più alta di infortunarsi (IC 95% da 1,98 a 3,62), p = 0,035, studio randomizzato in singolo cieco, follow-up a 12\u00A0mesi. Taddei 2020 (Phys Ther Sport): studio randomizzato proof-of-concept in singolo cieco, 28\u00A0runner, volume muscolare con risonanza magnetica.',
      cites: [CITE.taddeiRRI, CITE.taddeiMuscle],
    },
    {
      h2: 'Quanto tempo ci vuole per rinforzare i piedi?',
      keyFact: 'In uno studio del 2019 su 57\u00A0runner, i muscoli del piede sono cresciuti e diventati più forti in circa due mesi, con alcuni muscoli più grandi già dopo un mese (Ridge e colleghi).',
      paragraphs: [
        'Negli studi, i muscoli del piede sono diventati misurabilmente più forti in **circa due mesi di allenamento regolare**. Nel 2019, Ridge e colleghi hanno assegnato a caso 57\u00A0runner a:',
        {
          list: [
            'Esercizi di rinforzo del piede.',
            'Camminare con scarpe minimaliste.',
            'Nessun cambiamento.',
          ],
        },
        'Il gruppo esercizi faceva esercizi progressivi contro resistenza almeno cinque volte a settimana. Dopo circa due mesi, ogni muscolo del piede misurato era più grande e più forte in entrambi i gruppi attivi, senza cambiamenti nel gruppo di controllo. Alcuni muscoli erano già più grandi al controllo dopo un mese.',
        'La forma dell’arco cambia più lentamente, e di meno. Una revisione del 2023 di quattro studi ha trovato che il rinforzo dei muscoli intrinseci del piede non cambiava quanto si muove l’arco dopo un mese, ma lo cambiava dopo due mesi, con prove di bassa qualità.',
        'In un piccolo studio di Mulligan e Cook con 21\u00A0persone e senza gruppo di controllo, il navicular drop (quanto scende l’arco interno quando stai in piedi) è diminuito in media di 1,8\u00A0mm dopo un mese di allenamento del piede corto. È un cambiamento reale ma piccolo.',
      ],
      cites: [CITE.ridgeMinimalist, CITE.deSouzaIFM, CITE.mulliganCook],
    },
    {
      h2: 'Le scarpe barefoot o minimaliste rinforzano i piedi?',
      paragraphs: [
        'In uno studio, camminare con scarpe minimaliste ha rinforzato i muscoli del piede più o meno quanto gli esercizi. Nello stesso studio del 2019 di Ridge e colleghi, i runner che aumentavano gradualmente il numero di passi quotidiani con scarpe minimaliste hanno guadagnato dimensioni e forza muscolare simili al gruppo esercizi in circa due mesi. Gli autori hanno suggerito che cambiare scarpe potrebbe essere più facile da mantenere nel tempo che fare esercizi.',
        'Cambiare troppo in fretta ha i suoi rischi, soprattutto nella corsa. La guida sulle [scarpe barefoot](/it/scarpe-barefoot/) spiega come fare il passaggio e chi deve stare attento.',
      ],
      cites: [CITE.ridgeMinimalist],
    },
    {
      h2: 'Gli anziani possono rinforzare i piedi?',
      keyFact: 'In uno studio del 2016 su adulti tra 60 e 90\u00A0anni, un allenamento del piede supervisionato e progressivo ha aumentato la forza delle dita fino al 36%, mentre un programma a casa non l’ha cambiata (Mickle e colleghi).',
      paragraphs: [
        'Gli anziani possono rinforzare i piedi, e in uno studio a funzionare è stata la versione supervisionata con carichi via via più pesanti. In uno studio del 2016, Mickle e colleghi hanno assegnato 85\u00A0persone tra 60 e 90\u00A0anni a un corso supervisionato con esercizi per il piede via via più pesanti oppure a un programma di esercizi a casa, più un gruppo separato di 32\u00A0controlli.',
        'Dopo tre mesi, il gruppo supervisionato ha aumentato la forza delle dita fino al 36% e restava più a lungo su una gamba. Il gruppo a casa e il gruppo di controllo non hanno mostrato cambiamenti nella forza delle dita.',
        'Una revisione del 2022 di nove studi su adulti dai 65\u00A0anni in su ha trovato che il rinforzo dei muscoli intrinseci del piede aiutava forza, equilibrio e mobilità, e forse riduceva il rischio di caduta, con poco effetto sul modo di camminare. Gli autori hanno valutato discreta la qualità delle prove.',
        'Quindi passa a versioni più difficili quando diventano facili, e **tieni vicino un muro o un piano di lavoro per il lavoro di equilibrio.** Se le cadute ti preoccupano, un fisioterapista può impostare un programma sicuro.',
      ],
      cites: [CITE.mickleToe, CITE.futrellOlder],
    },
    {
      h2: 'Il rinforzo del piede aiuta la fascite plantare o il piede piatto?',
      paragraphs: [
        'Per la fascite plantare, il rinforzo del piede aggiunto allo stretching non ha fatto meglio del solo stretching in uno studio che li confrontava. Nel 2016, Kamonseki e colleghi hanno diviso 83\u00A0persone con fascite plantare in tre gruppi per due mesi:',
        {
          list: [
            'Rinforzo del piede più stretching.',
            'Rinforzo di piede e anca più stretching.',
            'Solo stretching.',
          ],
        },
        'Tutti e tre i gruppi sono migliorati per dolore e funzionalità, e nessun gruppo ha fatto meglio degli altri. Per il dolore al tallone, vedi gli [esercizi per la fascite plantare](/it/esercizi-fascite-plantare/).',
        'Per il piede piatto flessibile, uno studio del 2023 su 52\u00A0persone ha trovato che un programma misto con l’esercizio del piede corto cambiava la forma dell’arco più che nel gruppo di controllo. I dettagli, e i limiti del solo esercizio del piede corto, sono nella pagina sugli [esercizi per il piede piatto](/it/esercizi-piede-piatto/). Se il dolore è soprattutto alle dita, la guida sugli [esercizi per rinforzare le dita dei piedi](/it/esercizi-rinforzo-dita-piedi/) va più a fondo, e per la caviglia ci sono gli [esercizi di rinforzo della caviglia](/it/esercizi-rinforzo-caviglia/).',
      ],
      cites: [CITE.kamonseki, CITE.brijwasi],
    },
    {
      h2: 'Quanto sono solide le prove sul rinforzo del piede?',
      paragraphs: [
        'Le prove che gli esercizi per il piede rendono più forti i muscoli del piede vanno nella stessa direzione, ma gli studi sono piccoli. Una revisione del 2025 di Peters-Dickie e colleghi ha incluso 28\u00A0studi randomizzati con 1.399\u00A0persone. Ha sostenuto gli esercizi per il piede per aumentarne la forza, ma ha valutato la certezza da bassa a molto bassa, soprattutto perché c’erano pochi studi per ogni domanda e molti avevano un alto rischio di bias. I risultati sulle dimensioni dei muscoli erano contrastanti.',
        'Le prove che piedi più forti vogliano dire meno infortuni sono ancora più scarse e si basano soprattutto sull’unico studio sui runner visto sopra. **Il rinforzo del piede ha pochi rischi, costa poco e costruisce davvero forza.** Se prevenga il tuo prossimo infortunio è ancora una domanda aperta. Come queste guide valutano gli studi è spiegato nella pagina sulla [scienza](/science/) (in inglese).',
      ],
      sourceNote: 'Peters-Dickie 2025: le meta-analisi hanno mostrato che le scarpe minimaliste aumentavano la forza delle dita dalla 2 alla 5, e che gli esercizi per il piede riducevano il movimento dell’arco durante la corsa; certezza da bassa a molto bassa.',
      cites: [CITE.petersDickie],
    },
  ],
  faq: [
    {
      q: 'Quanto spesso fare gli esercizi per rinforzare i piedi?',
      cites: [CITE.ridgeMinimalist],
      a: 'Negli studi, la maggior parte dei programmi si faceva diverse volte a settimana. In uno studio del 2019, i runner facevano esercizi progressivi per il piede almeno cinque volte a settimana e hanno guadagnato dimensioni e forza muscolare in circa due mesi. Una breve sessione quasi tutti i giorni è un inizio ragionevole. I muscoli hanno bisogno di un po’ di recupero, quindi se la mattina dopo i piedi sono indolenziti, fai una giornata più leggera.',
    },
    {
      q: 'Meglio la raccolta dell’asciugamano o l’esercizio del piede corto?',
      cites: [CITE.jung, CITE.lynn],
      a: 'L’esercizio del piede corto lavora in modo più diretto sui muscoli dell’arco. In uno studio di laboratorio su 20\u00A0persone, il principale muscolo dell’arco interno era chiaramente più attivo durante il piede corto che durante la raccolta dell’asciugamano (Jung 2011). In un piccolo studio su 24\u00A0persone, un mese di piede corto ha migliorato un test di equilibrio più della raccolta dell’asciugamano (Lynn 2012). La raccolta dell’asciugamano resta un primo passo utile e facile.',
    },
    {
      q: 'Gli esercizi per rinforzare i piedi devono fare male?',
      a: 'No. Devi sentire fatica, e forse un leggero crampo sotto l’arco all’inizio, che passa quando rilassi. Un dolore acuto o un dolore a 6/10 o più vuol dire fermarsi per quel giorno. Se fa male sempre nello stesso punto, o il dolore ti tiene sveglio la notte, rivolgiti a un professionista sanitario prima di continuare.',
    },
    {
      q: 'Camminare a piedi nudi basta per rinforzare i piedi?',
      cites: [CITE.ridgeMinimalist],
      a: 'Potrebbe aiutare. In uno studio del 2019, i runner che aumentavano piano i passi quotidiani con scarpe minimaliste hanno guadagnato una forza del piede simile a quella di un gruppo esercizi in circa due mesi. Era un cambiamento graduale, non un passaggio improvviso. Passare troppo in fretta a piedi nudi può sovraccaricare il piede, quindi aumenta piano e tieni gli esercizi se ti piacciono.',
    },
    {
      q: 'Il rinforzo del piede può alzare un arco piatto?',
      cites: [CITE.mulliganCook, CITE.cheng],
      a: 'Solo un po’, e solo nel piede piatto flessibile. In un piccolo studio su 21\u00A0persone senza dolore al piede e senza gruppo di controllo, l’arco scendeva di 1,8\u00A0mm in meno dopo un mese di allenamento del piede corto. Una revisione del 2024 ha trovato che i programmi di piede corto cambiavano le misure dell’arco solo quando duravano più a lungo. Aspettati un piede più forte e stabile, non un arco di forma nuova.',
    },
    {
      q: 'Serve un’attrezzatura per rinforzare i piedi?',
      a: 'No. Per gli esercizi di questa pagina servono un pavimento, una sedia, un asciugamano e un muro a cui tenerti per l’equilibrio. Falli a piedi nudi così puoi vedere e sentire il piede muoversi. Più avanti puoi aggiungere carico con i sollevamenti sulle punte su una gamba o con uno zaino, ma il peso del corpo basta per molto tempo.',
    },
  ],
  redFlags: {
    h2: 'Rivolgiti prima a un professionista sanitario se',
    bullets: [
      'hai intorpidimento, formicolio o bruciore ai piedi, oppure hai il diabete con tagli o piaghe sulla pelle',
      'un piede si sta indebolendo, o la parte anteriore del piede striscia o sbatte a terra quando cammini',
      'un arco si sta appiattendo in fretta o il lato interno della caviglia è gonfio e dolente',
      'il dolore è in un punto preciso di un osso e peggiora a ogni camminata o corsa, il che può essere una frattura da stress',
      'il piede è rosso, caldo o gonfio, o hai la febbre',
      'non riesci a caricare il peso sul piede',
      'il dolore continua a peggiorare nonostante il riposo ed esercizi più leggeri',
    ],
  },
  program: {
    h2: 'Farlo come un piano',
    text: 'Walkito costruisce un piano settimanale intorno a un obiettivo e comprende gli esercizi per il piede di questa pagina: l’esercizio del piede corto da seduto fino a una gamba, l’apertura delle dita, il sollevamento dell’alluce, la raccolta dell’asciugamano, i sollevamenti sulle punte e il lavoro di equilibrio. Fa partire gli esercizi per l’arco da 3\u00A0serie da 8 con tenute di 5\u00A0secondi e l’equilibrio da 3\u00A0tenute da 20\u00A0secondi, e a ogni nuovo piano settimanale fa salire di un gradino il tuo esercizio principale quando hai valutato facili le ultime due sessioni con quell’esercizio e il dolore del mattino non è aumentato.',
    more: [
      'Scegli sessioni da 3, 5 o 10\u00A0minuti. All’inizio, ogni 14\u00A0giorni, un breve test controlla resistenza del polpaccio, tenuta dell’arco ed equilibrio, così vedi cosa sta cambiando. Walkito è un programma di esercizi per adulti. Non fa diagnosi e non sostituisce un professionista sanitario.',
    ],
    cta: 'Inizia con 3\u00A0minuti al giorno.',
  },
  crumb: 'Rinforzo del piede',
  campaign: 'guide-foot-strength-it',
};
