import { CITE } from '@/lib/citations';
import type { Guide } from '../types';

export const FOOT_STRENGTHENING_DE: Guide = {
  lang: 'de',
  page: 'footStrengthening',
  mainSource: CITE.taddeiRRI,
  published: '2026-10-09',
  updated: '2026-10-09',
  title: 'Fuß kräftigen: Übungen Schritt für Schritt',
  description:
    'Fuß kräftigen mit Übungen für kleine und große Fußmuskeln, vom Sitzen bis zum Stand auf einem Bein, mit Startdosis und Studien zu Verletzungen.',
  h1: 'Fuß kräftigen: Übungen, und wie du sie steigerst',
  lede:
    'Übungen zum Kräftigen der Füße trainieren die kleinen Muskeln im Fuß und die größeren, die von der Wade herunterlaufen. Fang im Sitzen an, mit der Kurzer-Fuß-Übung, Zehenspreizen und Großzehenheben, geh dann zum Stehen über und dann auf ein Bein. In Studien wurden die Fußmuskeln innerhalb von etwa zwei Monaten größer und kräftiger.',
  intro: [
    'Diese Seite ist der allgemeine Ratgeber für den ganzen Fuß. Für Plattfuß, Zehen oder Barfußschuhe sind die genaueren Seiten unten verlinkt.',
  ],
  takeaways: [
    'In einer Studie von 2020 mit 118\u00A0Freizeitläuferinnen und -läufern hatte die Gruppe ohne Fußtraining innerhalb von 12\u00A0Monaten eine 2,42-mal so hohe Wahrscheinlichkeit für eine Laufverletzung wie die Gruppe mit einem Fuß-Core-Programm (Taddei und Kollegen). Das ist eine einzelne Studie.',
    'In einer Studie von 2019 mit 57\u00A0Läuferinnen und Läufern machten etwa zwei Monate gesteigerter Fußübungen an mindestens fünf Tagen pro Woche jeden gemessenen Fußmuskel größer und kräftiger, während sich die Kontrollgruppe nicht veränderte (Ridge und Kollegen).',
    'Eine Übersichtsarbeit von 2025 über 28\u00A0Studien mit 1.399\u00A0Personen stützte Fußübungen für den Aufbau von Fußkraft, bewertete die Sicherheit der Belege aber als niedrig bis sehr niedrig (Peters-Dickie und Kollegen).',
    'Bei älteren Erwachsenen im Alter von 60 bis 90\u00A0Jahren steigerte ein betreutes Programm mit allmählich schwererer Last die Zehenkraft über drei Monate um bis zu 36\u00A0%, ein Programm für zu Hause dagegen nicht (Mickle und Kollegen, 2016).',
    'Bei Plantarfasziitis war Fußkräftigung zusätzlich zum Dehnen in einer Studie mit 83\u00A0Personen nicht besser als Dehnen allein (Kamonseki und Kollegen, 2016).',
  ],
  toc: true,
  sections: [
    {
      h2: 'Was sind die Fußmuskeln, und warum solltest du sie kräftigen?',
      paragraphs: [
        'Der Fuß hat zwei Muskelgruppen:',
        {
          list: [
            'Die **inneren (intrinsischen)** Fußmuskeln (die kleinen Muskeln, die im Fuß beginnen und enden) liegen unter dem Gewölbe und zwischen den Knochen. Sie halten das Gewölbe, spreizen die Zehen und machen die winzigen Korrekturen, die dich im Gleichgewicht halten.',
            'Zu den **äußeren (extrinsischen)** Fußmuskeln (die größeren Muskeln, die im Unterschenkel beginnen und den Fuß über lange Sehnen erreichen) gehören die Wade, die die Ferse hebt, und die Muskeln, die den Fuß drehen und anheben.',
          ],
        },
        'Eine Arbeit von McKeon und Kollegen von 2015 nannte die inneren Fußmuskeln den „Foot Core“. Die Idee ist dieselbe wie bei der tiefen Rumpfmuskulatur: kleine Stabilisatoren, die dafür sorgen, dass die größeren Muskeln gut arbeiten.',
        'Aus ihrer Sicht stützt die Versorgung des Fußes ihn häufiger von außen, als dass sie diese Muskeln trainiert, und so trainieren viele Menschen sie nie. Das ist ein Modell, keine gesicherte Ursache für Schmerzen, aber es erklärt, warum Fußprogramme zuerst die kleinen Muskeln trainieren und dann Wade und Gleichgewicht dazunehmen.',
        'Gutes Krafttraining für den Fuß deckt beide Gruppen ab:',
        {
          list: [
            'Kurzer-Fuß-Übung, Zehenspreizen und Großzehenheben trainieren die inneren Fußmuskeln.',
            'Fersenheben trainiert die Wade.',
            'Der Stand auf einem Bein lässt beide zusammenarbeiten.',
          ],
        },
      ],
      cites: [CITE.mcKeon],
    },
    {
      h2: 'Mit welchen Übungen zum Fußkräftigen solltest du anfangen?',
      keyFact: 'Eine Übersichtsarbeit von 2023 über vier Studien fand, dass die meisten Fußprogramme 5\u00A0Sekunden Halten nutzten und vom Sitzen zum Stehen übergingen (de Souza und Kollegen).',
      paragraphs: [
        'Fang mit den Übungen an, die die kleinen Fußmuskeln gezielt ansprechen, im Sitzen, und nimm Übungen im Stehen und für das Gleichgewicht dazu, wenn sie leicht werden. Eine Übersichtsarbeit von 2023 von de Souza und Kollegen untersuchte vier randomisierte Studien zur Kräftigung der inneren Fußmuskeln. Die meisten nutzten die Kurzer-Fuß-Übung und Handtuchgreifen, mit Anspannungen von etwa 5\u00A0Sekunden und einer Steigerung vom Sitzen zum Stehen.',
        'Die Dosen unten sind Startdosen. Mach die Übungen barfuß. Wenn eine Übung den Schmerz auf **6/10 oder mehr** bringt, hör für heute auf. Jede Übung hat eine eigene Seite mit mehr Details, verlinkt in der [Übungsbibliothek](/exercises/) (auf Englisch).',
      ],
      exercises: [
        {
          name: 'Kurzer Fuß im Sitzen',
          dose: '3\u00A0Sätze à 8, jeweils 5\u00A0Sekunden halten',
          often: 'Die meisten Einheiten',
          feel: 'Eine Anspannung unter dem Gewölbe, die Zehen bleiben locker',
          stop: 'Ein Krampf nicht nachlässt oder der Schmerz 6/10 erreicht',
          how: 'Setz dich hin, der Fuß steht flach. Zieh den Fußballen Richtung Ferse, ohne die Zehen einzukrallen, sodass sich das Gewölbe ein wenig hebt. Halten, dann entspannen. Die Bewegung ist klein. Wenn sich deine Zehen in den Boden krallen, lass locker und versuch es noch einmal. Die vollständige Technik findest du auf der Seite zur [Kurzer-Fuß-Übung](/de/uebungen/kurzer-fuss/).',
          media: 'short_foot_seated',
          caption: 'Kurzer Fuß im Sitzen: Zieh den Fußballen Richtung Ferse, die Zehen bleiben flach',
          alt: 'Eine sitzende Figur hebt das Gewölbe eines Fußes, während die Zehen flach auf dem Boden bleiben',
          evidence: { level: 'moderate', why: 'In den meisten Studien der Übersichtsarbeit von 2023 zur Fußkräftigung verwendet (de Souza), mit Belegen niedriger Qualität für Veränderungen bei Gewölbe und Gleichgewicht. Nie allein bei Verletzungen oder Schmerzen getestet.' },
        },
        {
          name: 'Zehenspreizen',
          dose: '3\u00A0Sätze à 10',
          often: 'Die meisten Einheiten',
          feel: 'Arbeit entlang der Seiten des Fußes',
          stop: 'Ein Krampf nicht nachlässt',
          how: 'Der Fuß steht flach. Spreiz alle fünf Zehen so weit du kannst, halte kurz und entspann. Ferse und Fußballen bleiben auf dem Boden.',
          media: 'toe_spread',
          caption: 'Zehenspreizen: Zehen weit spreizen, Ferse und Fußballen unten',
          alt: 'Ein nackter Fuß auf dem Boden mit gespreizten Zehen',
          evidence: { level: 'early', why: 'Eine MRT-Studie zeigt, dass die Übung die kleinen Fußmuskeln aktiviert (Gooding 2016). Nicht allein in einer Studie zu Ergebnissen getestet.' },
        },
        {
          name: 'Großzehenheben',
          dose: '3\u00A0Sätze à 8, jeweils 5\u00A0Sekunden halten',
          often: 'Die meisten Einheiten',
          feel: 'Anstrengung oben auf dem Fuß und unter dem Gewölbe',
          stop: 'Schmerz im Großzehengrundgelenk auftritt',
          how: 'Lass die vier kleinen Zehen auf dem Boden und heb nur die Großzehe. Dann probier es umgekehrt: Großzehe unten, kleine Zehen oben. Am Anfang ist das schwer. Eine kleine Bewegung reicht.',
          media: 'big_toe_lift',
          caption: 'Großzehenheben: Nur die Großzehe kommt hoch',
          alt: 'Ein nackter Fuß mit angehobener Großzehe, die anderen Zehen liegen flach auf dem Boden',
          evidence: { level: 'early', why: 'Eine MRT-Studie zeigt, dass die Übung die kleinen Fußmuskeln aktiviert (Gooding 2016). Wird in Fußprogrammen verwendet, aber nicht allein getestet.' },
        },
        {
          name: 'Handtuchgreifen',
          dose: '3\u00A0Sätze à 8, jeweils 5\u00A0Sekunden halten',
          often: 'Die meisten Einheiten',
          feel: 'Arbeit unter den Zehen und dem Gewölbe',
          stop: 'Ein Krampf nicht nachlässt',
          how: 'Setz dich hin, ein Handtuch liegt unter deinem Fuß. Krall die Zehen ein, um das Handtuch zu dir heranzuziehen, halte, lass dann los und streich es wieder glatt. Das trainiert die langen Zehenmuskeln genauso wie die kleinen.',
          media: 'towel_scrunch',
          caption: 'Handtuchgreifen: Krall die Zehen ein und zieh das Handtuch zusammen',
          alt: 'Ein nackter Fuß krallt die Zehen ein, um ein Handtuch über den Boden zu ziehen',
          evidence: { level: 'early', why: 'In den meisten Studien der Übersichtsarbeit von 2023 verwendet, meist zusammen mit der Kurzer-Fuß-Übung. Nicht allein bei Schmerzen oder Verletzungen getestet.' },
        },
        {
          name: 'Fersenheben beidbeinig',
          dose: '3\u00A0Sätze à 10',
          often: 'Die meisten Einheiten',
          feel: 'Arbeit in den Waden und den Fußballen',
          stop: 'Der Schmerz an Ferse oder Achillessehne 6/10 erreicht',
          how: 'Halt dich an einer Wand fest. Komm in etwa 3\u00A0Sekunden auf die Fußballen beider Füße hoch und senk dich in 3\u00A0Sekunden ab. Versuch, das Gewicht über der Seite der Großzehe zu halten, ohne nach außen zu kippen. Mehr auf der Seite [Fersenheben](/de/uebungen/fersenheben/).',
          media: 'heel_raise_double',
          caption: 'Beidbeiniges Fersenheben: langsam hoch, langsam runter',
          alt: 'Eine Figur hält sich an einer Wand fest und kommt auf die Fußballen beider Füße hoch',
          evidence: { level: 'moderate', why: 'Für Fersenheben gibt es Belege aus Studien bei Plantarfasziitis (Rathleff 2015). Hier trainiert es die Wade, den wichtigsten äußeren Fußmuskel.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.gooding, CITE.rathleff],
    },
    {
      h2: 'Wie steigerst du dich vom Sitzen zum Stehen und auf ein Bein?',
      paragraphs: [
        'Steigere Übungen zum Fußkräftigen, indem du Schritt für Schritt mehr Körpergewicht auf den Fuß bringst. Im Sitzen lernst du die Bewegung. Im Stehen auf beiden Füßen kommt die Hälfte deines Körpergewichts dazu. Auf einem Fuß kommt das ganze Gewicht dazu und dazu noch das Gleichgewicht. Geh nur dann eine Stufe höher, wenn sich die aktuelle leicht und kontrolliert anfühlt.',
        'Walkito nutzt bei der Kurzer-Fuß-Übung dieselben drei Stufen: im Sitzen, dann im Stehen auf beiden Füßen, dann auf einem Bein. Wenn das Gewölbe der Schwerpunkt deines Plans ist, hebt dich der nächste Wochenplan eine Stufe höher, wenn du deine letzten zwei Einheiten mit dieser Übung als leicht bewertet hast und dein Morgenschmerz nicht gestiegen ist. Eine Einheit, die du als schwer bewertest, oder ein Morgenschmerz, der um 2\u00A0Punkte steigt, bringt dich eine Stufe zurück. Die zwei späteren Stufen siehst du unten.',
      ],
      bullets: [
        '**Stufe 1, im Sitzen.** Kurzer Fuß, Zehenspreizen, Großzehenheben und Handtuchgreifen, alles im Sitzen.',
        '**Stufe 2, im Stehen auf beiden Füßen.** Kurzer Fuß halten im Stehen und beidbeiniges Fersenheben.',
        '**Stufe 3, auf einem Bein.** Kurzer Fuß halten auf einem Bein, dann Einbeinstand mit gehaltenem Gewölbe.',
        '**Später.** Einbeiniges Fersenheben und, wenn du läufst, kleine Hüpfer. Das sind größere Belastungen. Nimm sie erst dazu, wenn Stufe 3 leicht geht.',
      ],
      exercises: [
        {
          name: 'Kurzer Fuß im Stehen',
          dose: '3\u00A0Sätze à 8, jeweils 5\u00A0Sekunden halten',
          often: 'Sobald die Variante im Sitzen leicht geht',
          feel: 'Das Gewölbe hebt sich unter deinem Körpergewicht',
          stop: 'Der Schmerz 6/10 erreicht oder sich die Zehen immer wieder einkrallen',
          how: 'Stell dich hin, das Gewicht gleichmäßig auf beiden Füßen. Heb die Gewölbe wie im Sitzen, die Zehen locker, die Knie leicht gebeugt. Halten, dann entspannen.',
          media: 'short_foot_double',
          caption: 'Kurzer Fuß im Stehen: Heb beide Gewölbe, ohne die Zehen einzukrallen',
          alt: 'Eine stehende Figur hebt die Gewölbe beider Füße',
          evidence: { level: 'moderate', why: 'Die Steigerung vom Sitzen zum Stehen wurde in den meisten Studien der Übersichtsarbeit von 2023 verwendet. Nicht allein bei Schmerzen oder Verletzungen getestet.' },
        },
        {
          name: 'Kurzer Fuß auf einem Bein',
          dose: '3\u00A0Sätze à 10, jeweils 5\u00A0Sekunden halten',
          often: 'Sobald die Variante auf beiden Füßen leicht geht',
          feel: 'Der ganze Fuß und das Sprunggelenk arbeiten, um stabil zu bleiben',
          stop: 'Der Schmerz 6/10 erreicht oder du das Gewölbe nicht oben halten kannst',
          how: 'Stell dich nahe an einer Wand auf einen Fuß. Heb das Gewölbe und halte es, während du balancierst. Berühr die Wand, wenn du musst.',
          media: 'short_foot_single',
          caption: 'Kurzer Fuß auf einem Bein: Halte das Gewölbe, während du balancierst',
          alt: 'Eine Figur steht auf einem Fuß mit gehobenem Gewölbe, eine Hand nahe an einer Wand',
          evidence: { level: 'early', why: 'Wird in Fuß-Core-Programmen als letzte Stufe verwendet. Zu genau dieser Variante gibt es wenig Forschung.' },
        },
        {
          name: 'Einbeinstand',
          dose: '3-mal 20\u00A0Sekunden halten, jedes Bein',
          often: 'Gleichgewichtstage',
          feel: 'Kleine, ständige Korrekturen im Fuß',
          stop: 'Der Schmerz 6/10 erreicht oder dir schwindelig wird',
          how: 'Stell dich auf einen Fuß und schau auf einen Punkt vor dir. Lass den Fuß kleine Wackler machen. Das ist die eigentliche Arbeit. Steh nahe an einer Wand oder Arbeitsplatte. Mehr auf der Seite [Einbeinstand](/de/uebungen/einbeinstand/).',
          media: 'single_leg_hold',
          caption: 'Einbeinstand: Lass den Fuß die Korrekturen machen',
          alt: 'Eine Figur balanciert neben einer Wand auf einem Bein',
          evidence: { level: 'moderate', why: 'Gleichgewichtstraining senkte in einer Metaanalyse die Rate an Umknickverletzungen (Bellows 2018). Für die Fußkraft selbst wurde es nicht allein getestet.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.bellows],
    },
    {
      h2: 'Beugen Übungen zum Fußkräftigen Laufverletzungen vor?',
      keyFact: 'In einer Studie von 2020 mit 118\u00A0Läuferinnen und Läufern hatten diejenigen ohne Fuß-Core-Training innerhalb von 12\u00A0Monaten eine 2,42-mal so hohe Verletzungswahrscheinlichkeit (Taddei und Kollegen).',
      paragraphs: [
        'Übungen zum Fußkräftigen **senkten Laufverletzungen in einer guten Studie, aber eben nur in einer.** 2020 teilten Taddei und Kollegen 118\u00A0Freizeitläuferinnen und -läufer auf Langstrecken zufällig in eine Fuß-Core-Gruppe (57) und eine Kontrollgruppe (61) auf. Die Fuß-Core-Gruppe machte einen betreuten Kurs von etwa zwei Monaten für die Fuß- und Sprunggelenkmuskeln und trainierte danach mit Betreuung aus der Ferne weiter.',
        'Innerhalb von 12\u00A0Monaten hatte die Kontrollgruppe eine 2,42-mal so hohe Wahrscheinlichkeit für eine Laufverletzung. Die Autorinnen und Autoren sahen den Effekt nach etwa vier bis acht Monaten Training auftreten.',
        'Eine frühere, kleinere Studie desselben Teams mit 28\u00A0Läuferinnen und Läufern fand, dass etwa zwei Monate Fußtraining jeden gemessenen Fußmuskel im Vergleich zur Kontrollgruppe vergrößerten. Die Läuferinnen und Läufer drückten sich außerdem mit mehr Kraft vom Boden ab.',
        'Beide Studien stammen von einer Forschungsgruppe in Brasilien, mit Freizeitläuferinnen und -läufern, die zu Beginn nicht verletzt waren. Wir wissen noch nicht, ob das Programm Anfängerinnen und Anfängern hilft oder Menschen, die schon Schmerzen haben. Wenn du läufst und jetzt Fersenschmerzen hast, fang mit [Fersenschmerzen beim Laufen](/heel-pain-runners/) (auf Englisch) an.',
      ],
      sourceNote: 'Taddei 2020 (Am J Sports Med): Kontrollgruppe mit 2,42-fach höherer Verletzungswahrscheinlichkeit (95-%-KI 1,98 bis 3,62), p = 0,035, einfach verblindete RCT, Nachbeobachtung über 12\u00A0Monate. Taddei 2020 (Phys Ther Sport): einfach verblindete Machbarkeits-RCT, 28\u00A0Läuferinnen und Läufer, Muskelvolumen per MRT.',
      cites: [CITE.taddeiRRI, CITE.taddeiMuscle],
    },
    {
      h2: 'Wie lange dauert es, die Füße zu kräftigen?',
      keyFact: 'In einer Studie von 2019 mit 57\u00A0Läuferinnen und Läufern wuchsen die Fußmuskeln über etwa zwei Monate und wurden kräftiger, manche Muskeln waren schon nach einem Monat größer (Ridge und Kollegen).',
      paragraphs: [
        'In den Studien wurden die Fußmuskeln **mit regelmäßigem Training in etwa zwei Monaten** messbar kräftiger. 2019 teilten Ridge und Kollegen 57\u00A0Läuferinnen und Läufer zufällig auf:',
        {
          list: [
            'Fußkräftigungsübungen.',
            'Gehen in Minimalschuhen.',
            'Keine Veränderung.',
          ],
        },
        'Die Übungsgruppe machte an mindestens fünf Tagen pro Woche Übungen mit steigendem Widerstand. Nach etwa zwei Monaten war jeder gemessene Fußmuskel in beiden aktiven Gruppen größer und kräftiger, in der Kontrollgruppe gab es keine Veränderung. Manche Muskeln waren schon bei der Messung nach einem Monat größer.',
        'Die Form des Gewölbes verändert sich langsamer und weniger. Eine Übersichtsarbeit von 2023 über vier Studien fand, dass die Kräftigung der inneren Fußmuskeln nach einem Monat nicht veränderte, wie stark sich das Gewölbe bewegt, nach zwei Monaten aber schon, bei Belegen niedriger Qualität.',
        'In einer kleinen Studie von Mulligan und Cook mit 21\u00A0Personen und ohne Kontrollgruppe sank der Navicular Drop (wie weit das innere Gewölbe im Stehen absinkt) nach einem Monat Kurzer-Fuß-Training im Durchschnitt um 1,8\u00A0mm. Das ist eine echte, aber kleine Veränderung.',
      ],
      cites: [CITE.ridgeMinimalist, CITE.deSouzaIFM, CITE.mulliganCook],
    },
    {
      h2: 'Kräftigen Barfuß- oder Minimalschuhe die Füße?',
      paragraphs: [
        'Gehen in Minimalschuhen kräftigte die Fußmuskeln in einer Studie etwa so gut wie Fußübungen. In derselben Studie von Ridge und Kollegen von 2019 gewannen Läuferinnen und Läufer, die die Zahl ihrer täglichen Schritte in Minimalschuhen allmählich steigerten, über etwa zwei Monate ähnlich viel Muskelgröße und Kraft wie die Übungsgruppe. Die Autorinnen und Autoren vermuteten, dass ein Schuhwechsel leichter durchzuhalten sein könnte als Übungen.',
        'Ein zu schneller Wechsel hat eigene Risiken, besonders beim Laufen. Der Ratgeber zu [Barfußschuhen](/de/barfussschuhe/) erklärt, wie du umsteigst und wer vorsichtig sein sollte.',
      ],
      cites: [CITE.ridgeMinimalist],
    },
    {
      h2: 'Können ältere Menschen ihre Füße kräftigen?',
      keyFact: 'In einer Studie von 2016 mit Erwachsenen im Alter von 60 bis 90\u00A0Jahren steigerte betreutes, gesteigertes Fußtraining die Zehenkraft um bis zu 36\u00A0%, während ein Programm für zu Hause sie nicht veränderte (Mickle und Kollegen).',
      paragraphs: [
        'Ältere Menschen können ihre Füße kräftigen, und in einer Studie war es die betreute Variante mit allmählich schwererer Last, die funktionierte. In einer Studie von 2016 teilten Mickle und Kollegen 85\u00A0Menschen im Alter von 60 bis 90\u00A0Jahren entweder einem betreuten Kurs mit allmählich schwereren Fußübungen oder einem Übungsprogramm für zu Hause zu, dazu kam eine separate Kontrollgruppe mit 32\u00A0Personen.',
        'Nach drei Monaten steigerte die betreute Gruppe ihre Zehenkraft um bis zu 36\u00A0% und konnte länger auf einem Bein stehen. Die Heimgruppe und die Kontrollgruppe zeigten keine Veränderung der Zehenkraft.',
        'Eine Übersichtsarbeit von 2022 über neun Studien bei Erwachsenen ab 65 fand, dass die Kräftigung der inneren Fußmuskeln Kraft, Gleichgewicht und Beweglichkeit verbesserte und möglicherweise das Sturzrisiko senkte, mit wenig Effekt auf das Gangbild. Die Autorinnen und Autoren bewerteten die Qualität der Belege als mittelmäßig.',
        'Geh also zu schwereren Varianten über, wenn sie leicht werden, und **halte für Gleichgewichtsübungen eine Wand oder Arbeitsplatte in der Nähe.** Wenn Stürze ein Thema sind, kann eine Physiotherapeutin oder ein Physiotherapeut ein sicheres Programm zusammenstellen.',
      ],
      cites: [CITE.mickleToe, CITE.futrellOlder],
    },
    {
      h2: 'Hilft Fußkräftigung bei Plantarfasziitis oder Plattfuß?',
      paragraphs: [
        'Bei Plantarfasziitis war Fußkräftigung zusätzlich zum Dehnen in einer Studie, die beides verglich, nicht besser als Dehnen allein. 2016 teilten Kamonseki und Kollegen 83\u00A0Menschen mit Plantarfasziitis für zwei Monate auf drei Gruppen auf:',
        {
          list: [
            'Fußkräftigung plus Dehnen.',
            'Fuß- und Hüftkräftigung plus Dehnen.',
            'Nur Dehnen.',
          ],
        },
        'Alle drei Gruppen verbesserten sich bei Schmerz und Funktion, und keine Gruppe schnitt besser ab als die anderen. Bei Fersenschmerzen lies [Übungen bei Plantarfasziitis](/de/plantarfasziitis-uebungen/).',
        'Bei flexiblem Plattfuß fand eine Studie von 2023 mit 52\u00A0Personen, dass ein gemischtes Programm mit der Kurzer-Fuß-Übung die Form des Gewölbes stärker veränderte als in der Kontrollgruppe. Die Details und die Grenzen des Kurzer-Fuß-Trainings allein findest du auf der Seite [Übungen bei Plattfuß](/de/plattfuss-uebungen/). Wenn deine Schmerzen vor allem in den Zehen sitzen, geht der Ratgeber [Zehen kräftigen: Übungen](/de/zehen-kraeftigen-uebungen/) tiefer, und für das Sprunggelenk gibt es [Sprunggelenk stärken: Übungen](/de/sprunggelenk-staerken-uebungen/).',
      ],
      cites: [CITE.kamonseki, CITE.brijwasi],
    },
    {
      h2: 'Wie stark sind die Belege für Fußkräftigung?',
      paragraphs: [
        'Die Belege dafür, dass Fußübungen die Fußmuskeln kräftigen, zeigen in dieselbe Richtung, aber die Studien sind klein. Eine Übersichtsarbeit von 2025 von Peters-Dickie und Kollegen schloss 28 randomisierte Studien mit 1.399\u00A0Personen ein. Sie stützte Fußübungen für mehr Fußkraft, bewertete die Sicherheit aber als niedrig bis sehr niedrig, vor allem weil es pro Fragestellung wenige Studien gab und viele ein hohes Verzerrungsrisiko hatten. Die Ergebnisse zur Muskelgröße waren gemischt.',
        'Die Belege dafür, dass kräftigere Füße weniger Verletzungen bedeuten, sind noch dünner und stützen sich vor allem auf die eine Läuferstudie oben. **Fußkräftigung ist risikoarm und günstig, und sie baut Kraft auf.** Ob sie deiner nächsten Verletzung vorbeugt, ist noch offen. Mehr dazu, wie diese Ratgeber Forschung bewerten, steht auf der Seite [Wissenschaft](/science/) (auf Englisch).',
      ],
      sourceNote: 'Peters-Dickie 2025: Metaanalysen zeigten, dass Minimalschuhe die Kraft der Zehen 2 bis 5 steigerten und Fußübungen die Bewegung des Gewölbes beim Laufen verringerten; Sicherheit niedrig bis sehr niedrig.',
      cites: [CITE.petersDickie],
    },
  ],
  faq: [
    {
      q: 'Wie oft solltest du Übungen zum Fußkräftigen machen?',
      cites: [CITE.ridgeMinimalist],
      a: 'Die meisten Programme in der Forschung liefen mehrmals pro Woche. In einer Studie von 2019 machten Läuferinnen und Läufer an mindestens fünf Tagen pro Woche gesteigerte Fußübungen und gewannen über etwa zwei Monate an Muskelgröße und Kraft. Eine kurze Einheit an den meisten Tagen ist ein vernünftiger Anfang. Muskeln brauchen etwas Erholung. Wenn sich deine Füße am nächsten Morgen wund anfühlen, mach einen leichteren Tag.',
    },
    {
      q: 'Ist Handtuchgreifen oder die Kurzer-Fuß-Übung besser?',
      cites: [CITE.jung, CITE.lynn],
      a: 'Die Kurzer-Fuß-Übung spricht die Gewölbemuskeln direkter an. In einer Laborstudie mit 20\u00A0Personen war der wichtigste Muskel des inneren Gewölbes bei der Kurzer-Fuß-Übung deutlich aktiver als beim Handtuchgreifen (Jung 2011). In einer kleinen Studie mit 24\u00A0Personen verbesserte ein Monat Kurzer-Fuß-Training einen Gleichgewichtstest stärker als Handtuchgreifen (Lynn 2012). Handtuchgreifen ist trotzdem ein nützlicher, leichter erster Schritt.',
    },
    {
      q: 'Sollen Übungen zum Fußkräftigen wehtun?',
      a: 'Nein. Du solltest Anstrengung spüren und am Anfang vielleicht einen leichten Krampf unter dem Gewölbe, der nachlässt, wenn du entspannst. Stechender Schmerz oder ein Schmerz von 6/10 oder mehr heißt: Hör für heute auf. Wenn jedes Mal dieselbe Stelle wehtut oder dich der Schmerz nachts wach hält, geh zu einer medizinischen Fachperson, bevor du weitermachst.',
    },
    {
      q: 'Reicht Barfußgehen, um die Füße zu kräftigen?',
      cites: [CITE.ridgeMinimalist],
      a: 'Es kann helfen. In einer Studie von 2019 gewannen Läuferinnen und Läufer, die ihre täglichen Schritte in Minimalschuhen langsam steigerten, über etwa zwei Monate ähnlich viel Fußkraft wie eine Übungsgruppe. Das war ein allmählicher Wechsel, kein plötzlicher. Zu schnell barfuß zu gehen kann den Fuß überlasten. Steigere also langsam und behalte die Übungen bei, wenn sie dir gefallen.',
    },
    {
      q: 'Kann Fußkräftigung ein flaches Gewölbe anheben?',
      cites: [CITE.mulliganCook, CITE.cheng],
      a: 'Nur ein wenig, und nur bei flexiblem Plattfuß. In einer kleinen Studie mit 21\u00A0Personen ohne Fußschmerzen und ohne Kontrollgruppe sank das Gewölbe nach einem Monat Kurzer-Fuß-Training um 1,8\u00A0mm weniger ab. Eine Übersichtsarbeit von 2024 fand, dass Kurzer-Fuß-Programme die Messwerte des Gewölbes nur dann veränderten, wenn sie länger liefen. Rechne mit einem kräftigeren, stabileren Fuß, nicht mit einer neuen Gewölbeform.',
    },
    {
      q: 'Brauchst du Geräte, um die Füße zu kräftigen?',
      a: 'Nein. Für die Übungen auf dieser Seite brauchst du einen Boden, einen Stuhl, ein Handtuch und eine Wand zum Festhalten beim Gleichgewicht. Mach sie barfuß, damit du siehst und spürst, wie sich der Fuß bewegt. Später kannst du mit einbeinigem Fersenheben oder einem Rucksack Last dazunehmen, aber das Körpergewicht reicht lange Zeit aus.',
    },
  ],
  redFlags: {
    h2: 'Geh zuerst zu einer medizinischen Fachperson, wenn',
    bullets: [
      'du Taubheit, Kribbeln oder Brennen in den Füßen hast oder Diabetes und offene Stellen oder Wunden an der Haut',
      'ein Fuß schwächer wird oder der Vorfuß beim Gehen schleift oder auf den Boden klatscht',
      'ein Gewölbe schnell absinkt oder die Innenseite des Sprunggelenks geschwollen und schmerzhaft ist',
      'der Schmerz an einer Stelle an einem Knochen sitzt und mit jedem Gehen oder Laufen schlimmer wird, was ein Ermüdungsbruch sein kann',
      'der Fuß gerötet, heiß oder geschwollen ist oder du Fieber hast',
      'du den Fuß nicht belasten kannst',
      'der Schmerz trotz Ruhe und leichterer Übungen immer schlimmer wird',
    ],
  },
  program: {
    h2: 'Als Plan umsetzen',
    text: 'Walkito baut einen Wochenplan rund um ein Ziel auf und enthält die Fußübungen auf dieser Seite: die Kurzer-Fuß-Übung vom Sitzen bis auf ein Bein, Zehenspreizen, Großzehenheben, Handtuchgreifen, Fersenheben und Gleichgewichtsübungen. Die Gewölbeübungen starten mit 3\u00A0Sätzen à 8 mit 5\u00A0Sekunden Halten und das Gleichgewicht mit 3-mal 20\u00A0Sekunden Halten. Mit jedem neuen Wochenplan hebt die App deine Schwerpunktübung eine Stufe höher, wenn du deine letzten zwei Einheiten damit als leicht bewertet hast und dein Morgenschmerz nicht gestiegen ist.',
    more: [
      'Du wählst Einheiten von 3, 5 oder 10\u00A0Minuten. Anfangs alle 14\u00A0Tage prüft ein kurzer Test Wadenausdauer, Gewölbehalten und Gleichgewicht, damit du siehst, was sich verändert. Walkito ist ein Übungsprogramm für Erwachsene. Es stellt keine Diagnose und ersetzt keine medizinische Fachperson.',
    ],
    cta: 'Fang mit 3\u00A0Minuten am Tag an.',
  },
  crumb: 'Fuß kräftigen',
  campaign: 'guide-foot-strength-de',
};
