import { CITE } from '@/lib/citations';
import type { Guide } from '../types';

export const FOOT_STRENGTHENING_ES: Guide = {
  lang: 'es',
  page: 'footStrengthening',
  mainSource: CITE.taddeiRRI,
  published: '2026-10-09',
  updated: '2026-10-09',
  title: 'Ejercicios para fortalecer los pies: paso a paso',
  description:
    'Ejercicios para fortalecer los pies, músculos pequeños y grandes, de sentado a una pierna, con dosis de inicio y qué hallaron los ensayos sobre lesiones.',
  h1: 'Ejercicios para fortalecer los pies: qué hacer y cómo progresar',
  lede:
    'Los ejercicios para fortalecer los pies entrenan los músculos pequeños dentro del pie y los más grandes que bajan desde la pantorrilla. Empieza sentado con el ejercicio de pie corto, la separación de dedos y la elevación del dedo gordo, luego pasa a hacerlos de pie y después a una pierna. En los ensayos, los músculos del pie crecieron y ganaron fuerza en unos dos meses.',
  intro: [
    'Esta página es la guía general para todo el pie. Para pie plano, dedos o zapatos barefoot, las páginas más específicas están enlazadas abajo.',
  ],
  takeaways: [
    'En un ensayo de 2020 con 118\u00A0corredores recreativos, el grupo sin entrenamiento de pie tuvo 2,42\u00A0veces más probabilidades de sufrir una lesión por correr en 12\u00A0meses que el grupo que hizo un programa de core del pie (Taddei y colegas). Es un solo ensayo.',
    'En un ensayo de 2019 con 57\u00A0corredores, unos dos meses de ejercicios progresivos para el pie, hechos al menos cinco veces por semana, hicieron más grande y más fuerte cada músculo del pie que se midió, mientras que el grupo control no cambió (Ridge y colegas).',
    'Una revisión de 2025 de 28\u00A0ensayos con 1399\u00A0personas respaldó los ejercicios para el pie para ganar fuerza en el pie, pero calificó la certeza de la evidencia de baja a muy baja (Peters-Dickie y colegas).',
    'En adultos mayores de 60 a 90\u00A0años, un programa supervisado con cargas cada vez más pesadas aumentó la fuerza de los dedos hasta un 36\u00A0por ciento en tres meses, mientras que un programa en casa no lo logró (Mickle y colegas, 2016).',
    'Para la fascitis plantar, agregar fortalecimiento del pie al estiramiento no superó al estiramiento solo en un ensayo con 83\u00A0personas (Kamonseki y colegas, 2016).',
  ],
  toc: true,
  sections: [
    {
      h2: '¿Cuáles son los músculos del pie y por qué fortalecerlos?',
      paragraphs: [
        'El pie tiene dos grupos de músculos:',
        {
          list: [
            'Los músculos **intrínsecos** (los músculos pequeños que empiezan y terminan dentro del pie) están bajo el arco y entre los huesos. Sostienen el arco, separan los dedos y hacen las pequeñísimas correcciones que te mantienen en equilibrio.',
            'Los músculos **extrínsecos** (los músculos más grandes que empiezan en la pierna y llegan al pie por tendones largos) incluyen la pantorrilla, que levanta el talón, y los músculos que giran y levantan el pie.',
          ],
        },
        'Un artículo de 2015 de McKeon y colegas llamó a los músculos intrínsecos el «core del pie». La idea es la misma que con los músculos profundos del tronco: estabilizadores pequeños que hacen que los músculos más grandes trabajen bien.',
        'Su punto de vista era que el cuidado del pie suele sostener el pie desde afuera más que entrenar estos músculos, así que mucha gente nunca los entrena. Es un modelo, no una causa comprobada de dolor, pero explica por qué los programas para el pie entrenan primero los músculos pequeños y luego agregan la pantorrilla y el equilibrio.',
        'Un buen trabajo de fuerza para el pie cubre los dos grupos:',
        {
          list: [
            'El ejercicio de pie corto, la separación de dedos y la elevación del dedo gordo entrenan los músculos intrínsecos.',
            'Las elevaciones de talón entrenan la pantorrilla.',
            'Pararse en una pierna hace que los dos trabajen juntos.',
          ],
        },
      ],
      cites: [CITE.mcKeon],
    },
    {
      h2: '¿Con qué ejercicios para fortalecer los pies empezar?',
      keyFact: 'Una revisión de 2023 de cuatro ensayos encontró que la mayoría de los programas para el pie usaron contracciones sostenidas de 5\u00A0segundos y pasaron de sentado a de pie (de Souza y colegas).',
      paragraphs: [
        'Empieza con los ejercicios que aíslan los músculos pequeños del pie, sentado, y luego agrega trabajo de pie y de equilibrio cuando se vuelvan fáciles. Una revisión de 2023 de de Souza y colegas analizó cuatro ensayos aleatorizados de fortalecimiento intrínseco del pie. La mayoría usó el ejercicio de pie corto y recoger la toalla con los dedos, con contracciones sostenidas unos 5\u00A0segundos y una progresión de sentado a de pie.',
        'Las dosis de abajo son dosis de inicio. Hazlas descalzo. Si algún ejercicio lleva tu dolor a **6/10 o más**, para por el día. Cada ejercicio tiene su propia página con más detalle, enlazada desde la [biblioteca de ejercicios](/es/ejercicios/).',
      ],
      exercises: [
        {
          name: 'Pie corto, sentado',
          dose: '3\u00A0series de 8, sosteniendo cada una 5\u00A0segundos',
          often: 'Casi todas las sesiones',
          feel: 'Una tensión bajo el arco, con los dedos todavía relajados',
          stop: 'Un calambre que no cede, o dolor de 6/10',
          how: 'Siéntate con el pie plano. Sin encoger los dedos, lleva la parte delantera del pie hacia el talón para que el arco suba un poco. Sostén y relaja. El movimiento es pequeño. Si los dedos se aferran al piso, afloja y vuelve a intentar. La técnica completa está en la página del [ejercicio de pie corto](/es/ejercicios/pie-corto/).',
          media: 'short_foot_seated',
          caption: 'Pie corto, sentado: lleva la parte delantera del pie hacia el talón, dedos planos',
          alt: 'Una figura sentada levantando el arco de un pie mientras los dedos se quedan planos en el piso',
          evidence: { level: 'moderate', why: 'Se usó en la mayoría de los ensayos de la revisión de 2023 sobre fortalecimiento del pie (de Souza), con evidencia de baja calidad para cambios en el arco y el equilibrio. Nunca se ha probado por sí solo para lesiones o dolor.' },
        },
        {
          name: 'Separación de dedos',
          dose: '3\u00A0series de 10',
          often: 'Casi todas las sesiones',
          feel: 'Trabajo a lo largo de los costados del pie',
          stop: 'Un calambre que no cede',
          how: 'Con el pie plano, separa los cinco dedos lo más que puedas, sostén un momento y relaja. Mantén el talón y la parte delantera del pie en el piso.',
          media: 'toe_spread',
          caption: 'Separación de dedos: separa bien los dedos, talón y parte delantera del pie abajo',
          alt: 'Un pie descalzo en el piso con los dedos separados',
          evidence: { level: 'early', why: 'Un estudio con resonancia magnética muestra que activa los músculos pequeños del pie (Gooding 2016). No se ha probado por sí solo en un ensayo de resultados.' },
        },
        {
          name: 'Elevación del dedo gordo',
          dose: '3\u00A0series de 8, sosteniendo cada una 5\u00A0segundos',
          often: 'Casi todas las sesiones',
          feel: 'Esfuerzo en el empeine y bajo el arco',
          stop: 'Dolor en la articulación del dedo gordo',
          how: 'Mantén los cuatro dedos pequeños en el piso y levanta solo el dedo gordo. Luego prueba al revés: dedo gordo abajo, dedos pequeños arriba. Al principio cuesta. Un movimiento pequeño es suficiente.',
          media: 'big_toe_lift',
          caption: 'Elevación del dedo gordo: solo sube el dedo gordo',
          alt: 'Un pie descalzo con el dedo gordo levantado y los demás dedos planos en el piso',
          evidence: { level: 'early', why: 'Un estudio con resonancia magnética muestra que activa los músculos pequeños del pie (Gooding 2016). Se usa en programas para el pie, pero no se ha probado por sí solo.' },
        },
        {
          name: 'Recoger la toalla',
          dose: '3\u00A0series de 8, sosteniendo cada una 5\u00A0segundos',
          often: 'Casi todas las sesiones',
          feel: 'Trabajo bajo los dedos y el arco',
          stop: 'Un calambre que no cede',
          how: 'Siéntate con una toalla bajo el pie. Encoge los dedos para jalar la toalla hacia ti, sostén, luego suelta y vuelve a extenderla. Esto entrena los músculos largos de los dedos además de los pequeños.',
          media: 'towel_scrunch',
          caption: 'Recoger la toalla: encoge los dedos para juntar la toalla',
          alt: 'Un pie descalzo encogiendo los dedos para jalar una toalla sobre el piso',
          evidence: { level: 'early', why: 'Se usó en la mayoría de los ensayos de la revisión de 2023, normalmente junto con el ejercicio de pie corto. No se ha probado por sí solo para dolor o lesiones.' },
        },
        {
          name: 'Elevaciones de talón con dos pies',
          dose: '3\u00A0series de 10',
          often: 'Casi todas las sesiones',
          feel: 'Trabajo en las pantorrillas y en la parte delantera de los pies',
          stop: 'Dolor en el talón o el Aquiles de 6/10',
          how: 'Sostente de una pared. Sube a la parte delantera de los dos pies en unos 3\u00A0segundos y baja en 3\u00A0segundos. Intenta mantener el peso sobre el lado del dedo gordo, sin irte hacia afuera. Más en la página de [elevaciones de talón](/es/ejercicios/elevaciones-de-talon/).',
          media: 'heel_raise_double',
          caption: 'Elevaciones de talón con dos pies: sube despacio, baja despacio',
          alt: 'Una figura sosteniéndose de una pared y subiendo a la parte delantera de los dos pies',
          evidence: { level: 'moderate', why: 'Las elevaciones de talón tienen respaldo de ensayos para la fascitis plantar (Rathleff 2015). Aquí entrenan la pantorrilla, el principal músculo extrínseco del pie.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.gooding, CITE.rathleff],
    },
    {
      h2: '¿Cómo progresar de sentado a de pie y a una pierna?',
      paragraphs: [
        'Los ejercicios para fortalecer los pies progresan poniendo más peso corporal sobre el pie, un paso a la vez. El trabajo sentado enseña el movimiento. De pie sobre los dos pies agregas la mitad de tu peso corporal. De pie sobre un pie agregas todo, más el equilibrio. Sube solo cuando el paso actual se sienta fácil y controlado.',
        'Walkito usa los mismos tres pasos para el ejercicio de pie corto: sentado, luego de pie sobre los dos pies, luego a una pierna. Cuando el arco es el foco de tu plan, el siguiente plan semanal te sube un paso si calificaste como fáciles tus dos últimas sesiones con ese ejercicio y tu dolor de la mañana no ha subido. Una sesión calificada como difícil, o un dolor de la mañana 2\u00A0puntos más alto, te regresa un paso. Los dos pasos siguientes se muestran abajo.',
      ],
      bullets: [
        '**Paso 1, sentado.** Pie corto, separación de dedos, elevación del dedo gordo y recoger la toalla, todo sentado.',
        '**Paso 2, de pie sobre los dos pies.** El pie corto sostenido de pie y las elevaciones de talón con dos pies.',
        '**Paso 3, a una pierna.** El pie corto sostenido a una pierna, luego equilibrio a una pierna con el arco arriba.',
        '**Más adelante.** Elevaciones de talón a una pierna y, para corredores, saltos pequeños. Son cargas mayores. Agrégalas solo cuando el paso 3 sea fácil.',
      ],
      exercises: [
        {
          name: 'Pie corto, de pie sobre los dos pies',
          dose: '3\u00A0series de 8, sosteniendo cada una 5\u00A0segundos',
          often: 'Cuando la versión sentado sea fácil',
          feel: 'El arco sube con tu peso corporal encima',
          stop: 'Dolor de 6/10, o los dedos se siguen aferrando',
          how: 'Párate con el peso repartido entre los dos pies. Sube los arcos igual que sentado, con los dedos relajados y las rodillas ligeramente flexionadas. Sostén y relaja.',
          media: 'short_foot_double',
          caption: 'Pie corto, de pie: sube los dos arcos sin encoger los dedos',
          alt: 'Una figura de pie levantando el arco de los dos pies',
          evidence: { level: 'moderate', why: 'La progresión de sentado a de pie se usó en la mayoría de los ensayos de la revisión de 2023. No se ha probado por sí sola para dolor o lesiones.' },
        },
        {
          name: 'Pie corto, a una pierna',
          dose: '3\u00A0series de 10, sosteniendo cada una 5\u00A0segundos',
          often: 'Cuando la versión con dos pies sea fácil',
          feel: 'Todo el pie y el tobillo trabajando para mantenerte estable',
          stop: 'Dolor de 6/10, o no puedes mantener el arco arriba',
          how: 'Párate en un pie cerca de una pared. Sube el arco y mantenlo mientras te equilibras. Toca la pared si lo necesitas.',
          media: 'short_foot_single',
          caption: 'Pie corto, a una pierna: mantén el arco mientras te equilibras',
          alt: 'Una figura parada en un pie con el arco levantado y una mano cerca de una pared',
          evidence: { level: 'early', why: 'Se usa como último paso en los programas de core del pie. Hay poca investigación sobre esta variante exacta.' },
        },
        {
          name: 'Equilibrio a una pierna',
          dose: '3\u00A0series de 20\u00A0segundos, cada pierna',
          often: 'Días de equilibrio',
          feel: 'Correcciones pequeñas y constantes en el pie',
          stop: 'Dolor de 6/10, o mareo',
          how: 'Párate en un pie y mira un punto fijo delante de ti. Deja que el pie haga pequeños tambaleos. Ese es el trabajo. Párate cerca de una pared o una barra de cocina. Más en la página de [equilibrio a una pierna](/es/ejercicios/equilibrio-a-una-pierna/).',
          media: 'single_leg_hold',
          caption: 'Equilibrio a una pierna: deja que el pie haga las correcciones',
          alt: 'Una figura en equilibrio sobre una pierna junto a una pared',
          evidence: { level: 'moderate', why: 'El entrenamiento de equilibrio redujo los esguinces de tobillo en un metaanálisis (Bellows 2018). Para la fuerza del pie en sí no se ha probado por sí solo.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.bellows],
    },
    {
      h2: '¿Los ejercicios para fortalecer los pies previenen lesiones al correr?',
      keyFact: 'En un ensayo de 2020 con 118\u00A0corredores, quienes no hicieron entrenamiento de core del pie tuvieron 2,42\u00A0veces más probabilidades de lesionarse en 12\u00A0meses (Taddei y colegas).',
      paragraphs: [
        'Los ejercicios para fortalecer los pies **redujeron las lesiones al correr en un buen ensayo, pero solo en uno.** En 2020, Taddei y colegas dividieron al azar a 118\u00A0corredores recreativos de larga distancia en un grupo de core del pie (57\u00A0corredores) y un grupo control (61\u00A0corredores). El grupo de core del pie hizo un curso supervisado de unos dos meses para los músculos del pie y el tobillo, y luego siguió entrenando con supervisión a distancia.',
        'En 12\u00A0meses, el grupo control tuvo 2,42\u00A0veces más probabilidades de sufrir una lesión por correr. Los autores vieron que el efecto aparecía después de unos cuatro a ocho meses de entrenamiento.',
        'Un ensayo anterior y más pequeño del mismo equipo, con 28\u00A0corredores, encontró que unos dos meses de entrenamiento del pie aumentaron el tamaño de cada músculo del pie que midieron, en comparación con el grupo control. Los corredores además se impulsaban del piso con más fuerza.',
        'Los dos ensayos vienen de un solo grupo de investigación en Brasil, con corredores recreativos que no estaban lesionados al inicio. Todavía no sabemos si el programa ayuda a principiantes o a personas que ya tienen dolor. Si eres corredor y ya tienes dolor de talón, empieza con [dolor de talón en corredores](/es/dolor-de-talon-en-corredores/).',
      ],
      sourceNote: 'Taddei 2020 (Am J Sports Med): el grupo control tuvo 2,42\u00A0veces más probabilidades de lesionarse (IC 95\u00A0% 1,98 a 3,62), p = 0,035, ensayo aleatorizado simple ciego, seguimiento de 12\u00A0meses. Taddei 2020 (Phys Ther Sport): ensayo aleatorizado simple ciego de prueba de concepto, 28\u00A0corredores, volumen muscular por resonancia magnética.',
      cites: [CITE.taddeiRRI, CITE.taddeiMuscle],
    },
    {
      h2: '¿Cuánto tiempo se tarda en fortalecer los pies?',
      keyFact: 'En un ensayo de 2019 con 57\u00A0corredores, los músculos del pie crecieron y ganaron fuerza en unos dos meses, y algunos músculos ya eran más grandes al mes (Ridge y colegas).',
      paragraphs: [
        'En los ensayos, los músculos del pie ganaron fuerza de forma medible en **unos dos meses de entrenamiento constante**. En 2019, Ridge y colegas asignaron al azar a 57\u00A0corredores a:',
        {
          list: [
            'Ejercicios para fortalecer el pie.',
            'Caminar con zapatos minimalistas.',
            'No cambiar nada.',
          ],
        },
        'El grupo de ejercicio hizo ejercicios de resistencia progresiva al menos cinco veces por semana. Después de unos dos meses, cada músculo del pie que midieron era más grande y más fuerte en los dos grupos activos, sin cambios en el grupo control. Algunos músculos ya eran más grandes en la revisión del primer mes.',
        'La forma del arco cambia más despacio y menos. Una revisión de 2023 de cuatro ensayos encontró que el fortalecimiento intrínseco del pie no cambió cuánto se mueve el arco después de un mes, pero sí después de dos meses, con evidencia de baja calidad.',
        'En un estudio pequeño de Mulligan y Cook con 21\u00A0personas y sin grupo control, la caída del navicular (cuánto se hunde el arco interno al pararte) bajó en promedio 1,8\u00A0mm después de un mes de entrenamiento de pie corto. Es un cambio real, pero pequeño.',
      ],
      cites: [CITE.ridgeMinimalist, CITE.deSouzaIFM, CITE.mulliganCook],
    },
    {
      h2: '¿Los zapatos barefoot o minimalistas fortalecen los pies?',
      paragraphs: [
        'En un ensayo, caminar con zapatos minimalistas fortaleció los músculos del pie más o menos igual que los ejercicios. En el mismo estudio de 2019 de Ridge y colegas, los corredores que aumentaron poco a poco el número de pasos diarios con zapatos minimalistas ganaron tamaño y fuerza muscular parecidos a los del grupo de ejercicio en unos dos meses. Los autores sugirieron que cambiar de zapatos podría ser más fácil de mantener que hacer ejercicios.',
        'Cambiar demasiado rápido tiene sus propios riesgos, sobre todo para correr. La guía de [zapatos barefoot](/es/zapatos-barefoot/) explica cómo hacer el cambio y quién debe tener cuidado.',
      ],
      cites: [CITE.ridgeMinimalist],
    },
    {
      h2: '¿Los adultos mayores pueden fortalecer los pies?',
      keyFact: 'En un ensayo de 2016 con adultos de 60 a 90\u00A0años, el entrenamiento progresivo y supervisado del pie aumentó la fuerza de los dedos hasta un 36\u00A0por ciento, mientras que un programa en casa no la cambió (Mickle y colegas).',
      paragraphs: [
        'Los adultos mayores sí pueden fortalecer los pies, y en un ensayo la versión supervisada con cargas cada vez más pesadas fue la que funcionó. En un ensayo de 2016, Mickle y colegas asignaron a 85\u00A0personas de 60 a 90\u00A0años a una clase supervisada con ejercicios para el pie cada vez más pesados o a un programa de ejercicio en casa, más un grupo aparte de 32\u00A0controles.',
        'Después de tres meses, el grupo supervisado aumentó la fuerza de los dedos hasta un 36\u00A0por ciento y aguantó más tiempo parado en una pierna. El grupo en casa y el grupo control no mostraron cambios en la fuerza de los dedos.',
        'Una revisión de 2022 de nueve estudios en adultos de 65\u00A0años o más encontró que el fortalecimiento intrínseco del pie ayudó a la fuerza, el equilibrio y la movilidad, y posiblemente redujo el riesgo de caídas, con poco efecto en el patrón de marcha. Los autores calificaron la calidad de la evidencia como regular.',
        'Así que sube a versiones más difíciles cuando se vuelvan fáciles, y **ten cerca una pared o una barra de cocina para el trabajo de equilibrio.** Si las caídas te preocupan, un fisioterapeuta puede armar un programa seguro.',
      ],
      cites: [CITE.mickleToe, CITE.futrellOlder],
    },
    {
      h2: '¿Fortalecer los pies ayuda con la fascitis plantar o el pie plano?',
      paragraphs: [
        'Para la fascitis plantar, sumar fortalecimiento del pie al estiramiento no funcionó mejor que el estiramiento solo en un ensayo que los comparó. En 2016, Kamonseki y colegas dividieron a 83\u00A0personas con fascitis plantar en tres grupos durante dos meses:',
        {
          list: [
            'Fortalecimiento del pie más estiramiento.',
            'Fortalecimiento del pie y la cadera más estiramiento.',
            'Solo estiramiento.',
          ],
        },
        'Los tres grupos mejoraron en dolor y función, y ningún grupo superó a los demás. Para el dolor de talón, mira [ejercicios para la fascitis plantar](/es/ejercicios-fascitis-plantar/).',
        'Para el pie plano flexible, un ensayo de 2023 con 52\u00A0personas encontró que un programa mixto que incluía el ejercicio de pie corto cambió la forma del arco más que en el grupo control. Los detalles, y los límites del entrenamiento de pie corto por sí solo, están en la página de [ejercicios para pie plano](/es/ejercicios-pie-plano/). Si tu dolor está sobre todo en los dedos, la guía de [ejercicios para fortalecer los dedos de los pies](/es/ejercicios-para-fortalecer-los-dedos-del-pie/) profundiza más, y para el tobillo está [ejercicios para fortalecer el tobillo](/es/ejercicios-para-fortalecer-el-tobillo/).',
      ],
      cites: [CITE.kamonseki, CITE.brijwasi],
    },
    {
      h2: '¿Qué tan sólida es la evidencia sobre fortalecer los pies?',
      paragraphs: [
        'La evidencia de que los ejercicios para el pie fortalecen sus músculos apunta en la misma dirección, pero los estudios son pequeños. Una revisión de 2025 de Peters-Dickie y colegas incluyó 28\u00A0ensayos aleatorizados con 1399\u00A0personas. Respaldó los ejercicios para el pie para aumentar la fuerza del pie, pero calificó la certeza de baja a muy baja, sobre todo porque había pocos estudios por pregunta y muchos tenían alto riesgo de sesgo. Los resultados sobre el tamaño muscular fueron mixtos.',
        'La evidencia de que unos pies más fuertes signifiquen menos lesiones es todavía más escasa y se apoya sobre todo en el ensayo con corredores de arriba. **Fortalecer los pies es de bajo riesgo y barato, y sí da fuerza.** Si previene tu próxima lesión sigue sin saberse. Más sobre cómo estas guías califican la investigación en la página de [evidencia](/es/evidencia/).',
      ],
      sourceNote: 'Peters-Dickie 2025: los metaanálisis mostraron que los zapatos minimalistas aumentaron la fuerza de los dedos 2 a 5, y que los ejercicios para el pie redujeron el movimiento del arco al correr; certeza de baja a muy baja.',
      cites: [CITE.petersDickie],
    },
  ],
  faq: [
    {
      q: '¿Con qué frecuencia hacer ejercicios para fortalecer los pies?',
      cites: [CITE.ridgeMinimalist],
      a: 'La mayoría de los programas de la investigación se hicieron varias veces por semana. En un ensayo de 2019, los corredores hicieron ejercicios progresivos para el pie al menos cinco veces por semana y ganaron tamaño y fuerza muscular en unos dos meses. Una sesión corta casi todos los días es un comienzo razonable. Los músculos necesitan algo de recuperación, así que si amaneces con los pies adoloridos, haz un día más ligero.',
    },
    {
      q: '¿Es mejor recoger la toalla o el ejercicio de pie corto?',
      cites: [CITE.jung, CITE.lynn],
      a: 'El ejercicio de pie corto trabaja más directamente los músculos del arco. En un estudio de laboratorio con 20\u00A0personas, el principal músculo del arco interno estuvo claramente más activo durante el pie corto que al recoger la toalla (Jung 2011). En un ensayo pequeño con 24\u00A0personas, un mes de entrenamiento de pie corto mejoró una prueba de equilibrio más que recoger la toalla (Lynn 2012). Recoger la toalla sigue siendo un primer paso útil y fácil.',
    },
    {
      q: '¿Deben doler los ejercicios para fortalecer los pies?',
      a: 'No. Debes sentir esfuerzo, y quizá un calambre leve bajo el arco al principio, que cede cuando relajas. Un dolor agudo o un dolor de 6/10 o más significa que debes parar por el día. Si el mismo punto duele cada vez, o el dolor no te deja dormir, consulta a un profesional de la salud antes de seguir.',
    },
    {
      q: '¿Caminar descalzo basta para fortalecer los pies?',
      cites: [CITE.ridgeMinimalist],
      a: 'Puede ayudar. En un ensayo de 2019, los corredores que aumentaron poco a poco los pasos diarios con zapatos minimalistas ganaron una fuerza en el pie parecida a la de un grupo de ejercicio en unos dos meses. Fue un cambio gradual, no repentino. Andar descalzo demasiado rápido puede sobrecargar el pie, así que aumenta poco a poco y sigue con los ejercicios si te gustan.',
    },
    {
      q: '¿Fortalecer los pies puede levantar un arco plano?',
      cites: [CITE.mulliganCook, CITE.cheng],
      a: 'Solo un poco, y solo en el pie plano flexible. En un estudio pequeño con 21\u00A0personas sin dolor de pie y sin grupo control, el arco se hundió 1,8\u00A0mm menos después de un mes de entrenamiento de pie corto. Una revisión de 2024 encontró que los programas de pie corto cambiaron las medidas del arco solo cuando duraron más tiempo. Espera un pie más fuerte y estable, no una nueva forma de arco.',
    },
    {
      q: '¿Se necesita equipo para fortalecer los pies?',
      a: 'No. Los ejercicios de esta página solo necesitan piso, una silla, una toalla y una pared para sostenerte en el equilibrio. Hazlos descalzo para ver y sentir cómo se mueve el pie. Más adelante puedes agregar carga con elevaciones de talón a una pierna o una mochila, pero el peso corporal alcanza por mucho tiempo.',
    },
  ],
  redFlags: {
    h2: 'Consulta primero a un profesional de la salud si',
    bullets: [
      'tienes entumecimiento, hormigueo o ardor en los pies, o tienes diabetes y cualquier herida o llaga en la piel',
      'un pie se está debilitando, o la parte delantera del pie se arrastra o golpea el piso al caminar',
      'un arco se está aplanando rápido o la parte interna del tobillo está hinchada y adolorida',
      'el dolor está en un punto de un hueso y empeora con cada caminata o carrera, lo que puede ser una fractura por estrés',
      'el pie está rojo, caliente o hinchado, o tienes fiebre',
      'no puedes apoyar peso en el pie',
      'el dolor sigue empeorando a pesar del reposo y de ejercicios más suaves',
    ],
  },
  program: {
    h2: 'Hacerlo como un plan',
    text: 'Walkito arma un plan semanal en torno a una meta e incluye los ejercicios para el pie de esta página: el ejercicio de pie corto de sentado a una pierna, la separación de dedos, la elevación del dedo gordo, recoger la toalla, las elevaciones de talón y el trabajo de equilibrio. Empieza los ejercicios de arco con 3\u00A0series de 8 sosteniendo 5\u00A0segundos y el equilibrio con 3\u00A0series de 20\u00A0segundos, y en cada nuevo plan semanal sube un paso tu ejercicio principal cuando calificaste como fáciles tus dos últimas sesiones con él y tu dolor de la mañana no ha subido.',
    more: [
      'Eliges sesiones de 3, 5 o 10\u00A0minutos. Al principio cada 14\u00A0días, una prueba corta revisa la resistencia de la pantorrilla, cuánto mantienes el arco y el equilibrio, para que veas qué está cambiando. Walkito es un programa de ejercicios para adultos. No diagnostica y no reemplaza a un profesional de la salud.',
    ],
    cta: 'Empieza con 3\u00A0minutos al día.',
  },
  crumb: 'Fortalecer los pies',
  campaign: 'guide-foot-strength-es',
};
