import type { EnglishPage, NewLang } from '@/lib/i18n';

import { ACHILLES_PT } from './articles-pt/achilles';
import { BEST_APP_PT } from './articles-pt/best-app';
import { CALF_RAISES_PT } from './articles-pt/calf-raises';
import { EX_CALF_STRETCH_PT } from './articles-pt/ex-calf-stretch';
import { EX_PLANTAR_FASCIA_STRETCH_PT } from './articles-pt/ex-plantar-fascia-stretch';
import { EX_SHORT_FOOT_PT } from './articles-pt/ex-short-foot';
import { EX_TOWEL_HEEL_RAISE_PT } from './articles-pt/ex-towel-heel-raise';
import { HEEL_SPUR_EXERCISES_PT } from './articles-pt/heel-spur-exercises';
import { HUB_FLAT_FEET_PT } from './articles-pt/hub-flat-feet';
import { HUB_PLANTAR_FASCIITIS_PT } from './articles-pt/hub-plantar-fasciitis';
import { MORNING_HEEL_PAIN_PT } from './articles-pt/morning-heel-pain';
import { PF_DURATION_PT } from './articles-pt/pf-duration';
import { PF_VS_HEEL_SPUR_PT } from './articles-pt/pf-vs-heel-spur';
import { SHIN_SPLINTS_PT } from './articles-pt/shin-splints';
import { ACHILLES_FR } from './articles-fr/achilles';
import { BEST_APP_FR } from './articles-fr/best-app';
import { CALF_RAISES_FR } from './articles-fr/calf-raises';
import { EX_CALF_STRETCH_FR } from './articles-fr/ex-calf-stretch';
import { EX_PLANTAR_FASCIA_STRETCH_FR } from './articles-fr/ex-plantar-fascia-stretch';
import { EX_SHORT_FOOT_FR } from './articles-fr/ex-short-foot';
import { EX_TOWEL_HEEL_RAISE_FR } from './articles-fr/ex-towel-heel-raise';
import { HEEL_SPUR_EXERCISES_FR } from './articles-fr/heel-spur-exercises';
import { HUB_FLAT_FEET_FR } from './articles-fr/hub-flat-feet';
import { HUB_PLANTAR_FASCIITIS_FR } from './articles-fr/hub-plantar-fasciitis';
import { MORNING_HEEL_PAIN_FR } from './articles-fr/morning-heel-pain';
import { PF_DURATION_FR } from './articles-fr/pf-duration';
import { PF_VS_HEEL_SPUR_FR } from './articles-fr/pf-vs-heel-spur';
import { SHIN_SPLINTS_FR } from './articles-fr/shin-splints';
import { ACHILLES_IT } from './articles-it/achilles';
import { BEST_APP_IT } from './articles-it/best-app';
import { CALF_RAISES_IT } from './articles-it/calf-raises';
import { EX_CALF_STRETCH_IT } from './articles-it/ex-calf-stretch';
import { EX_PLANTAR_FASCIA_STRETCH_IT } from './articles-it/ex-plantar-fascia-stretch';
import { EX_SHORT_FOOT_IT } from './articles-it/ex-short-foot';
import { EX_TOWEL_HEEL_RAISE_IT } from './articles-it/ex-towel-heel-raise';
import { HEEL_SPUR_EXERCISES_IT } from './articles-it/heel-spur-exercises';
import { HUB_FLAT_FEET_IT } from './articles-it/hub-flat-feet';
import { HUB_PLANTAR_FASCIITIS_IT } from './articles-it/hub-plantar-fasciitis';
import { MORNING_HEEL_PAIN_IT } from './articles-it/morning-heel-pain';
import { PF_DURATION_IT } from './articles-it/pf-duration';
import { PF_VS_HEEL_SPUR_IT } from './articles-it/pf-vs-heel-spur';
import { SHIN_SPLINTS_IT } from './articles-it/shin-splints';
import { ACHILLES_DE } from './articles-de/achilles';
import { BEST_APP_DE } from './articles-de/best-app';
import { CALF_RAISES_DE } from './articles-de/calf-raises';
import { EX_CALF_STRETCH_DE } from './articles-de/ex-calf-stretch';
import { EX_PLANTAR_FASCIA_STRETCH_DE } from './articles-de/ex-plantar-fascia-stretch';
import { EX_SHORT_FOOT_DE } from './articles-de/ex-short-foot';
import { EX_TOWEL_HEEL_RAISE_DE } from './articles-de/ex-towel-heel-raise';
import { HEEL_SPUR_EXERCISES_DE } from './articles-de/heel-spur-exercises';
import { HUB_FLAT_FEET_DE } from './articles-de/hub-flat-feet';
import { HUB_PLANTAR_FASCIITIS_DE } from './articles-de/hub-plantar-fasciitis';
import { MORNING_HEEL_PAIN_DE } from './articles-de/morning-heel-pain';
import { PF_DURATION_DE } from './articles-de/pf-duration';
import { PF_VS_HEEL_SPUR_DE } from './articles-de/pf-vs-heel-spur';
import { SHIN_SPLINTS_DE } from './articles-de/shin-splints';
import type { Guide } from './types';

/** Articles in Portuguese, French, Italian and German, keyed by language and page.
 * Generated by `scripts/gen-articles-new.py`. */
export const ARTICLES_NEW: Record<NewLang, Partial<Record<EnglishPage, Guide>>> = {
  pt: {
    achilles: ACHILLES_PT,
    bestApp: BEST_APP_PT,
    calfRaises: CALF_RAISES_PT,
    exCalfStretch: EX_CALF_STRETCH_PT,
    exPlantarFasciaStretch: EX_PLANTAR_FASCIA_STRETCH_PT,
    exShortFoot: EX_SHORT_FOOT_PT,
    exTowelHeelRaise: EX_TOWEL_HEEL_RAISE_PT,
    heelSpurExercises: HEEL_SPUR_EXERCISES_PT,
    hubFlatFeet: HUB_FLAT_FEET_PT,
    hubPlantarFasciitis: HUB_PLANTAR_FASCIITIS_PT,
    morningHeelPain: MORNING_HEEL_PAIN_PT,
    pfDuration: PF_DURATION_PT,
    pfVsHeelSpur: PF_VS_HEEL_SPUR_PT,
    shinSplints: SHIN_SPLINTS_PT,
  },
  fr: {
    achilles: ACHILLES_FR,
    bestApp: BEST_APP_FR,
    calfRaises: CALF_RAISES_FR,
    exCalfStretch: EX_CALF_STRETCH_FR,
    exPlantarFasciaStretch: EX_PLANTAR_FASCIA_STRETCH_FR,
    exShortFoot: EX_SHORT_FOOT_FR,
    exTowelHeelRaise: EX_TOWEL_HEEL_RAISE_FR,
    heelSpurExercises: HEEL_SPUR_EXERCISES_FR,
    hubFlatFeet: HUB_FLAT_FEET_FR,
    hubPlantarFasciitis: HUB_PLANTAR_FASCIITIS_FR,
    morningHeelPain: MORNING_HEEL_PAIN_FR,
    pfDuration: PF_DURATION_FR,
    pfVsHeelSpur: PF_VS_HEEL_SPUR_FR,
    shinSplints: SHIN_SPLINTS_FR,
  },
  it: {
    achilles: ACHILLES_IT,
    bestApp: BEST_APP_IT,
    calfRaises: CALF_RAISES_IT,
    exCalfStretch: EX_CALF_STRETCH_IT,
    exPlantarFasciaStretch: EX_PLANTAR_FASCIA_STRETCH_IT,
    exShortFoot: EX_SHORT_FOOT_IT,
    exTowelHeelRaise: EX_TOWEL_HEEL_RAISE_IT,
    heelSpurExercises: HEEL_SPUR_EXERCISES_IT,
    hubFlatFeet: HUB_FLAT_FEET_IT,
    hubPlantarFasciitis: HUB_PLANTAR_FASCIITIS_IT,
    morningHeelPain: MORNING_HEEL_PAIN_IT,
    pfDuration: PF_DURATION_IT,
    pfVsHeelSpur: PF_VS_HEEL_SPUR_IT,
    shinSplints: SHIN_SPLINTS_IT,
  },
  de: {
    achilles: ACHILLES_DE,
    bestApp: BEST_APP_DE,
    calfRaises: CALF_RAISES_DE,
    exCalfStretch: EX_CALF_STRETCH_DE,
    exPlantarFasciaStretch: EX_PLANTAR_FASCIA_STRETCH_DE,
    exShortFoot: EX_SHORT_FOOT_DE,
    exTowelHeelRaise: EX_TOWEL_HEEL_RAISE_DE,
    heelSpurExercises: HEEL_SPUR_EXERCISES_DE,
    hubFlatFeet: HUB_FLAT_FEET_DE,
    hubPlantarFasciitis: HUB_PLANTAR_FASCIITIS_DE,
    morningHeelPain: MORNING_HEEL_PAIN_DE,
    pfDuration: PF_DURATION_DE,
    pfVsHeelSpur: PF_VS_HEEL_SPUR_DE,
    shinSplints: SHIN_SPLINTS_DE,
  },
};
