import type { EnglishPage } from '@/lib/i18n';

import { TIGHT_CALVES_ES } from './articles-es/tight-calves';
import { FLAT_FEET_KIDS_ES } from './articles-es/flat-feet-in-kids';
import { FLAT_FEET_BACK_PAIN_ES } from './articles-es/flat-feet-back-pain';
import { BAREFOOT_ES } from './articles-es/barefoot-shoes';
import { FOOT_STRENGTHENING_ES } from './articles-es/foot-strengthening-exercises';
import { ANKLE_MOBILITY_ES } from './articles-es/ankle-mobility-exercises';
import { ICE_HEAT_ES } from './articles-es/ice-or-heat-for-plantar-fasciitis';
import { FLAT_FEET_AGE_ES } from './articles-es/do-flat-feet-get-worse-with-age';
import { ANKLE_STRENGTHENING_ES } from './articles-es/ankle-strengthening-exercises';
import { NIGHT_SPLINTS_ES } from './articles-es/night-splints-plantar-fasciitis';
import { INSOLES_VS_EXERCISES_ES } from './articles-es/insoles-vs-exercises';
import { TOE_STRENGTHENING_ES } from './articles-es/toe-strengthening-exercises';
import { MASSAGE_BALL_ES } from './articles-es/massage-ball-plantar-fasciitis';
import { FLAT_FEET_KNEE_PAIN_ES } from './articles-es/flat-feet-knee-pain';
import { PF_TAPING_ES } from './articles-es/plantar-fasciitis-taping';
import { ACHILLES_ES } from './articles-es/achilles';
import { ARCH_PAIN_ES } from './articles-es/arch-pain';
import { BALL_OF_FOOT_ES } from './articles-es/ball-of-foot';
import { BEST_APP_ES } from './articles-es/best-app';
import { BUNIONS_ES } from './articles-es/bunions';
import { CALF_RAISE_TEST_ES } from './articles-es/calf-raise-test';
import { CALF_RAISES_ES } from './articles-es/calf-raises';
import { EX_ANKLE_ROCKS_ES } from './articles-es/ex-ankle-rocks';
import { EX_BAND_INVERSION_ES } from './articles-es/ex-band-inversion';
import { EX_BIG_TOE_LIFT_ES } from './articles-es/ex-big-toe-lift';
import { EX_CALF_RAISES_ES } from './articles-es/ex-calf-raises';
import { EX_CALF_STRETCH_ES } from './articles-es/ex-calf-stretch';
import { EX_ECCENTRIC_HEEL_DROPS_ES } from './articles-es/ex-eccentric-heel-drops';
import { EX_FOOT_ROLL_ES } from './articles-es/ex-foot-roll';
import { EX_HIP_ABDUCTION_ES } from './articles-es/ex-hip-abduction';
import { EX_PLANTAR_FASCIA_STRETCH_ES } from './articles-es/ex-plantar-fascia-stretch';
import { EX_SHORT_FOOT_ES } from './articles-es/ex-short-foot';
import { EX_SINGLE_LEG_BALANCE_ES } from './articles-es/ex-single-leg-balance';
import { EX_SOLEUS_STRETCH_ES } from './articles-es/ex-soleus-stretch';
import { EX_TIBIALIS_RAISES_ES } from './articles-es/ex-tibialis-raises';
import { EX_TOE_SPREAD_ES } from './articles-es/ex-toe-spread';
import { EX_TOWEL_HEEL_RAISE_ES } from './articles-es/ex-towel-heel-raise';
import { EX_TOWEL_SCRUNCH_ES } from './articles-es/ex-towel-scrunch';
import { HAGLUNDS_ES } from './articles-es/haglunds';
import { HAMMER_TOE_ES } from './articles-es/hammer-toe';
import { HEEL_FAT_PAD_ES } from './articles-es/heel-fat-pad';
import { HEEL_PAIN_AFTER_WALKING_ES } from './articles-es/heel-pain-after-walking';
import { HEEL_PAIN_AT_NIGHT_ES } from './articles-es/heel-pain-at-night';
import { HEEL_SPUR_EXERCISES_ES } from './articles-es/heel-spur-exercises';
import { HIGH_ARCHES_ES } from './articles-es/high-arches';
import { HUB_FLAT_FEET_ES } from './articles-es/hub-flat-feet';
import { HUB_PLANTAR_FASCIITIS_ES } from './articles-es/hub-plantar-fasciitis';
import { MORNING_HEEL_PAIN_ES } from './articles-es/morning-heel-pain';
import { MORTONS_ES } from './articles-es/mortons';
import { NURSES_ES } from './articles-es/nurses';
import { PF_DURATION_ES } from './articles-es/pf-duration';
import { PF_VS_HEEL_SPUR_ES } from './articles-es/pf-vs-heel-spur';
import { PTTD_ES } from './articles-es/pttd';
import { SESAMOIDITIS_ES } from './articles-es/sesamoiditis';
import { SEVERS_ES } from './articles-es/severs';
import { SHIN_SPLINTS_ES } from './articles-es/shin-splints';
import { STANDING_DESK_ES } from './articles-es/standing-desk';
import { STANDING_ES } from './articles-es/standing';
import { TOP_OF_FOOT_ES } from './articles-es/top-of-foot';
import { VS_EXAKT_ES } from './articles-es/vs-exakt';
import type { Guide } from './types';

/** Spanish versions of the English-only articles, keyed by page. Generated by
 * `scripts/gen-articles-es.py` from the files in `articles-es/`. */
export const ARTICLES_ES: Partial<Record<EnglishPage, Guide>> = {
  achilles: ACHILLES_ES,
  archPain: ARCH_PAIN_ES,
  ballOfFoot: BALL_OF_FOOT_ES,
  bestApp: BEST_APP_ES,
  bunions: BUNIONS_ES,
  calfRaiseTest: CALF_RAISE_TEST_ES,
  calfRaises: CALF_RAISES_ES,
  exAnkleRocks: EX_ANKLE_ROCKS_ES,
  exBandInversion: EX_BAND_INVERSION_ES,
  exBigToeLift: EX_BIG_TOE_LIFT_ES,
  exCalfRaises: EX_CALF_RAISES_ES,
  exCalfStretch: EX_CALF_STRETCH_ES,
  exEccentricHeelDrops: EX_ECCENTRIC_HEEL_DROPS_ES,
  exFootRoll: EX_FOOT_ROLL_ES,
  exHipAbduction: EX_HIP_ABDUCTION_ES,
  exPlantarFasciaStretch: EX_PLANTAR_FASCIA_STRETCH_ES,
  exShortFoot: EX_SHORT_FOOT_ES,
  exSingleLegBalance: EX_SINGLE_LEG_BALANCE_ES,
  exSoleusStretch: EX_SOLEUS_STRETCH_ES,
  exTibialisRaises: EX_TIBIALIS_RAISES_ES,
  exToeSpread: EX_TOE_SPREAD_ES,
  exTowelHeelRaise: EX_TOWEL_HEEL_RAISE_ES,
  exTowelScrunch: EX_TOWEL_SCRUNCH_ES,
  haglunds: HAGLUNDS_ES,
  hammerToe: HAMMER_TOE_ES,
  heelFatPad: HEEL_FAT_PAD_ES,
  heelPainAfterWalking: HEEL_PAIN_AFTER_WALKING_ES,
  heelPainAtNight: HEEL_PAIN_AT_NIGHT_ES,
  heelSpurExercises: HEEL_SPUR_EXERCISES_ES,
  highArches: HIGH_ARCHES_ES,
  hubFlatFeet: HUB_FLAT_FEET_ES,
  hubPlantarFasciitis: HUB_PLANTAR_FASCIITIS_ES,
  morningHeelPain: MORNING_HEEL_PAIN_ES,
  mortons: MORTONS_ES,
  nurses: NURSES_ES,
  pfDuration: PF_DURATION_ES,
  pfVsHeelSpur: PF_VS_HEEL_SPUR_ES,
  pttd: PTTD_ES,
  sesamoiditis: SESAMOIDITIS_ES,
  severs: SEVERS_ES,
  shinSplints: SHIN_SPLINTS_ES,
  standingDesk: STANDING_DESK_ES,
  standing: STANDING_ES,
  topOfFoot: TOP_OF_FOOT_ES,
  vsExakt: VS_EXAKT_ES,
  pfTaping: PF_TAPING_ES,
  flatFeetKneePain: FLAT_FEET_KNEE_PAIN_ES,
  massageBall: MASSAGE_BALL_ES,
  toeStrengthening: TOE_STRENGTHENING_ES,
  insolesVsExercises: INSOLES_VS_EXERCISES_ES,
  nightSplints: NIGHT_SPLINTS_ES,
  ankleStrengthening: ANKLE_STRENGTHENING_ES,
  flatFeetAge: FLAT_FEET_AGE_ES,
  iceHeat: ICE_HEAT_ES,
  ankleMobility: ANKLE_MOBILITY_ES,
  footStrengthening: FOOT_STRENGTHENING_ES,
  barefoot: BAREFOOT_ES,
  flatFeetBackPain: FLAT_FEET_BACK_PAIN_ES,
  flatFeetKids: FLAT_FEET_KIDS_ES,
  tightCalves: TIGHT_CALVES_ES,
};
