import type { EnglishPage } from '@/lib/i18n';

import { ACHILLES_ES } from './articles-es/achilles';
import { BALL_OF_FOOT_ES } from './articles-es/ball-of-foot';
import { BEST_APP_ES } from './articles-es/best-app';
import { CALF_RAISE_TEST_ES } from './articles-es/calf-raise-test';
import { CALF_RAISES_ES } from './articles-es/calf-raises';
import { EX_ANKLE_ROCKS_ES } from './articles-es/ex-ankle-rocks';
import { EX_BAND_INVERSION_ES } from './articles-es/ex-band-inversion';
import { EX_BIG_TOE_LIFT_ES } from './articles-es/ex-big-toe-lift';
import { EX_CALF_RAISES_ES } from './articles-es/ex-calf-raises';
import { EX_CALF_STRETCH_ES } from './articles-es/ex-calf-stretch';
import { EX_ECCENTRIC_HEEL_DROPS_ES } from './articles-es/ex-eccentric-heel-drops';
import { EX_FOOT_ROLL_ES } from './articles-es/ex-foot-roll';
import { EX_HIP_ABDUCTION_ES } from './articles-es/ex-hip-abduction';
import { EX_PLANTAR_FASCIA_STRETCH_ES } from './articles-es/ex-plantar-fascia-stretch';
import { EX_SHORT_FOOT_ES } from './articles-es/ex-short-foot';
import { EX_SINGLE_LEG_BALANCE_ES } from './articles-es/ex-single-leg-balance';
import { EX_SOLEUS_STRETCH_ES } from './articles-es/ex-soleus-stretch';
import { EX_TIBIALIS_RAISES_ES } from './articles-es/ex-tibialis-raises';
import { EX_TOE_SPREAD_ES } from './articles-es/ex-toe-spread';
import { EX_TOWEL_HEEL_RAISE_ES } from './articles-es/ex-towel-heel-raise';
import { EX_TOWEL_SCRUNCH_ES } from './articles-es/ex-towel-scrunch';
import { HUB_FLAT_FEET_ES } from './articles-es/hub-flat-feet';
import { HUB_PLANTAR_FASCIITIS_ES } from './articles-es/hub-plantar-fasciitis';
import { MORNING_HEEL_PAIN_ES } from './articles-es/morning-heel-pain';
import { NURSES_ES } from './articles-es/nurses';
import { PF_DURATION_ES } from './articles-es/pf-duration';
import { SHIN_SPLINTS_ES } from './articles-es/shin-splints';
import { STANDING_DESK_ES } from './articles-es/standing-desk';
import { STANDING_ES } from './articles-es/standing';
import { VS_EXAKT_ES } from './articles-es/vs-exakt';
import type { Guide } from './types';

/** Spanish versions of the English-only articles, keyed by page. Generated by
 * `scripts/gen-articles-es.py` from the files in `articles-es/`. */
export const ARTICLES_ES: Partial<Record<EnglishPage, Guide>> = {
  achilles: ACHILLES_ES,
  ballOfFoot: BALL_OF_FOOT_ES,
  bestApp: BEST_APP_ES,
  calfRaiseTest: CALF_RAISE_TEST_ES,
  calfRaises: CALF_RAISES_ES,
  exAnkleRocks: EX_ANKLE_ROCKS_ES,
  exBandInversion: EX_BAND_INVERSION_ES,
  exBigToeLift: EX_BIG_TOE_LIFT_ES,
  exCalfRaises: EX_CALF_RAISES_ES,
  exCalfStretch: EX_CALF_STRETCH_ES,
  exEccentricHeelDrops: EX_ECCENTRIC_HEEL_DROPS_ES,
  exFootRoll: EX_FOOT_ROLL_ES,
  exHipAbduction: EX_HIP_ABDUCTION_ES,
  exPlantarFasciaStretch: EX_PLANTAR_FASCIA_STRETCH_ES,
  exShortFoot: EX_SHORT_FOOT_ES,
  exSingleLegBalance: EX_SINGLE_LEG_BALANCE_ES,
  exSoleusStretch: EX_SOLEUS_STRETCH_ES,
  exTibialisRaises: EX_TIBIALIS_RAISES_ES,
  exToeSpread: EX_TOE_SPREAD_ES,
  exTowelHeelRaise: EX_TOWEL_HEEL_RAISE_ES,
  exTowelScrunch: EX_TOWEL_SCRUNCH_ES,
  hubFlatFeet: HUB_FLAT_FEET_ES,
  hubPlantarFasciitis: HUB_PLANTAR_FASCIITIS_ES,
  morningHeelPain: MORNING_HEEL_PAIN_ES,
  nurses: NURSES_ES,
  pfDuration: PF_DURATION_ES,
  shinSplints: SHIN_SPLINTS_ES,
  standingDesk: STANDING_DESK_ES,
  standing: STANDING_ES,
  vsExakt: VS_EXAKT_ES,
};
