/**
 * Builds the assistant into dist/: one self-contained `server.mjs` (no
 * node_modules on the server) with the widget HTML inlined.
 *
 *   bun run build
 *
 * 1. tokens.css from the app's theme (src/shared/config/theme.ts) and the
 *    site's radii (site/app/globals.css), so a change in the app's theme
 *    re-exports here rather than being copied by hand.
 * 2. The widget: main.ts bundled to one script, inlined with the CSS into
 *    one HTML string.
 * 3. The server, bundled with the app's program modules from ../src. Two of
 *    them reach React Native through one import each; those two imports point
 *    at src/shims (see the files there).
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

import { build, type Plugin } from 'esbuild';

import { accents, meterColors, palette, primaryButton, PRIMARY } from '../../src/shared/config/theme';

const ROOT = resolve(import.meta.dir, '..');
const APP = resolve(ROOT, '..');
const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8')) as { version: string };

// ─── 1. tokens.css ──────────────────────────────────────────────────────────

const css = readFileSync(join(APP, 'site/app/globals.css'), 'utf8');
const radius = (name: string) => {
  const m = new RegExp(`--radius-${name}:\\s*([^;]+);`).exec(css);
  if (!m) throw new Error(`build: --radius-${name} not found in site/app/globals.css`);
  return m[1].trim();
};

function scheme(mode: 'light' | 'dark') {
  const p = palette[mode];
  const m = meterColors[mode];
  const a = accents[mode];
  const b = primaryButton[mode];
  return [
    `--w-bg: ${p.background};`,
    `--w-ink: ${p.foreground};`,
    `--w-card: ${p.card};`,
    `--w-caption: ${m.caption};`,
    `--w-label: ${m.label};`,
    `--w-unit: ${m.unit};`,
    `--w-divider: ${m.divider};`,
    `--w-track: ${m.track};`,
    `--w-icon-tile: ${m.iconTile};`,
    `--w-glass: ${m.glassTint};`,
    `--w-focus: ${m.focus};`,
    `--w-focus-bg: ${m.focusBg};`,
    `--w-button: ${b.fill};`,
    `--w-button-label: ${b.label};`,
    `--w-violet: ${a.violet.fill};`,
    `--w-teal: ${a.teal.fill};`,
    `--w-teal-track: ${a.teal.track};`,
    `--w-blue: ${a.blue.fill};`,
    `--w-amber: ${a.amber.fill};`,
  ].join('\n  ');
}

const tokens = `/* Generated by scripts/build.ts from src/shared/config/theme.ts and
   site/app/globals.css. Do not edit; change the app's theme and rebuild. */
:root {
  --w-font: ui-rounded, -apple-system, "SF Pro Rounded", system-ui, "Nunito", sans-serif;
  --w-primary: ${PRIMARY};
  --w-radius-button: ${radius('button')};
  --w-radius-panel: ${radius('panel')};
  --w-radius-item: ${radius('item')};
  color-scheme: dark;
  ${scheme('dark')}
}
:root[data-theme='light'] {
  color-scheme: light;
  ${scheme('light')}
}
`;
writeFileSync(join(ROOT, 'src/widget/tokens.css'), tokens);

// ─── 2. The widget ──────────────────────────────────────────────────────────

const widgetJs = await build({
  entryPoints: [join(ROOT, 'src/widget/main.ts')],
  bundle: true,
  format: 'iife',
  minify: true,
  write: false,
  target: 'es2020',
  platform: 'browser',
  legalComments: 'none',
  tsconfigRaw: {},
});
const script = widgetJs.outputFiles[0].text.replace(/<\/script/gi, '<\\/script');
const widgetHtml = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><style>${tokens}${readFileSync(join(ROOT, 'src/widget/widget.css'), 'utf8')}</style></head><body><main id="root" aria-live="polite"></main><script>${script}</script></body></html>`;
mkdirSync(join(ROOT, 'dist'), { recursive: true });
writeFileSync(join(ROOT, 'dist/widget.html'), widgetHtml);

// ─── 3. The server ──────────────────────────────────────────────────────────

const PLAN_DIR = join(APP, 'src/entities/program/model/plan');
const shims: Plugin = {
  name: 'walkito-shims',
  setup(b) {
    b.onResolve({ filter: /^\.\.\/(state|exercises)$/ }, (args) =>
      dirname(args.importer) === PLAN_DIR
        ? { path: join(ROOT, `src/shims/${args.path.slice(3)}.ts`) }
        : undefined,
    );
    b.onResolve({ filter: /^@\// }, (args) => {
      const base = join(APP, 'src', args.path.slice(2));
      for (const candidate of [`${base}.ts`, join(base, 'index.ts')]) {
        try {
          readFileSync(candidate);
          return { path: candidate };
        } catch {
          /* next */
        }
      }
      return undefined;
    });
  },
};

// The project's public Supabase URL (the clips' bucket), as the app reads it.
let supabaseUrl = process.env.EXPO_PUBLIC_SUPABASE_URL;
if (!supabaseUrl) {
  try {
    supabaseUrl = /EXPO_PUBLIC_SUPABASE_URL=(\S+)/.exec(readFileSync(join(APP, '.env'), 'utf8'))?.[1];
  } catch {
    /* no .env here */
  }
}
if (!supabaseUrl) throw new Error('build: set EXPO_PUBLIC_SUPABASE_URL (or have it in ../.env)');
const posterIds = readdirSync(join(APP, 'site/public/exercises'))
  .filter((f) => /^[a-z_]+\.webp$/.test(f))
  .map((f) => f.replace('.webp', ''));

for (const [entry, out] of [
  ['src/server.ts', 'dist/server.mjs'],
  ['src/core.ts', 'dist/core.mjs'],
] as const) {
  await build({
    entryPoints: [join(ROOT, entry)],
    outfile: join(ROOT, out),
    bundle: true,
    format: 'esm',
    platform: 'node',
    target: 'node20',
    minify: false,
    legalComments: 'none',
    tsconfigRaw: {},
    plugins: [shims],
    define: {
      __WIDGET_HTML__: JSON.stringify(widgetHtml),
      __VERSION__: JSON.stringify(pkg.version),
      __SUPABASE_URL__: JSON.stringify(supabaseUrl),
      __POSTER_IDS__: JSON.stringify(posterIds),
    },
    banner: { js: "import { createRequire as __cr } from 'node:module'; const require = __cr(import.meta.url);" },
  });
}
console.log(`built dist/server.mjs, dist/core.mjs, dist/widget.html (${(widgetHtml.length / 1024).toFixed(0)} KB)`);
