export {
  BLOCKS,
  BLOCK_LENGTH,
  MAX_LEVEL,
  PLAN_BLOCKS,
  PROGRAM,
  PROGRAM_LENGTH,
  rebuildProgram,
  RETESTS,
  RETEST_MINUTES,
  RETEST_TESTS,
  TODAY_INDEX,
  blockIndexForRetest,
  blockName,
  checkpoints,
  clearRetestRequest,
  completedThrough,
  programSummary,
  currentLevels,
  dateFor,
  headlineLevels,
  isSystemRest,
  latestRetest,
  levelFor,
  levelLabel,
  measureLabel,
  movePlanFor,
  movesFor,
  painFor,
  recordRetest,
  requestRetest,
  retestBranch,
  retestResults,
  statusFor,
  useRetest,
  useRetestRequest,
  type DayStatus,
  type MovePlan,
  type ProgramDay,
  type ProgramSummary,
  type Retest,
  type RetestMeasurements,
  type RetestBranch,
  type RetestResult,
  type RetestRow,
  type SessionKind,
  type ZoneKey,
} from './model/program';

export {
  BLOCKS_12_WEEK,
  BLOCKS_6_WEEK,
  blockFor,
  blocksFor,
  isRetestDay,
  BASELINE_DAY,
  lastDayOf,
  retestDays,
  type Block,
  type PlanLength,
} from './model/blocks';

export {
  EXERCISES_BY_ID,
  EXERCISE_LIST,
  HEEL_RAISE_TEMPO,
  exerciseById,
  exerciseByTitle,
  exerciseCategoryLabel,
  exerciseText,
  loadsFascia,
  type Exercise,
  type ExerciseCategory,
  type ExerciseCueKey,
  type ExercisePosition,
  type ExerciseRationaleKey,
  type ExerciseTitleKey,
  type Tempo,
} from './model/exercises';

export { BLOCK_PLANS, firstNewExercise, planFor, type BlockPlan } from './model/catalogue';

export {
  MINUTES_BY_KIND,
  WEEK,
  kindFor,
  slotFor,
  templateFor,
  type DayKind,
  type DayTemplate,
} from './model/day-templates';

export {
  FIRST_LOADED_BLOCK,
  HEEL_RAISE_IDS,
  LOAD_NOTES,
  effectiveBlock,
  doseLabel,
  heelRaisePrescription,
  loadNoteFor,
  prescriptionFor,
  shortFootVariant,
  type Prescription,
} from './model/prescription';

export { ZONES, symmetryPct, zoneUnit } from './model/levels';

export {
  FLARE_PAIN,
  IN_SESSION_STOP_PAIN,
  LONG_ABSENCE_DAYS,
  OFFLOAD_MINUTES,
  SPIKE_JUMP,
  inSessionPain,
  isSpike,
  mobilityDayOf,
  nextOffset,
  offsetClears,
  resolveDay,
  type AdaptReason,
  type ResolveInput,
  type ResolvedDay,
  type ResolvedExercise,
} from './model/adapt';

export {
  allLogs,
  currentDay,
  dateKeyForDay,
  dayNumberFor,
  daysBetween,
  daysSinceLastSession,
  emptyLog,
  fromDateKey,
  hoursBaseline,
  hoursOnFeetOn,
  usualSessionMinute,
  logFor,
  painAverage,
  logPain,
  FIRST_STEP_CUTOFF_HOUR,
  firstStepOn,
  isFirstStepTime,
  painEntriesOn,
  painLatestOn,
  painOn,
  pastPlanEnd,
  phaseFor,
  programState,
  setProgramState,
  startProgram,
  toDateKey,
  todayDayNumber,
  useLogsVersion,
  useProgramState,
  writeLog,
  type DayLog,
  type PainEntry,
  type ProgramFocus,
  type ProgramPhase,
  type ProgramState,
} from './model/state';

export {
  attended,
  freezeUsedThisWeek,
  freezesLeft,
  resetFreezes,
  spendFreeze,
  streakThrough,
  useStreak,
  weekAttendance,
  type DayAttendance,
  type Streak,
  type StreakView,
} from './model/streak';

export {
  FIRST_MORNING_STRETCH_BLOCK,
  MORNING_STRETCH_COPY,
  MORNING_STRETCH_COPY_KEY,
  MORNING_STRETCH_ID,
  MORNING_STRETCH_MINUTES,
  hasMorningStretch,
  morningStretchCopy,
  morningStretchDone,
  morningStretchFor,
  setMorningStretchDone,
  type MorningStretch,
} from './model/morning-stretch';

export {
  MAINTENANCE_MINUTES,
  MAINTENANCE_RETEST_INTERVAL,
  regressionCopy,
  REGRESSION_PAIN_DAYS,
  REGRESSION_TARGET_BLOCK,
  isMaintenance,
  isMaintenanceRetestDay,
  maintenanceRetestDays,
  maintenanceSessionsPerWeek,
  maintenanceTransitionLines,
  nextMaintenanceRetestDay,
  regressionDetected,
  resolveMaintenanceDay,
} from './model/maintenance';

export {
  CONSISTENCY_WINDOW,
  SCORE_WEIGHTS,
  computeScore,
  consistencyNormalised,
  levelsAvgNormalised,
  painTrendNormalised,
} from './model/score';

export { CHECKPOINT_ICON, SESSION_META } from './ui/session-meta';
export { ZONE_META } from './ui/zone-meta';
export { settleOffset, stepBackAfterSession } from './model/offset';

// ── The weekly plan ──────────────────────────────────────────────────────────
export {
  CHAINS,
  EQUIPMENT,
  FALLBACKS,
  PLAN_META,
  planMeta,
  type ChainName,
  type Equipment,
  type GoalTag,
  type PlanKind,
  type PlanMeta,
} from './model/plan/catalogue-meta';
export { doseFor, doseSeconds, type PlanDose } from './model/plan/dose';
export { allowed, playableId, pogoAllowed, type EligibilityContext } from './model/plan/eligibility';
export {
  GOAL_ORDER,
  GOAL_SPECS,
  goalProgress,
  type Goal,
  type GoalStatus,
  type GoalType,
  type StartingFacts,
} from './model/plan/goals';
export {
  OUTCOME_KINDS,
  OUTCOME_SPORTS,
  outcomeProgress,
  type Outcome,
  type OutcomeArea,
  type OutcomeKind,
  type OutcomeProgress,
  type OutcomeSport,
} from './model/plan/outcome';
export {
  IN_SESSION_STOP,
  offersShortVersion,
  twoMinuteVersion,
  type AdjustedDay,
  type TodayReason,
} from './model/plan/today';
export {
  addDays,
  buildWeek,
  weekIndexFor,
  weekStartOf,
  type DayType,
  type DaysPerWeek,
  type PlanDay,
  type PlannedExercise,
  type Rationale,
  type RationaleKind,
  type SessionMinutes,
  type WeekPlan,
} from './model/plan/week';
export {
  DEFAULT_SETTINGS,
  abandonSession,
  beginSession,
  buildUpcomingWeek,
  ensureGoals,
  noteInSessionPain,
  noteSessionFeedback,
  exercisePrefs,
  goals,
  libraryFavourites,
  markCantDo,
  nextWeekPreview,
  outcome,
  painSeries,
  planDayOn,
  planSessionDone,
  planWeekOf,
  planSettings,
  postponeTest,
  rebuildRestOfWeek,
  recordSession,
  refreshGoals,
  reminderOverride,
  sessions,
  seedPlanSettings,
  setLastSessionFeedback,
  setOutcomeAreas,
  setOutcomeKind,
  setPlanSettings,
  swapFor,
  testDue,
  todayKey,
  todayPlan,
  toggleLibraryFavourite,
  usePlanVersion,
  usualStartMinute,
  weekPlan,
  type CantDoReason,
  type FootType,
  type PlanSettings,
  type SessionRecord,
  type SessionSource,
  type TodayHealth,
} from './model/plan/store';
export {
  completePlanSession,
  finishTestDay,
  lastTestDayOutcome,
  type CompletePlanSessionInput,
  type FinishTestDayInput,
  type TestDayOutcome,
} from './model/plan/finish';
export { NEXT_SESSION_HORIZON_DAYS, nextSession, useNextSession, type NextSession } from './model/plan/next-session';
export { requestPlanPush } from './model/plan/push-request';
export { BIG_MILESTONE, STREAK_MILESTONES, milestoneFor } from './model/streak';
