export {
  BLOCKS,
  BLOCK_LENGTH,
  MAX_LEVEL,
  PLAN_BLOCKS,
  PROGRAM,
  PROGRAM_LENGTH,
  RETESTS,
  RETEST_MINUTES,
  RETEST_TESTS,
  TODAY_INDEX,
  blockIndexForRetest,
  blockName,
  checkpoints,
  clearRetestRequest,
  REST_HOURS,
  completedThrough,
  nextSessionAt,
  programSummary,
  currentLevels,
  dateFor,
  headlineLevels,
  isSystemRest,
  latestRetest,
  levelFor,
  levelLabel,
  measureLabel,
  movePlanFor,
  movesFor,
  painFor,
  recordRetest,
  requestRetest,
  retestBranch,
  retestResults,
  statusFor,
  useRetest,
  useRetestRequest,
  type DayStatus,
  type MovePlan,
  type ProgramDay,
  type ProgramSummary,
  type Retest,
  type RetestMeasurements,
  type RetestBranch,
  type RetestResult,
  type RetestRow,
  type SessionKind,
  type ZoneKey,
} from './model/program';

export {
  BLOCKS_12_WEEK,
  BLOCKS_6_WEEK,
  blockFor,
  blocksFor,
  isRetestDay,
  lastDayOf,
  retestDays,
  type Block,
  type PlanLength,
} from './model/blocks';

export {
  EXERCISES_BY_ID,
  EXERCISE_LIST,
  HEEL_RAISE_TEMPO,
  exerciseById,
  exerciseByTitle,
  exerciseCategoryLabel,
  exerciseText,
  loadsFascia,
  type Exercise,
  type ExerciseCategory,
  type ExerciseCueKey,
  type ExercisePosition,
  type ExerciseRationaleKey,
  type ExerciseTitleKey,
  type Tempo,
} from './model/exercises';

export { BLOCK_PLANS, firstNewExercise, planFor, type BlockPlan } from './model/catalogue';

export {
  MINUTES_BY_KIND,
  WEEK,
  kindFor,
  slotFor,
  templateFor,
  type DayKind,
  type DayTemplate,
} from './model/day-templates';

export {
  FIRST_LOADED_BLOCK,
  HEEL_RAISE_IDS,
  LOAD_NOTES,
  effectiveBlock,
  heelRaisePrescription,
  loadNoteFor,
  prescriptionFor,
  shortFootVariant,
  type Prescription,
} from './model/prescription';

export { ZONES, symmetryPct, zoneUnit } from './model/levels';

export {
  FLARE_PAIN,
  IN_SESSION_STOP_PAIN,
  LONG_ABSENCE_DAYS,
  OFFLOAD_MINUTES,
  SPIKE_JUMP,
  inSessionPain,
  isSpike,
  mobilityDayOf,
  nextOffset,
  offsetClears,
  resolveDay,
  type AdaptReason,
  type ResolveInput,
  type ResolvedDay,
  type ResolvedExercise,
} from './model/adapt';

export {
  allLogs,
  currentDay,
  dateKeyForDay,
  daysBetween,
  daysSinceLastSession,
  emptyLog,
  fromDateKey,
  hoursBaseline,
  hoursOnFeetOn,
  logFor,
  painAverage,
  logPain,
  painEntriesOn,
  painLatestOn,
  painOn,
  pastPlanEnd,
  phaseFor,
  programState,
  setProgramState,
  toDateKey,
  useLogsVersion,
  useProgramState,
  writeLog,
  type DayLog,
  type PainEntry,
  type ProgramPhase,
  type ProgramState,
} from './model/state';

export {
  attended,
  freezeUsedThisWeek,
  freezesLeft,
  resetFreezes,
  spendFreeze,
  streakThrough,
  useStreak,
  weekAttendance,
  type DayAttendance,
  type Streak,
  type StreakView,
} from './model/streak';

export {
  FIRST_MORNING_STRETCH_BLOCK,
  MORNING_STRETCH_COPY,
  MORNING_STRETCH_COPY_KEY,
  MORNING_STRETCH_ID,
  MORNING_STRETCH_MINUTES,
  hasMorningStretch,
  morningStretchCopy,
  morningStretchDone,
  morningStretchFor,
  setMorningStretchDone,
  type MorningStretch,
} from './model/morning-stretch';

export {
  MAINTENANCE_MINUTES,
  MAINTENANCE_RETEST_INTERVAL,
  regressionCopy,
  REGRESSION_PAIN_DAYS,
  REGRESSION_TARGET_BLOCK,
  isMaintenance,
  isMaintenanceRetestDay,
  maintenanceRetestDays,
  maintenanceSessionsPerWeek,
  maintenanceTransitionLines,
  nextMaintenanceRetestDay,
  regressionDetected,
  resolveMaintenanceDay,
} from './model/maintenance';

export {
  CONSISTENCY_WINDOW,
  SCORE_WEIGHTS,
  computeScore,
  consistencyNormalised,
  levelsAvgNormalised,
  painTrendNormalised,
} from './model/score';

export { CHECKPOINT_ICON, SESSION_META } from './ui/session-meta';
export { ZONE_META } from './ui/zone-meta';
