import { CITE } from '@/lib/citations';
import type { Guide } from '../types';

export const FOOT_STRENGTHENING_PT: Guide = {
  lang: 'pt',
  page: 'footStrengthening',
  mainSource: CITE.taddeiRRI,
  published: '2026-10-09',
  updated: '2026-10-09',
  title: 'Exercícios para fortalecer os pés: progressão',
  description:
    'Exercícios para fortalecer os pés, dos músculos pequenos aos grandes, de sentado a uma perna só, com doses iniciais e o que os ensaios dizem sobre lesões.',
  h1: 'Exercícios para fortalecer os pés: o que fazer e como progredir',
  lede:
    'Os exercícios para fortalecer os pés treinam os pequenos músculos de dentro do pé e os maiores, que descem da panturrilha. Comece sentado com o exercício de pé curto, o abrir os dedos e a elevação do dedão, depois passe para em pé e depois para uma perna só. Nos ensaios, os músculos do pé ficaram maiores e mais fortes em cerca de dois meses.',
  intro: [
    'Esta página é o guia geral para o pé inteiro. Para pé chato, dedos ou calçados barefoot, as páginas mais específicas estão com link mais abaixo.',
  ],
  takeaways: [
    'Num ensaio de 2020 com 118\u00A0corredores amadores, o grupo sem treino dos pés teve 2,42\u00A0vezes mais chance de ter uma lesão de corrida ao longo de 12\u00A0meses do que o grupo que fez um programa de core do pé (Taddei e colegas). É um ensaio só.',
    'Num ensaio de 2019 com 57\u00A0corredores, cerca de dois meses de exercícios progressivos para os pés, feitos pelo menos cinco vezes por semana, deixaram maior e mais forte cada músculo do pé medido, enquanto o grupo de controle não mudou (Ridge e colegas).',
    'Uma revisão de 2025 com 28\u00A0ensaios e 1.399\u00A0pessoas apoiou os exercícios para os pés como forma de ganhar força no pé, mas classificou a certeza da evidência como baixa a muito baixa (Peters-Dickie e colegas).',
    'Em idosos de 60 a 90\u00A0anos, um programa supervisionado com cargas cada vez mais pesadas aumentou a força dos dedos em até 36% ao longo de três meses, enquanto um programa em casa não aumentou (Mickle e colegas, 2016).',
    'Na fascite plantar, acrescentar fortalecimento do pé ao alongamento não superou o alongamento sozinho num ensaio com 83\u00A0pessoas (Kamonseki e colegas, 2016).',
  ],
  toc: true,
  sections: [
    {
      h2: 'Quais são os músculos do pé e por que fortalecê-los?',
      paragraphs: [
        'O pé tem dois grupos de músculos:',
        {
          list: [
            'Os músculos **intrínsecos** (os pequenos músculos que começam e terminam dentro do pé) ficam embaixo do arco e entre os ossos. Eles sustentam o arco, abrem os dedos e fazem as pequenas correções que mantêm você em equilíbrio.',
            'Os músculos **extrínsecos** (os músculos maiores que começam na parte de baixo da perna e chegam ao pé por tendões longos) incluem a panturrilha, que levanta o calcanhar, e os músculos que viram e levantam o pé.',
          ],
        },
        'Um artigo de 2015 de McKeon e colegas chamou os músculos intrínsecos de “core do pé”. A ideia é a mesma dos músculos profundos do tronco: pequenos estabilizadores que mantêm os músculos maiores funcionando bem.',
        'Na visão deles, os cuidados com o pé mais frequentemente dão suporte ao pé por fora do que treinam esses músculos, então muita gente nunca os treina. Isso é um modelo, não uma causa comprovada de dor, mas explica por que os programas para os pés treinam primeiro os músculos pequenos e depois acrescentam a panturrilha e o equilíbrio.',
        'Um bom trabalho de força do pé cobre os dois grupos:',
        {
          list: [
            'O exercício de pé curto, o abrir os dedos e a elevação do dedão treinam os músculos intrínsecos.',
            'A elevação de calcanhar treina a panturrilha.',
            'Ficar em uma perna só faz os dois trabalharem juntos.',
          ],
        },
      ],
      cites: [CITE.mcKeon],
    },
    {
      h2: 'Por quais exercícios para fortalecer os pés começar?',
      keyFact: 'Uma revisão de 2023 com quatro ensaios concluiu que a maioria dos programas para os pés usava contrações sustentadas por 5\u00A0segundos e passava de sentado para em pé (de Souza e colegas).',
      paragraphs: [
        'Comece pelos exercícios que isolam os pequenos músculos do pé, feitos sentado, e depois acrescente o trabalho em pé e de equilíbrio conforme eles ficam fáceis. Uma revisão de 2023 de de Souza e colegas analisou quatro ensaios randomizados de fortalecimento intrínseco do pé. A maioria usou o exercício de pé curto e puxar a toalha com os dedos, com contrações sustentadas por cerca de 5\u00A0segundos e uma progressão de sentado para em pé.',
        'As doses abaixo são doses iniciais. Faça descalço. Se algum exercício levar a dor a **6/10 ou mais**, pare por hoje. Cada exercício tem a própria página com mais detalhes, com link a partir da [biblioteca de exercícios](/exercises/) (em inglês).',
      ],
      exercises: [
        {
          name: 'Pé curto, sentado',
          dose: '3\u00A0séries de 8, segurando cada uma por 5\u00A0segundos',
          often: 'Na maioria das sessões',
          feel: 'Uma contração embaixo do arco, com os dedos ainda relaxados',
          stop: 'Câimbra que não passa, ou dor em 6/10',
          how: 'Sente-se com o pé apoiado no chão. Sem dobrar os dedos, puxe a parte da frente do pé em direção ao calcanhar para o arco subir um pouco. Segure e relaxe. O movimento é pequeno. Se os dedos agarrarem o chão, alivie e tente de novo. A técnica completa está na página do [exercício de pé curto](/pt/exercicios/pe-curto/).',
          media: 'short_foot_seated',
          caption: 'Pé curto, sentado: puxe a parte da frente do pé em direção ao calcanhar, dedos no chão',
          alt: 'Uma figura sentada levantando o arco de um pé enquanto os dedos ficam apoiados no chão',
          evidence: { level: 'moderate', why: 'Usado na maioria dos ensaios da revisão de 2023 sobre fortalecimento do pé (de Souza), com evidência de baixa qualidade para mudanças no arco e no equilíbrio. Nunca foi testado sozinho para lesão ou dor.' },
        },
        {
          name: 'Abrir os dedos',
          dose: '3\u00A0séries de 10',
          often: 'Na maioria das sessões',
          feel: 'Trabalho ao longo das laterais do pé',
          stop: 'Câimbra que não passa',
          how: 'Com o pé apoiado no chão, abra os cinco dedos o máximo que conseguir, segure um instante e relaxe. Mantenha o calcanhar e a parte da frente do pé no chão.',
          media: 'toe_spread',
          caption: 'Abrir os dedos: afaste bem os dedos, calcanhar e parte da frente do pé no chão',
          alt: 'Um pé descalço no chão com os dedos afastados',
          evidence: { level: 'early', why: 'Um estudo com ressonância magnética mostra que ele ativa os pequenos músculos do pé (Gooding 2016). Não foi testado sozinho num ensaio de resultado.' },
        },
        {
          name: 'Elevação do dedão',
          dose: '3\u00A0séries de 8, segurando cada uma por 5\u00A0segundos',
          often: 'Na maioria das sessões',
          feel: 'Esforço no peito do pé e embaixo do arco',
          stop: 'Dor na articulação do dedão',
          how: 'Mantenha os quatro dedos menores no chão e levante só o dedão. Depois tente o contrário: dedão no chão, dedos menores para cima. No começo é difícil. Um movimento pequeno já basta.',
          media: 'big_toe_lift',
          caption: 'Elevação do dedão: só o dedão sobe',
          alt: 'Um pé descalço com o dedão levantado e os outros dedos apoiados no chão',
          evidence: { level: 'early', why: 'Um estudo com ressonância magnética mostra que ela ativa os pequenos músculos do pé (Gooding 2016). Usada em programas para os pés, mas não testada sozinha.' },
        },
        {
          name: 'Puxar a toalha com os dedos',
          dose: '3\u00A0séries de 8, segurando cada uma por 5\u00A0segundos',
          often: 'Na maioria das sessões',
          feel: 'Trabalho embaixo dos dedos e do arco',
          stop: 'Câimbra que não passa',
          how: 'Sente-se com uma toalha embaixo do pé. Dobre os dedos para puxar a toalha na sua direção, segure, depois solte e estique a toalha de novo. Isso treina os músculos longos dos dedos além dos pequenos.',
          media: 'towel_scrunch',
          caption: 'Puxar a toalha: dobre os dedos para juntar a toalha',
          alt: 'Um pé descalço dobrando os dedos para puxar uma toalha pelo chão',
          evidence: { level: 'early', why: 'Usado na maioria dos ensaios da revisão de 2023, normalmente junto com o exercício de pé curto. Não foi testado sozinho para dor ou lesão.' },
        },
        {
          name: 'Elevação de calcanhar com os dois pés',
          dose: '3\u00A0séries de 10',
          often: 'Na maioria das sessões',
          feel: 'Trabalho nas panturrilhas e na parte da frente dos pés',
          stop: 'Dor no calcanhar ou no Aquiles em 6/10',
          how: 'Segure numa parede. Suba na ponta dos dois pés em cerca de 3\u00A0segundos e desça em 3\u00A0segundos. Tente manter o peso sobre o lado do dedão, sem deixar o pé virar para fora. Mais na página de [elevação de calcanhar](/pt/exercicios/elevacao-de-calcanhar/).',
          media: 'heel_raise_double',
          caption: 'Elevação de calcanhar com os dois pés: sobe devagar, desce devagar',
          alt: 'Uma figura segurando numa parede e subindo na ponta dos dois pés',
          evidence: { level: 'moderate', why: 'A elevação de calcanhar tem apoio de ensaio para fascite plantar (Rathleff 2015). Aqui ela treina a panturrilha, o principal músculo extrínseco do pé.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.gooding, CITE.rathleff],
    },
    {
      h2: 'Como progredir de sentado para em pé e para uma perna só?',
      paragraphs: [
        'Progrida nos exercícios para fortalecer os pés colocando mais peso do corpo sobre o pé, um passo de cada vez. O trabalho sentado ensina o movimento. Em pé com os dois pés, você acrescenta metade do peso do corpo. Em um pé só, acrescenta todo o peso, mais o equilíbrio. Só suba quando o passo atual parecer fácil e controlado.',
        'O Walkito usa os mesmos três passos para o exercício de pé curto: sentado, depois em pé com os dois pés, depois em uma perna. Quando o arco é o foco do seu plano, no plano da semana seguinte você sobe um passo se marcou as suas duas últimas sessões com esse exercício como fáceis e a sua dor da manhã não aumentou. Uma sessão marcada como difícil, ou a dor da manhã 2\u00A0pontos mais alta, faz você voltar um passo. Os dois passos seguintes estão mais abaixo.',
      ],
      bullets: [
        '**Passo 1, sentado.** Pé curto, abrir os dedos, elevação do dedão e puxar a toalha com os dedos, tudo sentado.',
        '**Passo 2, em pé com os dois pés.** O pé curto sustentado em pé e a elevação de calcanhar com os dois pés.',
        '**Passo 3, uma perna.** O pé curto sustentado em uma perna, depois equilíbrio em uma perna com o arco levantado.',
        '**Depois.** Elevação de calcanhar em uma perna e, para quem corre, pequenos saltos. São cargas maiores. Só acrescente quando o passo 3 estiver fácil.',
      ],
      exercises: [
        {
          name: 'Pé curto, em pé com os dois pés',
          dose: '3\u00A0séries de 8, segurando cada uma por 5\u00A0segundos',
          often: 'Quando a versão sentado ficar fácil',
          feel: 'O arco subindo com o peso do corpo em cima',
          stop: 'Dor em 6/10, ou os dedos continuam agarrando o chão',
          how: 'Fique em pé com o peso distribuído igualmente nos dois pés. Levante os arcos do mesmo jeito que sentado, dedos relaxados, joelhos levemente dobrados. Segure e relaxe.',
          media: 'short_foot_double',
          caption: 'Pé curto, em pé: levante os dois arcos sem dobrar os dedos',
          alt: 'Uma figura em pé levantando o arco dos dois pés',
          evidence: { level: 'moderate', why: 'A progressão de sentado para em pé foi usada na maioria dos ensaios da revisão de 2023. Não foi testada sozinha para dor ou lesão.' },
        },
        {
          name: 'Pé curto, em uma perna',
          dose: '3\u00A0séries de 10, segurando cada uma por 5\u00A0segundos',
          often: 'Quando a versão com os dois pés ficar fácil',
          feel: 'O pé e o tornozelo inteiros trabalhando para manter você firme',
          stop: 'Dor em 6/10, ou você não consegue manter o arco levantado',
          how: 'Fique em um pé só perto de uma parede. Levante o arco e segure enquanto se equilibra. Encoste na parede se precisar.',
          media: 'short_foot_single',
          caption: 'Pé curto, em uma perna: segure o arco enquanto se equilibra',
          alt: 'Uma figura em um pé só com o arco levantado e uma mão perto de uma parede',
          evidence: { level: 'early', why: 'Usado como último passo nos programas de core do pé. Há pouca pesquisa sobre esta variação exata.' },
        },
        {
          name: 'Equilíbrio em uma perna',
          dose: '3\u00A0vezes de 20\u00A0segundos, cada perna',
          often: 'Dias de equilíbrio',
          feel: 'Pequenas correções constantes no pé',
          stop: 'Dor em 6/10, ou tontura',
          how: 'Fique em um pé só e olhe para um ponto fixo à sua frente. Deixe o pé fazer pequenos balanços. Esse é o trabalho. Fique perto de uma parede ou de uma bancada. Mais na página de [equilíbrio em uma perna](/pt/exercicios/equilibrio-uma-perna/).',
          media: 'single_leg_hold',
          caption: 'Equilíbrio em uma perna: deixe o pé fazer as correções',
          alt: 'Uma figura se equilibrando em uma perna ao lado de uma parede',
          evidence: { level: 'moderate', why: 'O treino de equilíbrio reduziu as taxas de entorse de tornozelo numa metanálise (Bellows 2018). Para a força do pé em si, não foi testado sozinho.' },
        },
      ],
      cites: [CITE.deSouzaIFM, CITE.bellows],
    },
    {
      h2: 'Exercícios para fortalecer os pés previnem lesões de corrida?',
      keyFact: 'Num ensaio de 2020 com 118\u00A0corredores, quem não fez o treino de core do pé teve 2,42\u00A0vezes mais chance de se lesionar ao longo de 12\u00A0meses (Taddei e colegas).',
      paragraphs: [
        'Os exercícios para fortalecer os pés **reduziram as lesões de corrida num bom ensaio, mas só num.** Em 2020, Taddei e colegas dividiram por sorteio 118\u00A0corredores amadores de longa distância num grupo de core do pé (57\u00A0corredores) e num grupo de controle (61\u00A0corredores). O grupo de core do pé fez um curso supervisionado de cerca de dois meses para os músculos do pé e do tornozelo e depois continuou treinando com supervisão a distância.',
        'Ao longo de 12\u00A0meses, o grupo de controle teve 2,42\u00A0vezes mais chance de ter uma lesão de corrida. Os autores viram o efeito aparecer depois de cerca de quatro a oito meses de treino.',
        'Um ensaio anterior e menor da mesma equipe, com 28\u00A0corredores, concluiu que cerca de dois meses de treino dos pés aumentaram o tamanho de cada músculo do pé medido, em comparação com o grupo de controle. Os corredores também passaram a empurrar o chão com mais força.',
        'Os dois ensaios vêm de um único grupo de pesquisa no Brasil, com corredores amadores que não estavam lesionados no início. Ainda não sabemos se o programa ajuda iniciantes ou pessoas que já têm dor. Para corredores que estão com dor no calcanhar agora, comece por [dor no calcanhar em corredores](/heel-pain-runners/) (em inglês).',
      ],
      sourceNote: 'Taddei 2020 (Am J Sports Med): grupo de controle com 2,42\u00A0vezes mais chance de se lesionar (IC 95% 1,98 a 3,62), p = 0,035, ensaio randomizado simples-cego, acompanhamento de 12\u00A0meses. Taddei 2020 (Phys Ther Sport): ensaio randomizado simples-cego de prova de conceito, 28\u00A0corredores, volume muscular por ressonância magnética.',
      cites: [CITE.taddeiRRI, CITE.taddeiMuscle],
    },
    {
      h2: 'Quanto tempo leva para fortalecer os pés?',
      keyFact: 'Num ensaio de 2019 com 57\u00A0corredores, os músculos do pé cresceram e ficaram mais fortes ao longo de cerca de dois meses, com alguns músculos já maiores depois de um mês (Ridge e colegas).',
      paragraphs: [
        'Nos ensaios, os músculos do pé ficaram mensuravelmente mais fortes em **cerca de dois meses de treino regular**. Em 2019, Ridge e colegas sortearam 57\u00A0corredores entre:',
        {
          list: [
            'Exercícios para fortalecer os pés.',
            'Andar com calçados minimalistas.',
            'Não mudar nada.',
          ],
        },
        'O grupo dos exercícios fez exercícios progressivos com resistência pelo menos cinco vezes por semana. Depois de cerca de dois meses, cada músculo do pé medido estava maior e mais forte nos dois grupos ativos, sem mudança no grupo de controle. Alguns músculos já estavam maiores na avaliação de um mês.',
        'O formato do arco muda mais devagar, e menos. Uma revisão de 2023 com quatro ensaios concluiu que o fortalecimento intrínseco do pé não mudou o quanto o arco se move depois de um mês, mas mudou depois de dois meses, com evidência de baixa qualidade.',
        'Num estudo pequeno de Mulligan e Cook com 21\u00A0pessoas e sem grupo de controle, a queda do navicular (o quanto o arco interno afunda quando você fica em pé) diminuiu em média 1,8\u00A0mm depois de um mês de treino de pé curto. É uma mudança real, mas pequena.',
      ],
      cites: [CITE.ridgeMinimalist, CITE.deSouzaIFM, CITE.mulliganCook],
    },
    {
      h2: 'Calçados barefoot ou minimalistas fortalecem os pés?',
      paragraphs: [
        'Andar com calçados minimalistas fortaleceu os músculos do pé mais ou menos tanto quanto os exercícios para os pés num ensaio. No mesmo estudo de 2019 de Ridge e colegas, os corredores que aumentaram aos poucos o número de passos diários dados com calçados minimalistas ganharam tamanho e força muscular parecidos com os do grupo dos exercícios ao longo de cerca de dois meses. Os autores sugeriram que trocar de calçado pode ser mais fácil de manter do que fazer exercícios.',
        'Trocar rápido demais tem os seus próprios riscos, principalmente para a corrida. O guia de [calçados barefoot](/pt/calcados-barefoot/) explica como fazer a transição e quem deve ter cuidado.',
      ],
      cites: [CITE.ridgeMinimalist],
    },
    {
      h2: 'Idosos conseguem fortalecer os pés?',
      keyFact: 'Num ensaio de 2016 com adultos de 60 a 90\u00A0anos, o treino supervisionado e progressivo dos pés aumentou a força dos dedos em até 36%, enquanto um programa em casa não mudou a força (Mickle e colegas).',
      paragraphs: [
        'Idosos conseguem fortalecer os pés, e num ensaio a versão supervisionada com cargas cada vez mais pesadas foi a que funcionou. Num ensaio de 2016, Mickle e colegas dividiram 85\u00A0pessoas de 60 a 90\u00A0anos entre uma aula supervisionada com exercícios para os pés cada vez mais pesados e um programa de exercícios em casa, além de um grupo separado de 32\u00A0controles.',
        'Depois de três meses, o grupo supervisionado aumentou a força dos dedos em até 36% e conseguiu ficar mais tempo em uma perna. O grupo de casa e o grupo de controle não mostraram mudança na força dos dedos.',
        'Uma revisão de 2022 com nove estudos em adultos de 65\u00A0anos ou mais concluiu que o fortalecimento intrínseco do pé ajudou a força, o equilíbrio e a mobilidade, e possivelmente reduziu o risco de quedas, com pouco efeito no padrão de marcha. Os autores classificaram a qualidade da evidência como razoável.',
        'Então suba para versões mais difíceis conforme elas ficam fáceis e **mantenha uma parede ou bancada por perto no trabalho de equilíbrio.** Se quedas são uma preocupação, um fisioterapeuta pode montar um programa seguro.',
      ],
      cites: [CITE.mickleToe, CITE.futrellOlder],
    },
    {
      h2: 'Fortalecer os pés ajuda na fascite plantar ou no pé chato?',
      paragraphs: [
        'Na fascite plantar, o fortalecimento do pé somado ao alongamento não foi melhor que o alongamento sozinho num ensaio que comparou os dois. Em 2016, Kamonseki e colegas dividiram 83\u00A0pessoas com fascite plantar em três grupos por dois meses:',
        {
          list: [
            'Fortalecimento do pé mais alongamento.',
            'Fortalecimento do pé e do quadril mais alongamento.',
            'Só alongamento.',
          ],
        },
        'Os três grupos melhoraram na dor e na função, e nenhum grupo se saiu melhor que os outros. Para dor no calcanhar, veja [exercícios para fascite plantar](/pt/exercicios-fascite-plantar/).',
        'No pé chato flexível, um ensaio de 2023 com 52\u00A0pessoas concluiu que um programa misto que incluía o exercício de pé curto mudou o formato do arco mais do que no grupo de controle. Os detalhes, e os limites do treino de pé curto sozinho, estão na página de [exercícios para pé chato](/pt/exercicios-pe-chato/). Se a sua dor fica principalmente nos dedos, o guia de [exercícios para fortalecer os dedos dos pés](/pt/exercicios-para-fortalecer-os-dedos-do-pe/) vai mais fundo, e para o tornozelo há [exercícios para fortalecer o tornozelo](/pt/exercicios-para-fortalecer-tornozelo/).',
      ],
      cites: [CITE.kamonseki, CITE.brijwasi],
    },
    {
      h2: 'Qual é a força da evidência sobre o fortalecimento dos pés?',
      paragraphs: [
        'A evidência de que os exercícios para os pés deixam os músculos do pé mais fortes aponta na mesma direção, mas os estudos são pequenos. Uma revisão de 2025 de Peters-Dickie e colegas incluiu 28\u00A0ensaios randomizados com 1.399\u00A0pessoas. Ela apoiou os exercícios para os pés como forma de aumentar a força do pé, mas classificou a certeza como baixa a muito baixa, principalmente porque havia poucos estudos por pergunta e muitos tinham alto risco de viés. Os resultados sobre o tamanho dos músculos foram mistos.',
        'A evidência de que pés mais fortes significam menos lesões é ainda mais fraca e se apoia principalmente no único ensaio com corredores citado acima. **O fortalecimento dos pés é barato e de baixo risco, e de fato aumenta a força.** Se ele previne a sua próxima lesão ainda é uma questão em aberto. Mais sobre como estes guias classificam a pesquisa está na página de [evidência científica](/science/) (em inglês).',
      ],
      sourceNote: 'Peters-Dickie 2025: as metanálises mostraram que calçados minimalistas aumentaram a força dos dedos 2 a 5, e que os exercícios para os pés reduziram o movimento do arco durante a corrida; certeza baixa a muito baixa.',
      cites: [CITE.petersDickie],
    },
  ],
  faq: [
    {
      q: 'Com que frequência fazer exercícios para fortalecer os pés?',
      cites: [CITE.ridgeMinimalist],
      a: 'A maioria dos programas da pesquisa era feita várias vezes por semana. Num ensaio de 2019, corredores fizeram exercícios progressivos para os pés pelo menos cinco vezes por semana e ganharam tamanho e força muscular ao longo de cerca de dois meses. Uma sessão curta na maioria dos dias é um começo razoável. Os músculos precisam de alguma recuperação, então, se os seus pés estiverem doloridos na manhã seguinte, faça um dia mais leve.',
    },
    {
      q: 'Puxar a toalha com os dedos ou pé curto: qual é melhor?',
      cites: [CITE.jung, CITE.lynn],
      a: 'O exercício de pé curto trabalha os músculos do arco de forma mais direta. Num estudo de laboratório com 20\u00A0pessoas, o principal músculo do arco interno ficou claramente mais ativo durante o pé curto do que durante o puxar a toalha (Jung 2011). Num ensaio pequeno com 24\u00A0pessoas, um mês de treino de pé curto melhorou um teste de equilíbrio mais do que o puxar a toalha (Lynn 2012). Puxar a toalha continua sendo um primeiro passo útil e fácil.',
    },
    {
      q: 'Exercícios para fortalecer os pés devem doer?',
      a: 'Não. Você deve sentir esforço, e talvez uma câimbra leve embaixo do arco no começo, que passa quando você relaxa. Dor aguda, ou dor em 6/10 ou mais, quer dizer parar por hoje. Se o mesmo ponto dói toda vez, ou se a dor não deixa você dormir, procure um profissional de saúde antes de continuar.',
    },
    {
      q: 'Andar descalço basta para fortalecer os pés?',
      cites: [CITE.ridgeMinimalist],
      a: 'Pode ajudar. Num ensaio de 2019, corredores que aumentaram devagar os passos diários com calçados minimalistas ganharam força no pé parecida com a de um grupo de exercícios ao longo de cerca de dois meses. Foi uma mudança gradual, não uma troca repentina. Andar descalço rápido demais pode sobrecarregar o pé, então vá aumentando devagar e mantenha os exercícios se você gosta deles.',
    },
    {
      q: 'Fortalecer os pés pode levantar um arco caído?',
      cites: [CITE.mulliganCook, CITE.cheng],
      a: 'Só um pouco, e só no pé chato flexível. Num estudo pequeno com 21\u00A0pessoas sem dor no pé e sem grupo de controle, o arco afundou 1,8\u00A0mm a menos depois de um mês de treino de pé curto. Uma revisão de 2024 concluiu que os programas de pé curto só mudaram as medidas do arco quando duraram mais tempo. Espere um pé mais forte e mais firme, não um novo formato de arco.',
    },
    {
      q: 'Preciso de equipamento para fortalecer os pés?',
      a: 'Não. Os exercícios desta página precisam de um chão, uma cadeira, uma toalha e uma parede para se apoiar no equilíbrio. Faça descalço, para ver e sentir o pé se mover. Mais tarde, você pode acrescentar carga com a elevação de calcanhar em uma perna ou com uma mochila, mas o peso do corpo basta por muito tempo.',
    },
  ],
  redFlags: {
    h2: 'Procure primeiro um profissional de saúde se',
    bullets: [
      'você tem dormência, formigamento ou queimação nos pés, ou tem diabetes com qualquer ferida ou machucado na pele',
      'um pé está ficando mais fraco, ou a parte da frente do pé arrasta ou bate no chão quando você anda',
      'um arco está caindo rapidamente ou a parte de dentro do tornozelo está inchada e dolorida',
      'a dor fica num ponto do osso e piora a cada caminhada ou corrida, o que pode ser uma fratura por estresse',
      'o pé está vermelho, quente ou inchado, ou você está com febre',
      'você não consegue apoiar o peso no pé',
      'a dor continua piorando mesmo com repouso e exercícios mais leves',
    ],
  },
  program: {
    h2: 'Fazendo isso como um plano',
    text: 'O Walkito monta um plano semanal em torno de uma meta e inclui os exercícios para os pés desta página: o exercício de pé curto de sentado até em uma perna, o abrir os dedos, a elevação do dedão, o puxar a toalha com os dedos, a elevação de calcanhar e o trabalho de equilíbrio. Ele começa os exercícios de arco com 3\u00A0séries de 8 e 5\u00A0segundos parado e o equilíbrio com 3\u00A0vezes de 20\u00A0segundos, e a cada novo plano semanal sobe o seu exercício de foco um passo quando você marcou as suas duas últimas sessões com ele como fáceis e a sua dor da manhã não aumentou.',
    more: [
      'Você escolhe sessões de 3, 5 ou 10\u00A0minutos. Um teste curto, a cada 14\u00A0dias no início, mede a resistência da panturrilha, a sustentação do arco e o equilíbrio, para você ver o que está mudando. O Walkito é um programa de exercícios para adultos. Ele não faz diagnóstico e não substitui um profissional de saúde.',
    ],
    cta: 'Comece com 3\u00A0minutos por dia.',
  },
  crumb: 'Fortalecer os pés',
  campaign: 'guide-foot-strength-pt',
};
